Repository yunionio/docs, pull requests merged in 2019-08, with the labels that each got.

#9 修改 Edit this page 链接错误
  config.toml
  content/zh/_redirects
  content/zh/index.html
  content/zh/index.md
  i18n/de.toml
  i18n/en.toml
  i18n/no.toml
  i18n/zh.toml
  layouts/partials/page-meta-links.html
Labels: approved, lgtm, size/L

#10 修改首页样式
  assets/scss/_variables_project.scss
  config.toml
  content/zh/_index.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  static/images/logo.svg
  static/js/search.js
Labels: approved, lgtm, size/L

#11 新增首页支持平台logo，融合云架构图片 其他首页样式调整
  assets/scss/_variables_project.scss
  content/zh/_index.html
  layouts/partials/footer.html
  static/images/frame.svg
  static/images/provider/aliyun.svg
  static/images/provider/aws.svg
  static/images/provider/azure.svg
  static/images/provider/gcp.svg
  static/images/provider/huawei.svg
  static/images/provider/k8s.svg
  static/images/provider/kvm.svg
  static/images/provider/openstack.svg
  static/images/provider/qcloud.svg
  static/images/provider/ucloud.svg
  static/images/provider/vmware.svg
Labels: approved, lgtm, size/XL

#12 添加 ha 部署，服务框架介绍的文档
  content/zh/docs/contribute/_index.md
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/images/auth_framework.png
  content/zh/docs/contribute/images/onecloud-services.png
  content/zh/docs/contribute/images/service_framework.png
  content/zh/docs/contribute/services.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/images/k8s.png
Labels: size/XL

#13 添加技术支持ipmi 更换架构图片
  assets/scss/_variables_project.scss
  content/zh/_index.html
  static/images/frame.png
  static/images/provider/ipmi.svg
  static/images/provider/zstack.svg
Labels: approved, lgtm, size/S
