Repository yunionio/docs, pull requests merged in 2019-07, with the labels that each got.

#1 开发贡献 稍微完善
  content/contribute/_index.md
  content/contribute/images/cc.png
  content/contribute/images/reviewer_label.png
  content/contribute/images/robot_review_label.png
  content/contribute/images/setReviwer.png
  content/contribute/images/submitPR.png
Labels: approved, lgtm, size/M

#3 更新climc命令文档
  content/howto/climc/_index.md
Labels: approved, lgtm, size/S

#4 补充mariadb的设置
  content/setup/controlplane.md
Labels: approved, lgtm, size/S

#7 update theme
  .gitignore
  assets/scss/_variables_project.scss
  content/zh/_index.html
  layouts/partials/favicons.html
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  package-lock.json
Labels: approved, lgtm, size/XXL

#8 update theme
  assets/scss/_variables_project.scss
  config.toml
  content/zh/_index.html
  content/zh/docs/index.json
  content/zh/index.html
  content/zh/index.md
  content/zh/search.md
  layouts/home.html
  layouts/partials/search-input.html
  layouts/partials/sidebar-tree.html
  layouts/swagger/baseof.html
  static/images/onecloud.792d54123.svg
  static/js/search.js
Labels: approved, lgtm, size/L
