Repository yunionio/docs, pull requests merged in 2020-08, with the labels that each got.

#48 update yunion.repo url
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
  scripts/cherry_pick_pull.sh
Labels: approved

#49 Automated cherry pick of #48: update yunion.repo url
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
  scripts/cherry_pick_pull.sh
Labels: approved

#55 Automated cherry pick of #52: add upgrade page
  content/zh/docs/setup/upgrade.md
Labels: approved, size/M

#56 update v3.2 upgrade doc
  content/zh/docs/setup/upgrade.md
Labels: approved, size/M

#63 clean cache when upgrade
  content/zh/docs/setup/upgrade.md
Labels: approved, size/XS

#64 Automated cherry pick of #63: clean cache when upgrade
  content/zh/docs/setup/upgrade.md
Labels: approved, size/XS

#65 Automated cherry pick of #63: clean cache when upgrade
  content/zh/docs/setup/upgrade.md
Labels: approved, size/XS

#66 allinone部署说明优化
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/howto/server/create/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
Labels: size/M

#67 Automated cherry pick of #66: allinone部署说明优化
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/howto/server/create/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
Labels: size/M

#71 fix: quickstart ssh-copy-id
  content/zh/docs/quickstart/allinone.md
Labels: approved, size/XS
