Repository yunionio/docs, pull requests merged in 2020-12, with the labels that each got.

#106 feat(host): add docs explain host wraning and error
  content/zh/docs/howto/host/kvm.md
Labels: approved, size/M

#114 Update changelog 1218
  content/zh/docs/changelog/release-3.3/3-3-8.md
  content/zh/docs/changelog/release-3.3/_index.md
  content/zh/docs/changelog/release-3.4/3-4-0.md
  content/zh/docs/changelog/release-3.4/3-4-11.md
  content/zh/docs/changelog/release-3.4/_index.md
Labels: approved, size/L

#116 chore(static): add bonc user
  content/zh/_index.html
  static/images/provider/bonc.png
Labels: approved
