Repository yunionio/docs, pull requests merged in 2020-06, with the labels that each got.

#35 Add a doc of deploying onecloud on minikube to take a glance
  content/zh/docs/quickstart/minikube.md
Labels: approved, lgtm, size/L

#36 docs:优化minikube安装体验
  README.md
  content/zh/docs/quickstart/minikube.md
Labels: approved, lgtm, size/S

#37 add:doc/contrib 本地调试运行
  content/zh/docs/contribute/contrib.md
Labels: approved, lgtm, size/M

#38 Dlp fix issue
  content/zh/docs/howto/climc/_index.md
Labels: approved, lgtm, size/M

#39 镜像内容更新
  content/zh/docs/howto/image/operation.md
  content/zh/docs/howto/image/query.md
  content/zh/docs/howto/image/upload.md
Labels: approved, lgtm, size/L
