Repository yunionio/docs, pull requests merged in 2020-11, with the labels that each got.

#82 remove duplicate wget
  content/zh/docs/howto/image/upload.md
Labels: approved, size/XS

#83 Automated cherry pick of #82: remove duplicate wget
  content/zh/docs/howto/image/upload.md
Labels: approved, size/XS

#84 Automated cherry pick of #82: remove duplicate wget
  content/zh/docs/howto/image/upload.md
Labels: approved, size/XS

#88 fix(quickstart): make minikube deploy steps runable
  content/zh/docs/quickstart/minikube.md
Labels: approved

#90 完善本地开发调试
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/images/region_error.png
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/images/oo_syncuser.png
Labels: size/L

#91 Automated cherry pick of #90: feat(howto): 完善 非控制节点认证配置
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/images/region_error.png
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/images/oo_syncuser.png
Labels: size/L

#94 chore(changelog): update
  content/zh/docs/changelog/release-3.4/3-4-9.md
Labels: approved

#97 Automated cherry pick of #96: chore(changelog): update each release description
  assets/icons/logo.svg
  assets/scss/_variables_project.scss
  config.toml
  content/zh/docs/changelog/release-3.3/_index.md
  content/zh/docs/changelog/release-3.4/3-4-9.md
  content/zh/docs/changelog/release-3.4/_index.md
  layouts/partials/navbar.html
  static/images/logo.svg
Labels: approved, size/L

#104 Automated cherry pick of #103: fix(climc): adjust aksk operation order
  content/zh/docs/howto/climc/_index.md
Labels: approved

#103 Hotfix/climc
  content/zh/docs/howto/climc/_index.md
Labels: approved, size/M
