Repository yunionio/docs, pull requests merged in 2020-01, with the labels that each got.

#21 fix host setup docs
  content/zh/docs/setup/host.md
Labels: size/XS

#22 fix edition change
  content/zh/docs/setup/controlplane.md
Labels: size/S

#23 update docs to use 2.13 repo
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: approved, lgtm, size/M

#24 host setup add fetchclient
  content/zh/docs/setup/host.md
Labels: size/XS

#25 add baremetal setup doc
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: size/S

#26 baremetal setup fix
  content/zh/docs/setup/baremetal.md
Labels: size/M
