Repository yunionio/docs, pull requests merged in 2021-08, with the labels that each got.

#410 feature: add contents for onpremise network and storage
  content/zh/docs/060_onpremise/_index.md
  content/zh/docs/060_onpremise/compute/_index.md
  content/zh/docs/060_onpremise/compute/baremetal/_index.md
  content/zh/docs/060_onpremise/compute/host/_index.md
  content/zh/docs/060_onpremise/compute/host/kvm.md
  content/zh/docs/060_onpremise/compute/image/_index.md
  content/zh/docs/060_onpremise/compute/network/10_host.md
  content/zh/docs/060_onpremise/compute/network/20_baremetal.md
  content/zh/docs/060_onpremise/compute/network/_index.md
  content/zh/docs/060_onpremise/compute/network/network.png
  content/zh/docs/060_onpremise/compute/scheduler/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/20_recycle.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/30_snapshot.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/40_migrate.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/20_share/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/_index.md
  content/zh/docs/060_onpremise/compute/storage/10_baremetal.md
  content/zh/docs/060_onpremise/compute/storage/20_vmware.md
  content/zh/docs/060_onpremise/compute/storage/_index.md
  content/zh/docs/060_onpremise/lb/_index.md
  content/zh/docs/060_onpremise/network/_index.md
  content/zh/docs/060_onpremise/storage/_index.md
  content/zh/docs/100_monitor_ops/10_monitor/_index.md
  content/zh/docs/100_monitor_ops/_index.md
Labels: approved, size/L

#411 Automated cherry pick of #410: feature: add contents for onpremise network and storage
  content/zh/docs/060_onpremise/_index.md
  content/zh/docs/060_onpremise/compute/_index.md
  content/zh/docs/060_onpremise/compute/baremetal/_index.md
  content/zh/docs/060_onpremise/compute/host/_index.md
  content/zh/docs/060_onpremise/compute/host/kvm.md
  content/zh/docs/060_onpremise/compute/image/_index.md
  content/zh/docs/060_onpremise/compute/network/10_host.md
  content/zh/docs/060_onpremise/compute/network/20_baremetal.md
  content/zh/docs/060_onpremise/compute/network/_index.md
  content/zh/docs/060_onpremise/compute/network/network.png
  content/zh/docs/060_onpremise/compute/scheduler/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/20_recycle.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/30_snapshot.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/40_migrate.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/10_local/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/20_share/_index.md
  content/zh/docs/060_onpremise/compute/storage/01_kvm/_index.md
  content/zh/docs/060_onpremise/compute/storage/10_baremetal.md
  content/zh/docs/060_onpremise/compute/storage/20_vmware.md
  content/zh/docs/060_onpremise/compute/storage/_index.md
  content/zh/docs/060_onpremise/lb/_index.md
  content/zh/docs/060_onpremise/network/_index.md
  content/zh/docs/060_onpremise/storage/_index.md
  content/zh/docs/100_monitor_ops/10_monitor/_index.md
  content/zh/docs/100_monitor_ops/_index.md
Labels: approved, size/L

#412 update v3.7 changelog
  content/en/docs/changelog/release-3.6/3-6-20.md
  content/en/docs/changelog/release-3.6/3-6-21.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-6.md
  content/en/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.6/3-6-20.md
  content/zh/docs/changelog/release-3.6/3-6-21.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-6.md
  content/zh/docs/changelog/release-3.7/_index.md
Labels: approved

#413 Add release notes page
  content/zh/docs/release/_index.md
  content/zh/docs/release/v3_7_5.md
  content/zh/docs/release/v3_7_6.md
Labels: approved, size/M

#414 Automated cherry pick of #413: Add release notes page
  content/zh/docs/release/_index.md
  content/zh/docs/release/v3_7_5.md
  content/zh/docs/release/v3_7_6.md
Labels: approved, size/M

#415 Automated cherry pick of #413: Add release notes page
  content/zh/docs/release/_index.md
  content/zh/docs/release/v3_7_5.md
  content/zh/docs/release/v3_7_6.md
Labels: approved, size/M

#416 Update v3_7_6.md
  content/zh/docs/release/v3_7_6.md
Labels: size/S

#417 Automated cherry pick of #416: Update v3_7_6.md
  content/zh/docs/release/v3_7_6.md
Labels: approved, size/S

#418 Automated cherry pick of #416: Update v3_7_6.md
  content/zh/docs/release/v3_7_6.md
Labels: approved

#421 fix(release-note): update v3.7.6
  content/zh/docs/release/v3_7_6.md
Labels: size/XS

#422 Automated cherry pick of #421: fix(release-note): update v3.7.6
  content/zh/docs/release/v3_7_6.md
Labels: size/XS

#424 add blog for monitor agent
  content/zh/blog/_posts/2021-08-05-monitor-agent.md
Labels: size/L

#426 Automated cherry pick of #424: add blog for monitor agent
  content/zh/blog/_posts/2021-08-05-monitor-agent.md
Labels: size/L

#425 Automated cherry pick of #424: add blog for monitor agent
  content/zh/blog/_posts/2021-08-05-monitor-agent.md
Labels: size/L

#427 fix: migrate monitor agent from blog to documentation
  content/zh/docs/100_monitor_ops/10_monitor/20_monitoragent.md
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805163249.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805163416.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805164138.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805164239.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165029.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165213.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165957.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170059.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170450.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170928.png
Labels: approved, size/S

#428 Automated cherry pick of #427: fix: migrate monitor agent from blog to documentation
  content/zh/docs/100_monitor_ops/10_monitor/20_monitoragent.md
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805163249.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805163416.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805164138.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805164239.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165029.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165213.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805165957.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170059.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170450.png
  content/zh/docs/100_monitor_ops/10_monitor/images/20210805170928.png
Labels: approved, size/S

#430 fix: add max_allowed_packet to my.cnf
  content/zh/docs/020_setup/controlplane.md
  content/zh/docs/020_setup/db-ha.md
Labels: approved, size/XS

#431 Automated cherry pick of #430: fix: add max_allowed_packet to my.cnf
  content/zh/docs/020_setup/controlplane.md
  content/zh/docs/020_setup/db-ha.md
Labels: approved, size/XS

#432 Automated cherry pick of #430: fix: add max_allowed_packet to my.cnf
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
Labels: approved, size/XS

#436 fix(upgrade): version to v3.7.6
  content/zh/docs/020_setup/upgrade.md
Labels: approved, size/XS

#437 Automated cherry pick of #436: fix(upgrade): version to v3.7.6
  content/zh/docs/020_setup/upgrade.md
Labels: approved

#438 Automated cherry pick of #436: fix(upgrade): version to v3.7.6
  content/zh/docs/setup/upgrade.md
Labels: approved

#439 fix: update SDK intro
  content/zh/docs/140_apisdk/02_sdk.md
Labels: approved, size/S

#440 Automated cherry pick of #439: fix: update SDK intro
  content/zh/docs/140_apisdk/02_sdk.md
Labels: approved, size/S

#441 feat: add misc build scripts
  .gitignore
  Dockerfile
  Dockerfile-img
  Makefile
  Makefile.ee
  content/en/docs/changelog/_index.md
  content/en/docs/roadmap/_index.md
  content/zh/blog/_index.md
  content/zh/docs/140_apisdk/_index.md
  content/zh/docs/170_roadmap/_index.md
  content/zh/docs/changelog/_index.md
  content/zh/docs/release/_index.md
  scripts/Makefile
  scripts/build.py
  scripts/build.sh
  scripts/builder/__init__.py
  scripts/builder/consts.py
  scripts/builder/drivers.py
  scripts/builder/hugo.py
  scripts/collect-input.py
  scripts/converter/__init__.py
  scripts/converter/helper.py
  scripts/converter/processor.py
  scripts/docker-push.sh
  scripts/function.sh
  scripts/local.sh
  scripts/offline-build.sh
  scripts/pandoc-doc-filter.py
  scripts/pandoc-table-filter.lua
  scripts/saas-build.py
  scripts/saas-dev.sh
  scripts/setup-upstream.sh
  scripts/utils/__init__.py
Labels: approved, do-not-merge/hold, size/XXL

#442 Automated cherry pick of #441: feat(misc): misc build scripts
  .gitignore
  Dockerfile
  Dockerfile-img
  Makefile
  Makefile.ee
  content/en/docs/changelog/_index.md
  content/en/docs/roadmap/_index.md
  content/zh/blog/_index.md
  content/zh/docs/140_apisdk/_index.md
  content/zh/docs/170_roadmap/_index.md
  content/zh/docs/changelog/_index.md
  content/zh/docs/release/_index.md
  scripts/Makefile
  scripts/build.py
  scripts/build.sh
  scripts/builder/__init__.py
  scripts/builder/consts.py
  scripts/builder/drivers.py
  scripts/builder/hugo.py
  scripts/collect-input.py
  scripts/converter/__init__.py
  scripts/converter/helper.py
  scripts/converter/processor.py
  scripts/docker-push.sh
  scripts/function.sh
  scripts/local.sh
  scripts/offline-build.sh
  scripts/pandoc-doc-filter.py
  scripts/pandoc-table-filter.lua
  scripts/saas-build.py
  scripts/saas-dev.sh
  scripts/setup-upstream.sh
  scripts/utils/__init__.py
Labels: size/XXL

#443 README_CN: update content meta header
  README_CN.md
Labels: approved, size/S

#444 Automated cherry pick of #443: README_CN: update content meta header
  README_CN.md
Labels: size/S

#445 feat: oem support
  config.toml
  content/zh/docs/010_quickstart/_index.md
  content/zh/docs/_index.md
  layouts/_default/baseof.html
  layouts/_default/content.html
  layouts/_default/list.html
  layouts/_default/list.rss.xml
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/docs/baseof.html
  layouts/docs/list.html
  layouts/docs/single.html
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/section-index.html
  layouts/partials/sidebar-tree.html
  layouts/partials/title.html
  layouts/shortcodes/oem_name.html
  layouts/swagger/baseof.html
  layouts/swagger/list.html
  layouts/swagger/single.html
Labels: approved, size/L

#446 Automated cherry pick of #445: feat: oem support
  config.toml
  content/zh/docs/010_quickstart/_index.md
  content/zh/docs/_index.md
  layouts/_default/baseof.html
  layouts/_default/content.html
  layouts/_default/list.html
  layouts/_default/list.rss.xml
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/docs/baseof.html
  layouts/docs/list.html
  layouts/docs/single.html
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/section-index.html
  layouts/partials/sidebar-tree.html
  layouts/partials/title.html
  layouts/shortcodes/oem_name.html
  layouts/swagger/baseof.html
  layouts/swagger/list.html
  layouts/swagger/single.html
Labels: approved, size/L
