Repository yunionio/docs, pull requests merged in 2021-11, with the labels that each got.

#557 fix: make perf test doc more concise, move test data to separate doc
  content/zh/docs/onpremise/vminstance/tutorial/customize.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/_index.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/perf-data.md
Labels: approved, size/XXL

#558 Automated cherry pick of #557: fix: make perf test doc more concise, move test data to separate doc
  content/zh/docs/onpremise/vminstance/tutorial/customize.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/_index.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/perf-data.md
Labels: approved, size/XXL

#559 fix: make perf test doc more concise, move test data to separate doc
  content/zh/docs/onpremise/vminstance/tutorial/customize.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/_index.md
Labels: size/M, approved

#560 Automated cherry pick of #559: fix: make perf test doc more concise, move test data to separate doc
  content/zh/docs/onpremise/vminstance/tutorial/customize.md
  content/zh/docs/onpremise/vminstance/tutorial/perf-test/_index.md
Labels: size/M, approved

#561 Create openstack 对接存储问题
  content/zh/docs/multicloud/cloudaccounts/openstack 对接存储问题
Labels: size/M

#564 feat(vminstance): server-change-disk-storage
  content/zh/docs/onpremise/vminstance/tutorial/change-disk-storge.md
Labels: size/L

#565 Automated cherry pick of #564: feat(vminstance): server-change-disk-storage
  content/zh/docs/onpremise/vminstance/tutorial/change-disk-storge.md
Labels: size/L

#573 fix: baremetal dhcp relay in simple mode
  content/zh/docs/onpremise/baremetal/faq/hardware-requirements.md
  content/zh/docs/onpremise/baremetal/tutorial/testcase.md
Labels: size/S

#574 Automated cherry pick of #573: fix: baremetal dhcp relay in simple mode
  content/zh/docs/onpremise/baremetal/faq/hardware-requirements.md
  content/zh/docs/onpremise/baremetal/tutorial/testcase.md
Labels: size/S

#575 feat: update docs to v3.8.4
  content/en/docs/changelog/release-3.8/3-8-4.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-4.md
  content/zh/docs/changelog/release-3.8/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/upgrade.md
Labels: size/XL

#570 release note of v3.8.4
  content/zh/docs/release/v3_8_4.md
Labels: size/M

#578 feat(change-disk-storage): add nfs proxy to ceph storage
  content/zh/docs/onpremise/vminstance/tutorial/change-disk-storge.md
Labels: size/S

#580 add nfs change-storage step
  content/zh/docs/onpremise/vminstance/tutorial/change-disk-storge.md
Labels: size/M

#581 Automated cherry pick of #580: add nfs change-storage step
  content/zh/docs/onpremise/vminstance/tutorial/change-disk-storge.md
Labels: size/M

#582 feat(3.8) 免密登录、云用户组、代理内容更新
  content/zh/docs/multicloud/cloudaccounts/images/addpermission.png
  content/zh/docs/multicloud/cloudaccounts/images/adduserpermission.png
  content/zh/docs/multicloud/cloudaccounts/images/azureaccountid.png
  content/zh/docs/multicloud/cloudaccounts/images/azuresamluser.png
  content/zh/docs/multicloud/cloudaccounts/images/azuresso.png
  content/zh/docs/multicloud/cloudaccounts/images/azuressologin1.png
  content/zh/docs/multicloud/cloudaccounts/images/azurexml.png
  content/zh/docs/multicloud/cloudaccounts/images/createazuresamluser.png
  content/zh/docs/multicloud/cloudaccounts/images/createexternalidenties.png
  content/zh/docs/multicloud/cloudaccounts/images/disablesamesite.png
  content/zh/docs/multicloud/cloudaccounts/images/externalidenties.png
  content/zh/docs/multicloud/cloudaccounts/images/newsaml.png
  content/zh/docs/multicloud/cloudaccounts/images/permission.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/azurecloudsso.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/cloudsso.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/globalproxy.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/modify.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/proxy.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/public_project.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/cloudgroup.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/modify.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/show.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/sync_status.md
  content/zh/docs/multicloud/cloudgroup/api/_index.md
  content/zh/docs/multicloud/cloudgroup/best_practice/_index.md
  content/zh/docs/multicloud/cloudgroup/faq/_index.md
  content/zh/docs/multicloud/cloudgroup/principle/_index.md
  content/zh/docs/multicloud/cloudgroup/troubleshooting/_index.md
  content/zh/docs/multicloud/cloudgroup/tutorial/cache.md
  content/zh/docs/multicloud/cloudgroup/tutorial/cloudpolicy.md
  content/zh/docs/multicloud/cloudgroup/tutorial/clouduser.md
  content/zh/docs/multicloud/cloudgroup/tutorial/create.md
  content/zh/docs/multicloud/cloudgroup/tutorial/delete.md
  content/zh/docs/multicloud/cloudgroup/tutorial/show.md
  content/zh/docs/multicloud/cloudgroup/tutorial/sync.md
Labels: size/XL

#583 Automated cherry pick of #582: feat(3.8) 免密登录、云用户组、代理内容更新
  content/zh/docs/multicloud/cloudaccounts/images/addpermission.png
  content/zh/docs/multicloud/cloudaccounts/images/adduserpermission.png
  content/zh/docs/multicloud/cloudaccounts/images/azureaccountid.png
  content/zh/docs/multicloud/cloudaccounts/images/azuresamluser.png
  content/zh/docs/multicloud/cloudaccounts/images/azuresso.png
  content/zh/docs/multicloud/cloudaccounts/images/azuressologin1.png
  content/zh/docs/multicloud/cloudaccounts/images/azurexml.png
  content/zh/docs/multicloud/cloudaccounts/images/createazuresamluser.png
  content/zh/docs/multicloud/cloudaccounts/images/createexternalidenties.png
  content/zh/docs/multicloud/cloudaccounts/images/disablesamesite.png
  content/zh/docs/multicloud/cloudaccounts/images/externalidenties.png
  content/zh/docs/multicloud/cloudaccounts/images/newsaml.png
  content/zh/docs/multicloud/cloudaccounts/images/permission.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/azurecloudsso.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/cloudsso.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudsso/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/globalproxy.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/modify.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/proxy/proxy.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/public_project.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/cloudgroup.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/modify.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/show.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/subaccount/sync_status.md
  content/zh/docs/multicloud/cloudgroup/api/_index.md
  content/zh/docs/multicloud/cloudgroup/best_practice/_index.md
  content/zh/docs/multicloud/cloudgroup/faq/_index.md
  content/zh/docs/multicloud/cloudgroup/principle/_index.md
  content/zh/docs/multicloud/cloudgroup/troubleshooting/_index.md
  content/zh/docs/multicloud/cloudgroup/tutorial/cache.md
  content/zh/docs/multicloud/cloudgroup/tutorial/cloudpolicy.md
  content/zh/docs/multicloud/cloudgroup/tutorial/clouduser.md
  content/zh/docs/multicloud/cloudgroup/tutorial/create.md
  content/zh/docs/multicloud/cloudgroup/tutorial/delete.md
  content/zh/docs/multicloud/cloudgroup/tutorial/show.md
  content/zh/docs/multicloud/cloudgroup/tutorial/sync.md
Labels: size/XL

#584 add ./config-ce-online.toml to fix contentDir config
  .gitignore
  config-ce-online.toml
  scripts/builder/hugo.py
Labels: size/S

#586 hugo dynamic generate config
  config-ce-online.toml
  scripts/builder/hugo.py
Labels: size/S

#587 Automated cherry pick of #586: hugo dynamic generate config
  config-ce-online.toml
  scripts/builder/hugo.py
Labels: size/S

#588 fix: add vm purge doc
  content/zh/docs/multicloud/cloudaccounts/faq/delete_failed.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/_index.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/purge.md
Labels: size/M

#589 Automated cherry pick of #588: fix: add vm purge doc
  content/zh/docs/multicloud/cloudaccounts/faq/delete_failed.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/_index.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/purge.md
Labels: size/M

#592 feat(3.8) 补充运维手册
  content/zh/docs/ops/_index.md
  content/zh/docs/ops/commonops.md
  content/zh/docs/ops/component.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/images/configmaperror.png
  content/zh/docs/ops/migrate.md
  content/zh/docs/ops/ocadm.md
  content/zh/docs/ops/poderror.md
Labels: size/XL

#593 Automated cherry pick of #592: feat(3.8) 补充运维手册
  content/zh/docs/ops/_index.md
  content/zh/docs/ops/commonops.md
  content/zh/docs/ops/component.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/images/configmaperror.png
  content/zh/docs/ops/migrate.md
  content/zh/docs/ops/ocadm.md
  content/zh/docs/ops/poderror.md
Labels: size/XL

#595 更新kubelet、kubectl和kubeadm的安装版本
  content/zh/docs/setup/controlplane.md
Labels: size/XS

#590 fix: add qcloud cam
  content/zh/docs/multicloud/_index.md
  content/zh/docs/multicloud/iam.md
Labels: size/M

#599 release auth and security docs for ce edition
  content/zh/docs/auth_security/_index.md
Labels: size/XS
