Repository yunionio/docs, pull requests merged in 2021-09, with the labels that each got.

#449 add(vm): faq
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/_index.md
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/create_failed.md
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/no_region.md
  content/zh/docs/070_multicloud/100_compute/vminstance/images/no_region.png
  content/zh/docs/070_multicloud/100_compute/vminstance/images/vm_log.png
  content/zh/docs/070_multicloud/cloudaccounts/faq/health_check.md
Labels: size/M

#450 Automated cherry pick of #449: add(vm): faq
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/_index.md
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/create_failed.md
  content/zh/docs/070_multicloud/100_compute/vminstance/faq/no_region.md
  content/zh/docs/070_multicloud/100_compute/vminstance/images/no_region.png
  content/zh/docs/070_multicloud/100_compute/vminstance/images/vm_log.png
  content/zh/docs/070_multicloud/cloudaccounts/faq/health_check.md
Labels: size/M

#453 fix(doc): vm faq update
  content/zh/docs/multicloud/compute/vminstance/faq/no_region.md
Labels: size/XS

#454 Automated cherry pick of #453: fix(doc): vm faq update
  content/zh/docs/multicloud/compute/vminstance/faq/no_region.md
Labels: size/XS

#458 update changelog 20210917
  content/en/docs/changelog/release-3.6/3-6-22.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-7.md
  content/en/docs/changelog/release-3.7/_index.md
  content/en/docs/changelog/release-3.8/3-8-0.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.6/3-6-22.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-7.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.8/3-8-0.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/XXL

#459 Automated cherry pick of #458: update changelog 20210917
  content/en/docs/changelog/release-3.6/3-6-22.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-7.md
  content/en/docs/changelog/release-3.7/_index.md
  content/en/docs/changelog/release-3.8/3-8-0.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.6/3-6-22.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-7.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.8/3-8-0.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/XXL

#460 release node for v3.7.7
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/release/v3_7_7.md
  content/zh/docs/setup/controlplane.md
Labels: size/M

#462 upgrade to v3.7.7
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#464 fix(release 3.7.7): date to 20210914
  content/zh/docs/release/v3_7_7.md
Labels: approved

#465 Update v3_7_7.md
  content/zh/docs/release/v3_7_7.md
Labels: size/XS

#469 Automated cherry pick of #465: Update v3_7_7.md
  content/zh/docs/release/v3_7_7.md
Labels: size/XS

#472 feat(baremetal): change netif
  content/zh/docs/onpremise/baremetal/tutorial/change_netif.md
Labels: size/M, approved

#473 Automated cherry pick of #472: feat(baremetal): change netif
  content/zh/docs/onpremise/baremetal/tutorial/change_netif.md
Labels: size/M, approved

#470 fix: describe ceph dev with release/3.8
  content/zh/docs/development/ceph.md
Labels: size/XS

#471 Automated cherry pick of #470: fix: describe ceph dev with release/3.8
  content/zh/docs/development/ceph.md
Labels: size/XS

#474 feature: add 1 blog post and 2 baremetal faq
  content/zh/blog/_posts/2021-09-25-calico-customized-node-firewall.md
  content/zh/docs/onpremise/baremetal/faq/bonding_shared_bmc_nic.md
  content/zh/docs/onpremise/baremetal/faq/link-aggregation-management.png
  content/zh/docs/onpremise/baremetal/faq/nic_persistent_naming.md
  content/zh/docs/onpremise/network/principle/baremetal.md
Labels: approved, size/L

#475 Automated cherry pick of #474: feature: add 1 blog post and 2 baremetal faq
  content/zh/blog/_posts/2021-09-25-calico-customized-node-firewall.md
  content/zh/docs/onpremise/baremetal/faq/bonding_shared_bmc_nic.md
  content/zh/docs/onpremise/baremetal/faq/link-aggregation-management.png
  content/zh/docs/onpremise/baremetal/faq/nic_persistent_naming.md
  content/zh/docs/onpremise/network/principle/baremetal.md
Labels: approved, size/L

#455 add perf test doc
  content/zh/docs/onpremise/vminstance/tutorial/perf-test.md
Labels: approved, size/L

#479 feature: docs on vlan and ldap
  content/zh/docs/auth_security/identity.md
  content/zh/docs/onpremise/network/principle/brtrunk.png
  content/zh/docs/onpremise/network/principle/host.md
  content/zh/docs/onpremise/network/principle/host_alias_vlan_nic.png
  content/zh/docs/onpremise/network/principle/vm_vlan_access.png
Labels: size/M

#480 Automated cherry pick of #479: feature: docs on vlan and ldap
  content/zh/docs/auth_security/identity.md
  content/zh/docs/onpremise/network/principle/brtrunk.png
  content/zh/docs/onpremise/network/principle/host.md
  content/zh/docs/onpremise/network/principle/host_alias_vlan_nic.png
  content/zh/docs/onpremise/network/principle/vm_vlan_access.png
Labels: size/M
