Repository yunionio/docs, pull requests merged in 2021-03, with the labels that each got.

#128 chore(changelog): update changelog
  content/zh/docs/changelog/release-3.4/3-4-13.md
  content/zh/docs/changelog/release-3.4/3-4-14.md
  content/zh/docs/changelog/release-3.4/3-4-15.md
  content/zh/docs/changelog/release-3.4/3-4-16.md
  content/zh/docs/changelog/release-3.4/_index.md
  content/zh/docs/changelog/release-3.6/3-6-0.md
  content/zh/docs/changelog/release-3.6/3-6-1.md
  content/zh/docs/changelog/release-3.6/3-6-2.md
  content/zh/docs/changelog/release-3.6/3-6-3.md
  content/zh/docs/changelog/release-3.6/3-6-4.md
  content/zh/docs/changelog/release-3.6/3-6-5.md
  content/zh/docs/changelog/release-3.6/3-6-6.md
  content/zh/docs/changelog/release-3.6/3-6-7.md
  content/zh/docs/changelog/release-3.6/3-6-8.md
  content/zh/docs/changelog/release-3.6/_index.md
Labels: size/XXL

#130 chore: release v3.6.9
  content/zh/docs/changelog/release-3.6/3-6-9.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#131 Automated cherry pick of #130: chore: release v3.6.9
  content/zh/docs/changelog/release-3.6/3-6-9.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#132 feat(upgrade): add page changelog link
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#133 Automated cherry pick of #132: feat(upgrade): add page changelog link
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#134 feat(setup): link to upgrade page
  content/zh/docs/setup/controlplane.md
Labels: size/S

#136 fix(upgrade): pip install requirements
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#137 Automated cherry pick of #136: fix(upgrade): pip install requirements
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#138 fix(upgrade): use yum install ansible and paramiko
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#141 feat(shortcodes): add tabs
  content/zh/docs/contribute/contrib.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/intro.md
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, size/L

#142 Automated cherry pick of #141: feat(shortcodes): add tabs
  content/zh/docs/contribute/contrib.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/intro.md
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, size/L

#143 Automated cherry pick of #141: feat(shortcodes): add tabs
  content/zh/docs/contribute/contrib.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/intro.md
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, size/L

#140 Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: approved, size/M

#144 Automated cherry pick of #140: Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/M

#145 Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#146 Automated cherry pick of #145: Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: approved, size/XS

#147 fix(host): add v3.6 node
  content/zh/docs/setup/host.md
Labels: approved, size/XS

#148 Automated cherry pick of #147: fix(host): add v3.6 node
  content/zh/docs/setup/host.md
Labels: approved, size/XS

#149 feat(dev): add dev docs
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/dev-env.md
  content/zh/docs/contribute/images/kubectl-edit-image.png
  content/zh/docs/contribute/images/kubectl-get-region-pod.png
Labels: approved, size/XL

#150 Automated cherry pick of #149: feat(dev): add dev docs
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/dev-env.md
  content/zh/docs/contribute/images/kubectl-edit-image.png
  content/zh/docs/contribute/images/kubectl-get-region-pod.png
Labels: approved, size/XL

#151 feat(contribute): add operator intro
  content/zh/docs/contribute/operator-intro.md
Labels: size/L

#152 Automated cherry pick of #151: feat(contribute): add operator intro
  content/zh/docs/contribute/operator-intro.md
Labels: size/L

#156 feat: change navbar style
  assets/scss/_variables_project.scss
  config.toml
  content/zh/_index.html
  layouts/partials/navbar.html
Labels: approved, size/M

#157 Automated cherry pick of #156: feat: change navbar style
  assets/scss/_variables_project.scss
  config.toml
  content/zh/_index.html
  layouts/partials/navbar.html
Labels: approved, size/M

#158 Automated cherry pick of #156: feat: change navbar style
  assets/scss/_variables_project.scss
  config.toml
  content/zh/_index.html
  layouts/partials/navbar.html
Labels: approved, size/M

#159 add roadmap
  content/zh/docs/roadmap/_index.md
Labels: approved, size/M

#160 Automated cherry pick of #159: add roadmap
  content/zh/docs/roadmap/_index.md
Labels: approved, size/M

#162 fix: internal content link
  content/zh/docs/contribute/framework.md
  content/zh/docs/howto/host/kvm.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: approved, size/M

#163 Automated cherry pick of #162: fix: internal content link
  content/zh/docs/contribute/framework.md
  content/zh/docs/howto/host/kvm.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: approved, size/M

#153 feat(docs): add arm64 deploy content
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/images/host-hybrid-list.png
  content/zh/docs/setup/images/image-hybrid-list.png
  content/zh/docs/setup/images/vm-hybrid-create.png
  content/zh/docs/setup/images/vm-hybrid-list.png
  content/zh/docs/setup/upgrade.md
Labels: size/L

#154 Automated cherry pick of #153: feat(docs): add arm64 deploy content
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/images/host-hybrid-list.png
  content/zh/docs/setup/images/image-hybrid-list.png
  content/zh/docs/setup/images/vm-hybrid-create.png
  content/zh/docs/setup/images/vm-hybrid-list.png
  content/zh/docs/setup/upgrade.md
Labels: size/L

#164 fix: internal links
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
Labels: size/XS

#166 update changelog
  content/zh/docs/changelog/release-3.6/3-6-10.md
  content/zh/docs/changelog/release-3.6/_index.md
Labels: approved, size/L

#167 Automated cherry pick of #166: update changelog
  content/zh/docs/changelog/release-3.6/3-6-10.md
  content/zh/docs/changelog/release-3.6/_index.md
Labels: approved, size/L
