Repository yunionio/docs, pull requests merged in 2021-05, with the labels that each got.

#182 update changelog
  content/zh/docs/changelog/release-3.6/3-6-15.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
Labels: approved, size/S

#183 Automated cherry pick of #182: update changelog
  content/zh/docs/changelog/release-3.6/3-6-15.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
Labels: size/S

#187 feat: release 3.7 docs
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/upgrade.md
  scripts/build.sh
Labels: approved

#189 feat: add v3.7 english translations
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/docs/quickstart/nodes.md
Labels: approved, size/L

#190 Automated cherry pick of #189: feat: add v3.7 english translations
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/docs/quickstart/nodes.md
Labels: size/L

#191 sync changelog for english version
  Makefile
  config.toml
  content/en/docs/changelog/release-3.3/3-3-0.md
  content/en/docs/changelog/release-3.3/3-3-1.md
  content/en/docs/changelog/release-3.3/3-3-3.md
  content/en/docs/changelog/release-3.3/3-3-4.md
  content/en/docs/changelog/release-3.3/3-3-5.md
  content/en/docs/changelog/release-3.3/3-3-6.md
  content/en/docs/changelog/release-3.3/3-3-7.md
  content/en/docs/changelog/release-3.3/3-3-8.md
  content/en/docs/changelog/release-3.3/_index.md
  content/en/docs/changelog/release-3.4/3-4-0.md
  content/en/docs/changelog/release-3.4/3-4-1.md
  content/en/docs/changelog/release-3.4/3-4-10.md
  content/en/docs/changelog/release-3.4/3-4-11.md
  content/en/docs/changelog/release-3.4/3-4-12.md
  content/en/docs/changelog/release-3.4/3-4-13.md
  content/en/docs/changelog/release-3.4/3-4-14.md
  content/en/docs/changelog/release-3.4/3-4-15.md
  content/en/docs/changelog/release-3.4/3-4-16.md
  content/en/docs/changelog/release-3.4/3-4-2.md
  content/en/docs/changelog/release-3.4/3-4-3.md
  content/en/docs/changelog/release-3.4/3-4-4.md
  content/en/docs/changelog/release-3.4/3-4-5.md
  content/en/docs/changelog/release-3.4/3-4-6.md
  content/en/docs/changelog/release-3.4/3-4-7.md
  content/en/docs/changelog/release-3.4/3-4-8.md
  content/en/docs/changelog/release-3.4/3-4-9.md
  content/en/docs/changelog/release-3.4/_index.md
  content/en/docs/changelog/release-3.6/3-6-0.md
  content/en/docs/changelog/release-3.6/3-6-1.md
  content/en/docs/changelog/release-3.6/3-6-10.md
  content/en/docs/changelog/release-3.6/3-6-11.md
  content/en/docs/changelog/release-3.6/3-6-12.md
  content/en/docs/changelog/release-3.6/3-6-13.md
  content/en/docs/changelog/release-3.6/3-6-14.md
  content/en/docs/changelog/release-3.6/3-6-15.md
  content/en/docs/changelog/release-3.6/3-6-2.md
  content/en/docs/changelog/release-3.6/3-6-3.md
  content/en/docs/changelog/release-3.6/3-6-4.md
  content/en/docs/changelog/release-3.6/3-6-5.md
  content/en/docs/changelog/release-3.6/3-6-6.md
  content/en/docs/changelog/release-3.6/3-6-7.md
  content/en/docs/changelog/release-3.6/3-6-8.md
  content/en/docs/changelog/release-3.6/3-6-9.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/_index.md
Labels: size/XXL

#192 Automated cherry pick of #191: sync changelog for english version
  Makefile
  config.toml
  content/en/docs/changelog/release-3.3/3-3-0.md
  content/en/docs/changelog/release-3.3/3-3-1.md
  content/en/docs/changelog/release-3.3/3-3-3.md
  content/en/docs/changelog/release-3.3/3-3-4.md
  content/en/docs/changelog/release-3.3/3-3-5.md
  content/en/docs/changelog/release-3.3/3-3-6.md
  content/en/docs/changelog/release-3.3/3-3-7.md
  content/en/docs/changelog/release-3.3/3-3-8.md
  content/en/docs/changelog/release-3.3/_index.md
  content/en/docs/changelog/release-3.4/3-4-0.md
  content/en/docs/changelog/release-3.4/3-4-1.md
  content/en/docs/changelog/release-3.4/3-4-10.md
  content/en/docs/changelog/release-3.4/3-4-11.md
  content/en/docs/changelog/release-3.4/3-4-12.md
  content/en/docs/changelog/release-3.4/3-4-13.md
  content/en/docs/changelog/release-3.4/3-4-14.md
  content/en/docs/changelog/release-3.4/3-4-15.md
  content/en/docs/changelog/release-3.4/3-4-16.md
  content/en/docs/changelog/release-3.4/3-4-2.md
  content/en/docs/changelog/release-3.4/3-4-3.md
  content/en/docs/changelog/release-3.4/3-4-4.md
  content/en/docs/changelog/release-3.4/3-4-5.md
  content/en/docs/changelog/release-3.4/3-4-6.md
  content/en/docs/changelog/release-3.4/3-4-7.md
  content/en/docs/changelog/release-3.4/3-4-8.md
  content/en/docs/changelog/release-3.4/3-4-9.md
  content/en/docs/changelog/release-3.4/_index.md
  content/en/docs/changelog/release-3.6/3-6-0.md
  content/en/docs/changelog/release-3.6/3-6-1.md
  content/en/docs/changelog/release-3.6/3-6-10.md
  content/en/docs/changelog/release-3.6/3-6-11.md
  content/en/docs/changelog/release-3.6/3-6-12.md
  content/en/docs/changelog/release-3.6/3-6-13.md
  content/en/docs/changelog/release-3.6/3-6-14.md
  content/en/docs/changelog/release-3.6/3-6-15.md
  content/en/docs/changelog/release-3.6/3-6-2.md
  content/en/docs/changelog/release-3.6/3-6-3.md
  content/en/docs/changelog/release-3.6/3-6-4.md
  content/en/docs/changelog/release-3.6/3-6-5.md
  content/en/docs/changelog/release-3.6/3-6-6.md
  content/en/docs/changelog/release-3.6/3-6-7.md
  content/en/docs/changelog/release-3.6/3-6-8.md
  content/en/docs/changelog/release-3.6/3-6-9.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/_index.md
Labels: size/XXL

#194 feat: add build workflows
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  Makefile
  README.md
  README_CN.md
  deploy
  deploy-to-cn
  package.json
  scripts/build.sh
  scripts/hash-files.sh
  scripts/setup.sh
Labels: approved, size/L

#195 Automated cherry pick of #194: feat: add build workflows
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  Makefile
  README.md
  README_CN.md
  deploy
  deploy-to-cn
  package.json
  scripts/build.sh
  scripts/hash-files.sh
  scripts/setup.sh
Labels: approved, size/L

#199 update changelog
  content/en/docs/changelog/release-3.6/3-6-16.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-1.md
  content/en/docs/changelog/release-3.7/_index.md
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/docs/changelog/release-3.6/3-6-16.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-1.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/upgrade.md
Labels: approved, size/L

#200 Automated cherry pick of #199: update changelog
  content/en/docs/changelog/release-3.6/3-6-16.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-1.md
  content/en/docs/changelog/release-3.7/_index.md
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/docs/changelog/release-3.6/3-6-16.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-1.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/upgrade.md
Labels: approved, size/L

#201 feat: i18n automatic language redirection
  layouts/alias.html
Labels: approved, size/M

#202 Automated cherry pick of #201: feat: i18n automatic language redirection
  layouts/alias.html
Labels: approved, size/M

#203 Automated cherry pick of #201: feat: i18n automatic language redirection
  layouts/alias.html
Labels: approved, size/M

#205 feat(docs) 切换到企业版后，把常见问题的命令放到上面切换操作中
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#206 Automated cherry pick of #205: feat(docs) 切换到企业版后，把常见问题的命令放到上面切换操作中
  content/zh/docs/setup/ce-ee-switch.md
Labels: approved, size/S

#207 Automated cherry pick of #205: feat(docs) 切换到企业版后，把常见问题的命令放到上面切换操作中
  content/zh/docs/setup/ce-ee-switch.md
Labels: approved, size/S

#210 Automated cherry pick of #209: feat(docs)ucloud的对接文档需要更新
  content/zh/docs/_index.md
  content/zh/docs/howto/images/ucloud_access_api_key_1.png
  content/zh/docs/howto/images/ucloud_api_key.png
  content/zh/docs/howto/images/ucloud_api_public_private_key.png
  content/zh/docs/howto/images/ucloudapi.png
  content/zh/docs/howto/images/ucloudapikeypair.png
  content/zh/docs/howto/images/ucloudapikeyshow.png
  content/zh/docs/howto/multicloud/cloudaccount.md
Labels: size/S

#209 feat(docs)ucloud的对接文档需要更新
  content/zh/docs/_index.md
  content/zh/docs/howto/images/ucloud_access_api_key_1.png
  content/zh/docs/howto/images/ucloud_api_key.png
  content/zh/docs/howto/images/ucloud_api_public_private_key.png
  content/zh/docs/howto/images/ucloudapi.png
  content/zh/docs/howto/images/ucloudapikeypair.png
  content/zh/docs/howto/images/ucloudapikeyshow.png
  content/zh/docs/howto/multicloud/cloudaccount.md
Labels: size/S

#211 Automated cherry pick of #209: feat(docs)ucloud的对接文档需要更新
  content/zh/docs/_index.md
  content/zh/docs/howto/images/ucloud_access_api_key_1.png
  content/zh/docs/howto/images/ucloud_api_key.png
  content/zh/docs/howto/images/ucloud_api_public_private_key.png
  content/zh/docs/howto/images/ucloudapi.png
  content/zh/docs/howto/images/ucloudapikeypair.png
  content/zh/docs/howto/images/ucloudapikeyshow.png
  content/zh/docs/howto/multicloud/cloudaccount.md
Labels: size/S
