Repository yunionio/docs, pull requests merged in 2021-12, with the labels that each got.

#605 feat(3.8)中间件模块
  content/zh/docs/multicloud/middlewave/_index.md
  content/zh/docs/multicloud/middlewave/elasticsearch/_index.md
  content/zh/docs/multicloud/middlewave/elasticsearch/delete.md
  content/zh/docs/multicloud/middlewave/elasticsearch/log.md
  content/zh/docs/multicloud/middlewave/elasticsearch/show.md
  content/zh/docs/multicloud/middlewave/elasticsearch/sync.md
  content/zh/docs/multicloud/middlewave/kafka/_index.md
  content/zh/docs/multicloud/middlewave/kafka/delete.md
  content/zh/docs/multicloud/middlewave/kafka/log.md
  content/zh/docs/multicloud/middlewave/kafka/show.md
  content/zh/docs/multicloud/middlewave/kafka/sync.md
Labels: size/L

#606 Automated cherry pick of #605: feat(3.8)中间件模块
  content/zh/docs/multicloud/middlewave/_index.md
  content/zh/docs/multicloud/middlewave/elasticsearch/_index.md
  content/zh/docs/multicloud/middlewave/elasticsearch/delete.md
  content/zh/docs/multicloud/middlewave/elasticsearch/log.md
  content/zh/docs/multicloud/middlewave/elasticsearch/show.md
  content/zh/docs/multicloud/middlewave/elasticsearch/sync.md
  content/zh/docs/multicloud/middlewave/kafka/_index.md
  content/zh/docs/multicloud/middlewave/kafka/delete.md
  content/zh/docs/multicloud/middlewave/kafka/log.md
  content/zh/docs/multicloud/middlewave/kafka/show.md
  content/zh/docs/multicloud/middlewave/kafka/sync.md
Labels: size/L

#611 feat: add codestruct-front
  content/zh/docs/development/codestruct.md
Labels: size/M

#612 Automated cherry pick of #611: feat: add codestruct-front
  content/zh/docs/development/codestruct.md
Labels: size/M

#613 feat(3.8)补充安装监控Agent等
  content/zh/docs/monitor_ops/monitor/tutorial/installagent.md
  content/zh/docs/ops/agent.md
  content/zh/docs/ops/clearimage.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/images/binlog.png
  content/zh/docs/ops/images/deletelogtable.png
  content/zh/docs/ops/images/getinfluxdb.png
  content/zh/docs/ops/images/image.png
  content/zh/docs/ops/images/imagecache.png
  content/zh/docs/ops/images/logtable.png
  content/zh/docs/ops/images/snapshot.png
  content/zh/docs/ops/log.md
Labels: size/L

#614 Automated cherry pick of #613: feat(3.8)补充安装监控Agent等
  content/zh/docs/monitor_ops/monitor/tutorial/installagent.md
  content/zh/docs/ops/agent.md
  content/zh/docs/ops/clearimage.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/images/binlog.png
  content/zh/docs/ops/images/deletelogtable.png
  content/zh/docs/ops/images/getinfluxdb.png
  content/zh/docs/ops/images/image.png
  content/zh/docs/ops/images/imagecache.png
  content/zh/docs/ops/images/logtable.png
  content/zh/docs/ops/images/snapshot.png
  content/zh/docs/ops/log.md
Labels: size/L

#618 fix: update k8s v1.15.8 to v1.15.12
  content/zh/docs/development/dev-env.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: size/S

#619 Automated cherry pick of #618: fix: update k8s v1.15.8 to v1.15.12
  content/zh/docs/development/dev-env.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: size/S

#622 feature: vpc vip
  content/zh/docs/onpremise/baremetal/tutorial/testcase.md
  content/zh/docs/onpremise/image/tutorial/create.md
  content/zh/docs/onpremise/network/tutorial/vpc/vpcvip.md
Labels: size/L

#623 Automated cherry pick of #622: feature: vpc vip
  content/zh/docs/onpremise/baremetal/tutorial/testcase.md
  content/zh/docs/onpremise/image/tutorial/create.md
  content/zh/docs/onpremise/network/tutorial/vpc/vpcvip.md
Labels: size/L
