Repository yunionio/docs, pull requests merged in 2021-06, with the labels that each got.

#217 fix: 改名为cloudpods的一些修改
  README.md
  README_CN.md
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/quickstart/_index.md
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/_index.html
  content/zh/docs/_index.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
Labels: approved, size/L

#218 Automated cherry pick of #217: fix: 改名为cloudpods的一些修改
  README.md
  README_CN.md
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/quickstart/_index.md
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/nodes.md
  content/zh/_index.html
  content/zh/docs/_index.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
Labels: approved

#216 add: multicloud desc
  content/zh/docs/howto/multicloud/iam.md
  content/zh/docs/howto/multicloud/multicloud.md
Labels: size/L

#214 feat(multicloud)添加移动云内容
  content/zh/docs/howto/images/ecloud.png
  content/zh/docs/howto/images/ecloudaccesskey.png
  content/zh/docs/howto/multicloud/cloudaccount.md
Labels: size/M

#215 Automated cherry pick of #214: feat(multicloud)添加移动云内容
  content/zh/docs/howto/images/ecloud.png
  content/zh/docs/howto/images/ecloudaccesskey.png
  content/zh/docs/howto/multicloud/cloudaccount.md
Labels: size/M

#223 Revert "Automated cherry pick of #220: fix: adjust logo and GA"
  content/en/_index.html
  content/en/docs/contact/_index.md
  content/zh/_index.html
  content/zh/docs/contact/_index.md
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo.png
  static/images/cloudpods_logo_white.png
  static/images/skillcode.png
Labels: approved, size/M

#226 fix: update logos
  static/images/cloudpods_logo.png
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_logo_white.png
  static/images/skillcode.png
Labels: approved, size/XS

#227 Automated cherry pick of #226: fix: update logos
  static/images/cloudpods_logo.png
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_logo_white.png
  static/images/skillcode.png
Labels: size/XS

#229 Automated cherry pick of #228: introduction of config SSL certificates
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/M

#230 Automated cherry pick of #228: introduction of config SSL certificates
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/M

#228 introduction of config SSL certificates
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/M

#231 remove opensource.yunion.cn reference
  content/zh/docs/setup/upgrade.md
Labels: approved, size/XS

#232 Automated cherry pick of #231: remove opensource.yunion.cn reference
  content/zh/docs/setup/upgrade.md
Labels: approved, size/XS

#234 add blog content
  config.toml
  content/zh/blog/_index.md
  content/zh/blog/_posts/2021-06-07-nvida-gpu-passthrough-record.md
Labels: size/L

#236 Github to GitHub
  config.toml
Labels: approved, size/XS

#237 Automated cherry pick of #236: Github to GitHub
  config.toml
Labels: approved, size/XS

#238 Automated cherry pick of #236: Github to GitHub
  config.toml
Labels: approved

#239 fix: replace qrcode
  static/images/skillcode.png
Labels: approved, size/XS

#240 Automated cherry pick of #239: fix: replace qrcode
  static/images/skillcode.png
Labels: approved, size/XS

#241 fix: change gpu blog title to an action
  content/zh/blog/_posts/2021-06-07-nvida-gpu-passthrough-record.md
  content/zh/docs/howto/baremetal/faq.md
Labels: approved, size/M

#242 Automated cherry pick of #241: fix: change gpu blog title to an action
  content/zh/blog/_posts/2021-06-07-nvida-gpu-passthrough-record.md
  content/zh/docs/howto/baremetal/faq.md
Labels: approved, size/M

#243 feature: add two blogs on 20210531 meetup
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction.md
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/01.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/02.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/03.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/04.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/05.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/06.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/07.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/08.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/09.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/10.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/11.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/12.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/13.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/14.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/15.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/16.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro.md
  content/zh/blog/_posts/2021-05-31-lb-application-intro/01.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/02.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/03-1.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/03.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/04.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/05.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/06.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/07.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/08.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/09.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/10.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/11.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/12.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/13.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/14.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/15.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/16.png
  content/zh/docs/howto/baremetal/faq.md
Labels: approved, size/L

#244 Automated cherry pick of #243: feature: add two blogs on 20210531 meetup
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction.md
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/01.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/02.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/03.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/04.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/05.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/06.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/07.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/08.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/09.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/10.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/11.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/12.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/13.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/14.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/15.png
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/16.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro.md
  content/zh/blog/_posts/2021-05-31-lb-application-intro/01.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/02.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/03-1.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/03.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/04.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/05.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/06.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/07.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/08.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/09.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/10.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/11.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/12.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/13.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/14.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/15.png
  content/zh/blog/_posts/2021-05-31-lb-application-intro/16.png
  content/zh/docs/howto/baremetal/faq.md
Labels: approved, size/L

#246 fix: change site URL to www.cloudpods.org
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/setup/intro.md
  content/zh/docs/setup/upgrade.md
  scripts/build.sh
Labels: approved, size/M

#247 Automated cherry pick of #246: fix: change site URL to www.cloudpods.org
  content/zh/docs/contribute/contrib.md
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/setup/intro.md
  content/zh/docs/setup/upgrade.md
  scripts/build.sh
Labels: approved, size/M

#248 fix: update logo and other misc
  config.toml
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_logo_white.png
Labels: approved, size/S

#249 Automated cherry pick of #248: fix: update logo and other misc
  config.toml
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_logo_white.png
Labels: approved, size/S

#250 update cname
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#251 Automated cherry pick of #250: update cname
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#245 fix: add cloudgroup
  content/zh/docs/howto/multicloud/cloudgroup/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/api/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/best_practice/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/changelog.md
  content/zh/docs/howto/multicloud/cloudgroup/faq/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/principle/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/troubleshooting/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/cloudpolicy.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/clouduser.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/create.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/delete.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/sync.md
Labels: size/L

#252 Automated cherry pick of #245: fix: add cloudgroup
  content/zh/docs/howto/multicloud/cloudgroup/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/api/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/best practice/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/changelog.md
  content/zh/docs/howto/multicloud/cloudgroup/faq/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/intro.md
  content/zh/docs/howto/multicloud/cloudgroup/principle/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/cloudpolicy.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/clouduser.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/create.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/delete.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/sync.md
  content/zh/docs/howto/multicloud/cloudgroup/troubleshooting/_index.md
Labels: approved, size/M

#253 refactor content structure
  content/zh/docs/howto/auth/_index.md
  content/zh/docs/howto/compute/_index.md
  content/zh/docs/howto/compute/baremetal/_index.md
  content/zh/docs/howto/compute/baremetal/faq.md
  content/zh/docs/howto/compute/baremetal/images/baremetal-arch.png
  content/zh/docs/howto/compute/baremetal/intro.md
  content/zh/docs/howto/compute/baremetal/operator.md
  content/zh/docs/howto/compute/host/_index.md
  content/zh/docs/howto/compute/host/esxi.md
  content/zh/docs/howto/compute/host/kvm.md
  content/zh/docs/howto/compute/image/_index.md
  content/zh/docs/howto/compute/image/create.md
  content/zh/docs/howto/compute/image/operation.md
  content/zh/docs/howto/compute/image/query.md
  content/zh/docs/howto/compute/image/upload.md
  content/zh/docs/howto/compute/pminstance/_index.md
  content/zh/docs/howto/compute/scheduler/_index.md
  content/zh/docs/howto/compute/vminstance/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/backup.md
  content/zh/docs/howto/compute/vminstance/tutorial/connect.md
  content/zh/docs/howto/compute/vminstance/tutorial/create.md
  content/zh/docs/howto/compute/vminstance/tutorial/gpu.md
  content/zh/docs/howto/compute/vminstance/tutorial/images/webssh.png
  content/zh/docs/howto/compute/vminstance/tutorial/import.md
  content/zh/docs/howto/compute/vminstance/tutorial/migrate.md
  content/zh/docs/howto/compute/vminstance/tutorial/others.md
  content/zh/docs/howto/network/lb/_index.md
  content/zh/docs/howto/server/create/aliyun.md
  content/zh/docs/howto/server/create/baremetal.md
  content/zh/docs/howto/server/create/esxi.md
  content/zh/docs/howto/server/create/kvm.md
  content/zh/docs/howto/server/migrate.md
  content/zh/docs/howto/storage/_index.md
Labels: approved, size/L

#254 Automated cherry pick of #253: refactor content structure
  content/zh/docs/howto/auth/_index.md
  content/zh/docs/howto/compute/_index.md
  content/zh/docs/howto/compute/baremetal/_index.md
  content/zh/docs/howto/compute/baremetal/faq.md
  content/zh/docs/howto/compute/baremetal/images/baremetal-arch.png
  content/zh/docs/howto/compute/baremetal/intro.md
  content/zh/docs/howto/compute/baremetal/operator.md
  content/zh/docs/howto/compute/host/_index.md
  content/zh/docs/howto/compute/host/esxi.md
  content/zh/docs/howto/compute/host/kvm.md
  content/zh/docs/howto/compute/image/_index.md
  content/zh/docs/howto/compute/image/create.md
  content/zh/docs/howto/compute/image/operation.md
  content/zh/docs/howto/compute/image/query.md
  content/zh/docs/howto/compute/image/upload.md
  content/zh/docs/howto/compute/pminstance/_index.md
  content/zh/docs/howto/compute/scheduler/_index.md
  content/zh/docs/howto/compute/vminstance/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/backup.md
  content/zh/docs/howto/compute/vminstance/tutorial/connect.md
  content/zh/docs/howto/compute/vminstance/tutorial/create.md
  content/zh/docs/howto/compute/vminstance/tutorial/gpu.md
  content/zh/docs/howto/compute/vminstance/tutorial/images/webssh.png
  content/zh/docs/howto/compute/vminstance/tutorial/import.md
  content/zh/docs/howto/compute/vminstance/tutorial/migrate.md
  content/zh/docs/howto/compute/vminstance/tutorial/others.md
  content/zh/docs/howto/network/lb/_index.md
  content/zh/docs/howto/server/create/aliyun.md
  content/zh/docs/howto/server/create/baremetal.md
  content/zh/docs/howto/server/create/esxi.md
  content/zh/docs/howto/server/create/kvm.md
  content/zh/docs/howto/server/migrate.md
  content/zh/docs/howto/storage/_index.md
Labels: approved, size/L

#255 refactor climc usage
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/howto/climc/usage.md
Labels: approved, size/XL

#257 fix(docs): update cloudgroup
  content/zh/docs/howto/multicloud/cloudgroup/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/best_practice/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/intro.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/create.md
  content/zh/docs/howto/multicloud/cloudgroup/quickguide/sync.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/_index.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/cloudpolicy.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/clouduser.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/create.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/delete.md
  content/zh/docs/howto/multicloud/cloudgroup/tutorial/sync.md
Labels: size/L

#260 baremetal and changelog renew
  content/en/docs/changelog/release-3.6/3-6-17.md
  content/en/docs/changelog/release-3.6/3-6-18.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-3.md
  content/en/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.6/3-6-17.md
  content/zh/docs/changelog/release-3.6/3-6-18.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-3.md
  content/zh/docs/changelog/release-3.7/_index.md
  content/zh/docs/howto/compute/baremetal/faq/_index.md
  content/zh/docs/howto/compute/baremetal/faq/manual_change_raid.md
  content/zh/docs/howto/compute/baremetal/principle.md
  content/zh/docs/howto/compute/baremetal/tutorial/_index.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_register.md
  content/zh/docs/howto/compute/baremetal/tutorial/operator.md
Labels: approved, size/L

#262 fix: add rds doc
  content/zh/docs/howto/db/_index.md
  content/zh/docs/howto/db/rds/_index.md
  content/zh/docs/howto/db/rds/images/rds_change_config.png
  content/zh/docs/howto/db/rds/images/rds_change_config_2.png
  content/zh/docs/howto/db/rds/images/rds_create.png
  content/zh/docs/howto/db/rds/images/rds_list.png
  content/zh/docs/howto/db/rds/images/rds_reboot.png
  content/zh/docs/howto/db/rds/images/rds_release.png
  content/zh/docs/howto/db/rds/images/rds_release2.png
  content/zh/docs/howto/db/rds/images/rds_secgroup.png
  content/zh/docs/howto/db/rds/images/rds_secgroup2.png
  content/zh/docs/howto/db/rds/images/rds_show.png
  content/zh/docs/howto/db/rds/images/rds_syncstatus.png
  content/zh/docs/howto/db/rds/tutorial/_index.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/_index.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/change_config.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/create.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/list.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/reboot.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/release.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/secgroup.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/show.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/syncstatus.md
Labels: size/XL

#263 Automated cherry pick of #262: fix: add rds doc
  content/zh/docs/howto/db/_index.md
  content/zh/docs/howto/db/rds/_index.md
  content/zh/docs/howto/db/rds/images/rds_change_config.png
  content/zh/docs/howto/db/rds/images/rds_change_config_2.png
  content/zh/docs/howto/db/rds/images/rds_create.png
  content/zh/docs/howto/db/rds/images/rds_list.png
  content/zh/docs/howto/db/rds/images/rds_reboot.png
  content/zh/docs/howto/db/rds/images/rds_release.png
  content/zh/docs/howto/db/rds/images/rds_release2.png
  content/zh/docs/howto/db/rds/images/rds_secgroup.png
  content/zh/docs/howto/db/rds/images/rds_secgroup2.png
  content/zh/docs/howto/db/rds/images/rds_show.png
  content/zh/docs/howto/db/rds/images/rds_syncstatus.png
  content/zh/docs/howto/db/rds/tutorial/_index.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/_index.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/change_config.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/create.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/list.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/reboot.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/release.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/secgroup.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/show.md
  content/zh/docs/howto/db/rds/tutorial/dbinstance/syncstatus.md
Labels: size/XL

#266 fix(blog): image not display
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/index.md
  content/zh/blog/_posts/2021-05-31-lb-application-intro/index.md
Labels: approved, size/M

#267 Automated cherry pick of #266: fix(blog): image not display
  content/zh/blog/_posts/2021-05-31-cloudpods-3.7-new-feature-introduction/index.md
  content/zh/blog/_posts/2021-05-31-lb-application-intro/index.md
Labels: approved, size/M

#268 feat(blog): add k8s kubelet pid limits content
  content/zh/blog/_posts/2021-06-25-k8s-kubelet-pid-limits.md
Labels: approved, lgtm, size/L

#269 Automated cherry pick of #268: feat(blog): add k8s kubelet pid limits content
  content/zh/blog/_posts/2021-06-25-k8s-kubelet-pid-limits.md
Labels: approved, size/L

#272 Update _index.md
  content/en/docs/roadmap/_index.md
Labels: approved, size/S

#270 Feature/yousong net
  content/zh/docs/howto/compute/vminstance/_index.md
  content/zh/docs/howto/network/_index.md
  content/zh/docs/howto/network/lb/_index.md
Labels: approved, size/M

#271 Automated cherry pick of #270: Feature/yousong net
  content/zh/docs/howto/compute/vminstance/_index.md
  content/zh/docs/howto/network/_index.md
  content/zh/docs/howto/network/lb/_index.md
Labels: approved, size/M

#273 feat(baremetal): add change ip address content
  content/zh/docs/howto/compute/baremetal/tutorial/change_ip_address.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_register.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_server.md
Labels: approved, size/L

#274 Automated cherry pick of #273: feat(baremetal): add change ip address content
  content/zh/docs/howto/compute/baremetal/tutorial/change_ip_address.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_register.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_server.md
Labels: approved, size/L

#276 fix: submodule
  .gitmodules
Labels: approved

#275 merge common files to release/3.7
  content/en/docs/roadmap/_index.md
Labels: approved, size/S

#281 feature: cherry pick common changes to all branches
  .gitignore
  scripts/cherry_pick_all.sh
Labels: approved, size/M

#282 feat(changelog): update to v3.7.5
  content/en/docs/changelog/release-3.7/3-7-4.md
  content/en/docs/changelog/release-3.7/3-7-5.md
  content/en/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.7/3-7-4.md
  content/zh/docs/changelog/release-3.7/3-7-5.md
  content/zh/docs/changelog/release-3.7/_index.md
Labels: approved, size/L

#283 Automated cherry pick of #282: feat(changelog): update to v3.7.5
  content/en/docs/changelog/release-3.7/3-7-4.md
  content/en/docs/changelog/release-3.7/3-7-5.md
  content/en/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.7/3-7-4.md
  content/zh/docs/changelog/release-3.7/3-7-5.md
  content/zh/docs/changelog/release-3.7/_index.md
Labels: approved, size/L
