Repository yunionio/docs, pull requests merged in 2021-07, with the labels that each got.

#286 fix(dev): update dev related content
  content/en/docs/contribute/contrib.md
  content/zh/docs/contribute/dev-env.md
Labels: approved, size/M

#287 Automated cherry pick of #286: fix(dev): update dev related content
  content/en/docs/contribute/contrib.md
  content/zh/docs/contribute/dev-env.md
Labels: approved

#288 feat(vminstance): document of how to change disk driver
  content/zh/docs/howto/compute/vminstance/tutorial/change_disk_driver.md
Labels: approved, size/L

#284 fix(docs): update swagger api
  content/en/docs/swagger/swagger_cloudevent.yaml
  content/en/docs/swagger/swagger_cloudid.yaml
  content/en/docs/swagger/swagger_compute.yaml
  content/en/docs/swagger/swagger_identity.yaml
  content/en/docs/swagger/swagger_image.yaml
  content/en/docs/swagger/swagger_monitor.yaml
  content/en/docs/swagger/swagger_notify.yaml
  content/en/docs/swagger/swagger_yunionconf.yaml
  content/zh/docs/swagger/swagger_cloudevent.yaml
  content/zh/docs/swagger/swagger_cloudid.yaml
  content/zh/docs/swagger/swagger_compute.yaml
  content/zh/docs/swagger/swagger_identity.yaml
  content/zh/docs/swagger/swagger_image.yaml
  content/zh/docs/swagger/swagger_monitor.yaml
  content/zh/docs/swagger/swagger_notify.yaml
  content/zh/docs/swagger/swagger_yunionconf.yaml
Labels: size/XXL

#285 Automated cherry pick of #284: fix(docs): update swagger api
  content/en/docs/swagger/swagger_cloudevent.yaml
  content/en/docs/swagger/swagger_cloudid.yaml
  content/en/docs/swagger/swagger_compute.yaml
  content/en/docs/swagger/swagger_identity.yaml
  content/en/docs/swagger/swagger_image.yaml
  content/en/docs/swagger/swagger_monitor.yaml
  content/en/docs/swagger/swagger_notify.yaml
  content/en/docs/swagger/swagger_yunionconf.yaml
  content/zh/docs/swagger/swagger_cloudevent.yaml
  content/zh/docs/swagger/swagger_cloudid.yaml
  content/zh/docs/swagger/swagger_compute.yaml
  content/zh/docs/swagger/swagger_identity.yaml
  content/zh/docs/swagger/swagger_image.yaml
  content/zh/docs/swagger/swagger_monitor.yaml
  content/zh/docs/swagger/swagger_notify.yaml
  content/zh/docs/swagger/swagger_yunionconf.yaml
Labels: size/XXL

#291 fix: update contact qr code
  content/en/docs/contact/_index.md
  content/en/docs/quickstart/allinone.md
  content/zh/docs/contact/_index.md
  content/zh/docs/quickstart/allinone.md
  static/images/contact_me_qr_20210701.png
Labels: approved, size/M

#292 Merge common files to release/3.2
  content/en/docs/contact/_index.md
  content/en/docs/contribute/contrib.md
  content/zh/docs/contact/_index.md
  content/zh/docs/contribute/dev-env.md
Labels: approved, size/M

#293 Merge common files to release/3.3
  content/en/docs/contact/_index.md
  content/en/docs/contribute/contrib.md
  content/zh/docs/contact/_index.md
  content/zh/docs/contribute/dev-env.md
Labels: approved, size/M

#295 Merge common files to release/3.6
  content/en/docs/contact/_index.md
  content/en/docs/contribute/contrib.md
  content/zh/docs/contact/_index.md
  content/zh/docs/contribute/dev-env.md
Labels: approved, size/M

#296 Merge common files to release/3.7
  content/en/docs/contact/_index.md
  content/zh/docs/contact/_index.md
  static/images/opensource_banner.svg
  static/images/opensource_banner_en.svg
Labels: approved, size/L

#297 Automated cherry pick of #291: fix: update contact qr code
  content/en/docs/quickstart/allinone.md
  content/zh/docs/quickstart/allinone.md
  static/images/contact_me_qr_20210701.png
Labels: size/S

#299 feat(3.7)将云联壹云改成Cloudpods&补充界面截图（zh）
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/contribute/services.md
  content/zh/docs/howto/_index.md
  content/zh/docs/howto/climc/usage.md
  content/zh/docs/howto/compute/host/_index.md
  content/zh/docs/howto/compute/host/kvm.md
  content/zh/docs/howto/compute/image/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/create.md
  content/zh/docs/howto/compute/vminstance/tutorial/import.md
  content/zh/docs/howto/container/_index.md
  content/zh/docs/howto/container/pre_env.md
  content/zh/docs/howto/multicloud/cloudaccount.md
  content/zh/docs/howto/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/howto/multicloud/cloudaccounts/tutorial/delete.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/upgrade.md
  content/zh/docs/ui/_index.md
  content/zh/docs/ui/baremetal.md
  content/zh/docs/ui/images/accountlist.png
  content/zh/docs/ui/images/addphysicalmachine.png
  content/zh/docs/ui/images/baremetalnetwork.png
  content/zh/docs/ui/images/cloudcreate.png
  content/zh/docs/ui/images/cloudselect.png
  content/zh/docs/ui/images/cloudshell.png
  content/zh/docs/ui/images/createbaremetal.png
  content/zh/docs/ui/images/createkvmvm1.png
  content/zh/docs/ui/images/createkvmvm2.png
  content/zh/docs/ui/images/createpublicvm1.png
  content/zh/docs/ui/images/createpublicvm2.png
  content/zh/docs/ui/images/dashboard.png
  content/zh/docs/ui/images/diskraid.png
  content/zh/docs/ui/images/fdisk.png
  content/zh/docs/ui/images/feature.png
  content/zh/docs/ui/images/hostlist.png
  content/zh/docs/ui/images/kvmvmlist.png
  content/zh/docs/ui/images/login.png
  content/zh/docs/ui/images/physicalmachinelist.png
  content/zh/docs/ui/images/publicvmlist.png
  content/zh/docs/ui/kvm.md
  content/zh/docs/ui/login.md
  content/zh/docs/ui/multicloud.md
Labels: size/L

#300 Automated cherry pick of #299: feat(3.7)将云联壹云改成Cloudpods
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/contribute/services.md
  content/zh/docs/howto/_index.md
  content/zh/docs/howto/climc/usage.md
  content/zh/docs/howto/compute/host/_index.md
  content/zh/docs/howto/compute/host/kvm.md
  content/zh/docs/howto/compute/image/_index.md
  content/zh/docs/howto/compute/vminstance/tutorial/create.md
  content/zh/docs/howto/compute/vminstance/tutorial/import.md
  content/zh/docs/howto/container/_index.md
  content/zh/docs/howto/container/pre_env.md
  content/zh/docs/howto/multicloud/cloudaccount.md
  content/zh/docs/howto/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/howto/multicloud/cloudaccounts/tutorial/delete.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/upgrade.md
Labels: size/L

#301 Automated cherry pick of #299: feat(3.7)将云联壹云改成Cloudpods
  content/zh/docs/ui/_index.md
  content/zh/docs/ui/baremetal.md
  content/zh/docs/ui/images/accountlist.png
  content/zh/docs/ui/images/addphysicalmachine.png
  content/zh/docs/ui/images/baremetalnetwork.png
  content/zh/docs/ui/images/cloudcreate.png
  content/zh/docs/ui/images/cloudselect.png
  content/zh/docs/ui/images/cloudshell.png
  content/zh/docs/ui/images/createbaremetal.png
  content/zh/docs/ui/images/createkvmvm1.png
  content/zh/docs/ui/images/createkvmvm2.png
  content/zh/docs/ui/images/createpublicvm1.png
  content/zh/docs/ui/images/createpublicvm2.png
  content/zh/docs/ui/images/dashboard.png
  content/zh/docs/ui/images/diskraid.png
  content/zh/docs/ui/images/fdisk.png
  content/zh/docs/ui/images/feature.png
  content/zh/docs/ui/images/hostlist.png
  content/zh/docs/ui/images/kvmvmlist.png
  content/zh/docs/ui/images/login.png
  content/zh/docs/ui/images/physicalmachinelist.png
  content/zh/docs/ui/images/publicvmlist.png
  content/zh/docs/ui/kvm.md
  content/zh/docs/ui/login.md
  content/zh/docs/ui/multicloud.md
Labels: approved, size/L

#302 fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: approved, size/XS

#307 Automated cherry pick of #302: fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: size/XS

#306 Automated cherry pick of #302: fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: size/XS

#305 Automated cherry pick of #302: fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: size/XS

#304 Automated cherry pick of #302: fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: approved, size/XS

#303 Automated cherry pick of #302: fix(en): change title Documentation to Cloudpods
  OWNERS
  config.toml
Labels: approved, size/XS

#309 Automated cherry pick of #308: fix: logo not match with latest branch
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_white.png
Labels: approved, lgtm, size/S

#310 Automated cherry pick of #308: fix: logo not match with latest branch
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_white.png
Labels: approved, lgtm, size/S

#311 Automated cherry pick of #308: fix: logo not match with latest branch
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_white.png
Labels: approved, lgtm, size/S

#308 fix: logo not match with latest branch
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar.html
  static/images/cloudpods_logo_white.png
Labels: approved, lgtm, size/S

#312 fix(layouts): update previous version layouts
  layouts/partials/navbar.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: approved, size/M

#314 update changelog
  content/en/docs/changelog/release-3.6/3-6-19.md
  content/en/docs/changelog/release-3.6/_index.md
  content/en/docs/changelog/release-3.7/3-7-0.md
  content/en/docs/changelog/release-3.7/3-7-5.md
  content/en/docs/changelog/release-3.7/_index.md
  content/zh/docs/changelog/release-3.6/3-6-19.md
  content/zh/docs/changelog/release-3.6/_index.md
  content/zh/docs/changelog/release-3.7/3-7-0.md
  content/zh/docs/changelog/release-3.7/3-7-5.md
  content/zh/docs/changelog/release-3.7/_index.md
Labels: size/L

#316 fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: approved, size/XS

#317 Automated cherry pick of #316: fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: size/XS

#318 Automated cherry pick of #316: fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: size/XS

#319 Automated cherry pick of #316: fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: size/XS

#320 Automated cherry pick of #316: fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: size/XS

#321 Automated cherry pick of #316: fix(build.sh): title to Cloudpods
  scripts/build.sh
Labels: size/XS

#322 fix title for version before v3.7
  config.toml
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/contribute/services.md
  content/zh/docs/howto/_index.md
  content/zh/docs/howto/climc/_index.md
  content/zh/docs/howto/container/_index.md
  content/zh/docs/howto/container/pre_env.md
  content/zh/docs/howto/host/_index.md
  content/zh/docs/howto/host/kvm.md
  content/zh/docs/howto/image/_index.md
  content/zh/docs/howto/multicloud/cloudaccount.md
  content/zh/docs/howto/server/_index.md
  content/zh/docs/howto/server/create/_index.md
  content/zh/docs/howto/server/create/kvm.md
  content/zh/docs/howto/server/gpu.md
  content/zh/docs/howto/server/import.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/intro.md
  content/zh/docs/setup/upgrade.md
Labels: size/L

#324 fix title for v3.3
  config.toml
  content/zh/docs/contribute/framework.md
  content/zh/docs/contribute/operator-intro.md
  content/zh/docs/contribute/services.md
Labels: approved, size/S

#326 fix: improve cover page
  Makefile
  README.md
  README_CN.md
  assets/scss/_variables_project.scss
  config.toml
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  scripts/build.sh
  scripts/cherry_pick_all.sh
  static/images/cloudpods_screen.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
Labels: approved, size/XL

#327 Automated cherry pick of #326: fix: improve cover page
  Makefile
  README.md
  README_CN.md
  assets/scss/_variables_project.scss
  config.toml
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  scripts/build.sh
  static/images/cloudpods_screen.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
Labels: approved, size/XL

#334 fix: cherry_pick_all not sync config.toml
  scripts/cherry_pick_all.sh
Labels: approved

#335 Merge common files to release/3.2
  assets/js/offline-search.js
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/alias.html
  layouts/partials/breadcrumb.html
  layouts/partials/community_links.html
  layouts/partials/disqus-comment.html
  layouts/partials/favicons.html
  layouts/partials/featured-image.html
  layouts/partials/feedback.html
  layouts/partials/footer.html
  layouts/partials/head-css.html
  layouts/partials/navbar-lang-selector.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-lastmod.html
  layouts/partials/page-meta-links.html
  layouts/partials/pager.html
  layouts/partials/scripts.html
  layouts/partials/search-input.html
  layouts/partials/section-index.html
  layouts/partials/sidebar-tree.html
  layouts/partials/sidebar.html
  layouts/partials/toc.html
  layouts/shortcodes/alert.html
  layouts/shortcodes/blocks/cover.html
  layouts/shortcodes/blocks/feature.html
  layouts/shortcodes/blocks/lead.html
  layouts/shortcodes/blocks/link-down.html
  layouts/shortcodes/blocks/section.html
  layouts/shortcodes/imgproc.html
  layouts/shortcodes/pageinfo.html
  layouts/shortcodes/readfile.md
  layouts/shortcodes/swaggerui.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_screen.png
  static/images/contact_me_qr_20210701.png
  static/images/provider/bonc.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
  static/images/skillcode.png
Labels: approved, size/XXL

#336 Merge common files to release/3.3
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/alias.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_screen.png
  static/images/contact_me_qr_20210701.png
  static/images/provider/bonc.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
  static/images/skillcode.png
Labels: approved, size/XL

#337 Merge common files to release/3.4
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/alias.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_screen.png
  static/images/contact_me_qr_20210701.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
  static/images/skillcode.png
Labels: approved, size/XL

#338 Merge common files to release/3.6
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/shortcodes/blocks/cover.html
  static/images/cloudpods_logo_green.png
  static/images/cloudpods_screen.png
  static/images/contact_me_qr_20210701.png
  static/images/provider/cmecloud.svg
  static/images/provider/ctyun.svg
  static/images/provider/google.svg
  static/images/provider/jdcloud.svg
  static/images/skillcode.png
Labels: approved, size/XL

#339 Merge common files to release/3.7
  static/images/opensource_banner.svg
  static/images/opensource_banner_en.svg
Labels: approved, size/L

#340 Hotfix/qj minor changes 20210705
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: approved, size/S

#341 Automated cherry pick of #340: Added Untitled Diagram.drawio
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: size/S

#342 Merge common files to release/3.2
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: approved, size/S

#343 Merge common files to release/3.3
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: approved, size/S

#344 Merge common files to release/3.4
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: size/S

#345 Merge common files to release/3.6
  assets/scss/_variables_project.scss
  content/en/_index.html
Labels: approved, size/S

#346 fix: update config.toml at release/3.2
  config.toml
Labels: approved, size/S

#347 fix: update config.toml at release/3.3
  config.toml
Labels: approved, size/S

#348 fix: update config.toml at release/3.4
  config.toml
Labels: approved, size/S

#349 fix: update config.toml on release/3.6
  config.toml
Labels: approved, size/M

#350 fix: minor fixes 20200705-1
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: approved

#351 Merge common files to release/3.2
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#352 Merge common files to release/3.3
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#353 Merge common files to release/3.4
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#354 Merge common files to release/3.6
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#355 Merge common files to release/3.7
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#356 fix: add account health check doc
  content/zh/docs/howto/multicloud/cloudaccounts/faq/_index.md
  content/zh/docs/howto/multicloud/cloudaccounts/faq/health_check.md
Labels: size/M

#357 Automated cherry pick of #356: fix: add account health check doc
  content/zh/docs/howto/multicloud/cloudaccounts/faq/_index.md
  content/zh/docs/howto/multicloud/cloudaccounts/faq/health_check.md
Labels: size/M

#363 Automated cherry pick of #358: fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#362 Automated cherry pick of #358: fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#361 Automated cherry pick of #358: fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#360 Automated cherry pick of #358: fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#359 Automated cherry pick of #358: fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#358 fix: add API link
  config.toml
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#369 Automated cherry pick of #364: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#368 Automated cherry pick of #364: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#367 Automated cherry pick of #364: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#366 Automated cherry pick of #364: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#365 Automated cherry pick of #364: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#364 fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/M

#375 Automated cherry pick of #370: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#374 Automated cherry pick of #370: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#373 Automated cherry pick of #370: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#372 Automated cherry pick of #370: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#371 Automated cherry pick of #370: fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#370 fix: cover page add features of cloud native and climc
  content/en/_index.html
  content/zh/_index.html
Labels: approved, size/S

#378 fix(baremetal): redirect create_register to EE doc
  content/zh/docs/howto/compute/baremetal/tutorial/create_register.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_register_redirect.md
Labels: approved, size/M

#379 Automated cherry pick of #378: fix(baremetal): redirect create_register to EE doc
  content/zh/docs/howto/compute/baremetal/tutorial/create_register.md
  content/zh/docs/howto/compute/baremetal/tutorial/create_register_redirect.md
Labels: approved, size/M

#376 fix: add new resource sync doc
  content/zh/docs/contribute/resource_sync/_index.md
  content/zh/docs/contribute/resource_sync/new_resource.md
Labels: size/XXL

#380 fix(ssl): restart traefik pod
  content/zh/docs/setup/config-ssl-certs.md
Labels: approved, size/XS

#382 Automated cherry pick of #380: fix(ssl): restart traefik pod
  content/zh/docs/setup/config-ssl-certs.md
Labels: approved

#383 add: ceph rbd doc
  content/zh/docs/contribute/ceph.md
Labels: size/L

#384 Automated cherry pick of #383: add: ceph rbd doc
  content/zh/docs/contribute/ceph.md
Labels: size/L

#391 update deploy-to-cn scripts
  deploy-to-cn
Labels: approved

#385 feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#387 Automated cherry pick of #385: feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#388 Automated cherry pick of #385: feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#389 Automated cherry pick of #385: feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#390 Automated cherry pick of #385: feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#386 Automated cherry pick of #385: feature: add more cloudpods users, add two blogs
  content/en/_index.html
  content/zh/_index.html
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/index.md
  content/zh/blog/_posts/2019-06-13-unified-iaas-for-future/unified_iaas.jpg
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/goprofile.png
  content/zh/blog/_posts/2021-07-01-keystone-slow-password-auth/index.md
  static/images/provider/bitdeer.svg
  static/images/provider/huolala.svg
  static/images/provider/jiuzhouzhengquan.svg
  static/images/provider/lixiang.svg
  static/images/provider/lvmeng.svg
Labels: approved, size/XL

#392 feat(action): push site to AWS S3
  .github/workflows/release.yml
Labels: approved, size/S

#393 Automated cherry pick of #392: feat(action): push site to AWS S3
  .github/workflows/release.yml
Labels: approved, size/S

#399 Automated cherry pick of #394: feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: approved, size/L

#398 Automated cherry pick of #394: feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: approved, size/L

#397 Automated cherry pick of #394: feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: size/L

#396 Automated cherry pick of #394: feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: approved, size/L

#395 Automated cherry pick of #394: feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: approved, size/L

#394 feature: add ocfs2 blog
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/index.md
  content/zh/blog/_posts/2021-07-02-ocfs2-as-san-filesystem/ocfs2-create.png
Labels: approved, size/L

#402 fix: broken links
  content/zh/docs/070_multicloud/140_db/rds/tutorial/dbinstance/create.md
  content/zh/docs/070_multicloud/cloudaccounts/tutorial/aksk_grant.md
Labels: size/XS

#403 Automated cherry pick of #402: fix: broken links
  content/zh/docs/070_multicloud/140_db/rds/tutorial/dbinstance/create.md
  content/zh/docs/070_multicloud/cloudaccounts/tutorial/aksk_grant.md
Labels: size/XS

#404 fix: add recommended two mysql parameters
  content/zh/docs/020_setup/controlplane.md
Labels: approved, size/XS

#405 Automated cherry pick of #404: fix: add recommended two mysql parameters
  content/zh/docs/020_setup/controlplane.md
Labels: approved, size/XS

#406 Automated cherry pick of #404: fix: add recommended two mysql parameters
  content/zh/docs/setup/controlplane.md
Labels: approved, size/XS

#407 Automated cherry pick of #404: fix: add recommended two mysql parameters
  content/zh/docs/setup/controlplane.md
Labels: approved, size/XS

#408 fix: minor updates 20210729
  content/zh/docs/070_multicloud/02_iam.md
  content/zh/docs/070_multicloud/090_region/_index.md
  content/zh/docs/070_multicloud/100_compute/_index.md
  content/zh/docs/070_multicloud/110_objectstorage/_index.md
  content/zh/docs/120_misc/090_log-purge.md
Labels: size/M

#409 Automated cherry pick of #408: fix: minor updates 20210729
  content/zh/docs/070_multicloud/02_iam.md
  content/zh/docs/070_multicloud/090_region/_index.md
  content/zh/docs/070_multicloud/100_compute/_index.md
  content/zh/docs/070_multicloud/110_objectstorage/_index.md
  content/zh/docs/120_misc/090_log-purge.md
Labels: size/M
