Repository yunionio/docs, pull requests merged in 2022-01, with the labels that each got.

#626 fix: add VPC mtu
  content/zh/docs/onpremise/network/tutorial/vpc/mtu.md
Labels: size/L

#627 Automated cherry pick of #626: fix: add VPC mtu
  content/zh/docs/onpremise/network/tutorial/vpc/mtu.md
Labels: size/L

#632 feat: update deployment docs use ocboot
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: size/L

#633 Automated cherry pick of #632: feat: update deployment docs use ocboot
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/minikube.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host.md
Labels: size/L

#636 fix: remove host howto
  content/zh/docs/development/devtools.md
  content/zh/docs/onpremise/network/tutorial/configuration.md
  content/zh/docs/setup/removehost.md
Labels: size/L

#637 Automated cherry pick of #636: fix: remove host howto
  content/zh/docs/development/devtools.md
  content/zh/docs/onpremise/network/tutorial/configuration.md
  content/zh/docs/setup/removehost.md
Labels: size/L

#638 feat(3.8)添加平台备份恢复内容
  content/zh/docs/monitor_ops/monitor/principle/_index.md
  content/zh/docs/monitor_ops/monitor/principle/monitoragent.md
  content/zh/docs/onpremise/network/tutorial/default/viewvpc.md
  content/zh/docs/onpremise/network/tutorial/default/viewwire.md
  content/zh/docs/onpremise/network/tutorial/vpc/viewvpc.md
  content/zh/docs/setup/backup.md
Labels: size/L

#639 Automated cherry pick of #638: feat(3.8)添加平台备份恢复内容
  content/zh/docs/monitor_ops/monitor/principle/_index.md
  content/zh/docs/monitor_ops/monitor/principle/monitoragent.md
  content/zh/docs/onpremise/network/tutorial/default/viewvpc.md
  content/zh/docs/onpremise/network/tutorial/default/viewwire.md
  content/zh/docs/onpremise/network/tutorial/vpc/viewvpc.md
  content/zh/docs/setup/backup.md
Labels: size/L

#640 feat(changelog): release 3.8.6
  content/en/docs/changelog/release-3.8/3-8-6.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-6.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/L

#641 Automated cherry pick of #640: feat(changelog): release 3.8.6
  content/en/docs/changelog/release-3.8/3-8-6.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-6.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/L

#642 feat: deploy on k8s
  content/zh/docs/quickstart/k8s.md
Labels: size/L

#643 Automated cherry pick of #642: feat: deploy on k8s
  content/zh/docs/quickstart/k8s.md
Labels: size/L

#646 feat: v3.8.6 release note
  content/zh/docs/release/v3_8_6.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#650 Multi zone setup
  content/zh/docs/setup/host.md
  content/zh/docs/setup/multi-zone.md
Labels: size/L

#651 Automated cherry pick of #650: feat(setup): multi zone
  content/zh/docs/setup/host.md
  content/zh/docs/setup/multi-zone.md
Labels: size/L

#648 feat(3.8) usb透传补充web操作
  content/zh/docs/onpremise/vminstance/tutorial/gpu.md
  content/zh/docs/onpremise/vminstance/tutorial/usb-passthrough.md
Labels: size/M

#652 Automated cherry pick of #648: feat(3.8) usb透传补充web操作
  content/zh/docs/onpremise/vminstance/tutorial/gpu.md
  content/zh/docs/onpremise/vminstance/tutorial/usb-passthrough.md
Labels: size/M

#649 feat(3.9)VPC对等连接&VPC互联&路由表
  content/zh/docs/multicloud/network/routetable/_index.md
  content/zh/docs/multicloud/network/routetable/faq/_index.md
  content/zh/docs/multicloud/network/routetable/principle/_index.md
  content/zh/docs/multicloud/network/routetable/tutorial/_index.md
  content/zh/docs/multicloud/network/routetable/tutorial/ipsubnet/_index.md
  content/zh/docs/multicloud/network/routetable/tutorial/route/_index.md
  content/zh/docs/multicloud/network/routetable/tutorial/route/delete.md
  content/zh/docs/multicloud/network/routetable/tutorial/routetable/_index.md
  content/zh/docs/multicloud/network/routetable/tutorial/routetable/log.md
  content/zh/docs/multicloud/network/routetable/tutorial/routetable/show.md
  content/zh/docs/multicloud/network/routetable/tutorial/routetable/sync.md
  content/zh/docs/multicloud/network/vpcnetwork/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/faq/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/principle/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/route/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/route/enable.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpc/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpc/create.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpc/delete.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpcnetwork/_index.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpcnetwork/delete.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpcnetwork/log.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpcnetwork/show.md
  content/zh/docs/multicloud/network/vpcnetwork/tutorial/vpcnetwork/sync.md
  content/zh/docs/multicloud/network/vpcpeer/_index.md
  content/zh/docs/multicloud/network/vpcpeer/faq/_index.md
  content/zh/docs/multicloud/network/vpcpeer/principle/_index.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/_index.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/route/_index.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/vpcpeer/_index.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/vpcpeer/delete.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/vpcpeer/log.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/vpcpeer/show.md
  content/zh/docs/multicloud/network/vpcpeer/tutorial/vpcpeer/sync.md
Labels: size/L

#657 docs(docs): 加载 nf_conntrack 模块；语法 typo fix；
  content/zh/docs/setup/controlplane.md
Labels: size/S

#658 Automated cherry pick of #657: docs(docs): 加载 nf_conntrack 模块；语法 typo fix；
  content/zh/docs/setup/controlplane.md
Labels: size/S

#655 fix: mtu setting for eipgw
  content/zh/docs/onpremise/network/tutorial/vpc/mtu.md
Labels: size/XS

#656 Automated cherry pick of #655: fix: mtu setting for eipgw
  content/zh/docs/onpremise/network/tutorial/vpc/mtu.md
Labels: size/XS

#661 feat(blog) 天空计算——云计算的下一个时代
  content/zh/blog/_posts/2022-01-21-skycomputing/index.md
Labels: size/M

#662 Automated cherry pick of #661: feat(blog) 天空计算——云计算的下一个时代
  content/zh/blog/_posts/2022-01-21-skycomputing/index.md
Labels: size/M

#665 fix: doc fixes
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
  content/zh/docs/setup/removehost.md
Labels: size/M

#666 Automated cherry pick of #665: fix: doc fixes
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
  content/zh/docs/setup/removehost.md
Labels: size/M

#663 fix: centos dracut module for arm
  content/zh/docs/onpremise/image/tutorial/sysimage/create.md
Labels: size/XS

#664 Automated cherry pick of #663: fix: centos dracut module for arm
  content/zh/docs/onpremise/image/tutorial/sysimage/create.md
Labels: size/XS

#671 fix: add content for admin security group
  content/zh/docs/onpremise/network/tutorial/configuration.md
  content/zh/docs/onpremise/network/tutorial/secgroup/resourse.md
Labels: size/M

#672 Automated cherry pick of #671: fix: add content for admin security group
  content/zh/docs/onpremise/network/tutorial/configuration.md
  content/zh/docs/onpremise/network/tutorial/secgroup/resourse.md
Labels: size/M

#669 feat(web-mutual-tls): add mutual tls doc
  content/zh/docs/setup/images/chrome-bad-ssl-client.png
  content/zh/docs/setup/images/chrome-certs.png
  content/zh/docs/setup/images/chrome-import-pkcs12.png
  content/zh/docs/setup/images/chrome-web.png
  content/zh/docs/setup/traefik-mutual-tls.md
Labels: size/L

#670 Automated cherry pick of #669: feat(web-mutual-tls): add mutual tls doc
  content/zh/docs/setup/images/chrome-bad-ssl-client.png
  content/zh/docs/setup/images/chrome-certs.png
  content/zh/docs/setup/images/chrome-import-pkcs12.png
  content/zh/docs/setup/images/chrome-web.png
  content/zh/docs/setup/traefik-mutual-tls.md
Labels: size/L

#673 fix: admin security group notes
  content/zh/docs/onpremise/network/tutorial/secgroup/resourse.md
Labels: size/XS

#674 Automated cherry pick of #673: fix: admin security group notes
  content/zh/docs/onpremise/network/tutorial/secgroup/resourse.md
Labels: size/XS
