Repository yunionio/docs, pull requests merged in 2022-12, with the labels that each got.

#1117 fix: dns error
  content/zh/docs/ops/dnserror.md
Labels: size/L

#1118 Automated cherry pick of #1117: fix: dns error
  content/zh/docs/ops/dnserror.md
Labels: size/L

#1115 feat(3.10):虚拟机新增定时任务、kvm主机支持GPU卡热插拔
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1116 feat(3.9):华为云aksk、费用模块新增费用总计
  content/zh/docs/web_ui/cost/analysis/billaccount.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billstatistics.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/cost/bill/billdetail.md
  content/zh/docs/web_ui/cost/bill/billresource.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/M

#1120 optimize: complement of how to check k8s dns error
  content/zh/docs/ops/dnserror.md
Labels: size/S

#1121 Automated cherry pick of #1120: optimize: complement of how to check k8s dns error
  content/zh/docs/ops/dnserror.md
Labels: size/S

#1122 feat: add doc of how to config node eviction threshold
  content/zh/docs/ops/eviction_threshold.md
Labels: size/M

#1125 feat(3.10): 添加外部数据
  content/zh/docs/development/images/resource.png
  content/zh/docs/development/remotefile.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1129 Automated cherry pick of #1128: fix: onecloud namespace hint
  content/zh/docs/quickstart/k8s.md
Labels: size/XS

#1133 fix(chart): helm installation guide
  content/zh/docs/quickstart/k8s.md
Labels: size/M

#1134 Automated cherry pick of #1133: fix(chart): helm installation guide
  content/zh/docs/quickstart/k8s.md
Labels: size/M

#1135 feat: update changelog
  content/en/docs/changelog/release-3.8/3-8-17.md
  content/en/docs/changelog/release-3.8/_index.md
  content/en/docs/changelog/release-3.9/3-9-0.md
  content/en/docs/changelog/release-3.9/3-9-5.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.8/3-8-17.md
  content/zh/docs/development/changelog/release-3.8/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-5.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1136 Automated cherry pick of #1135: feat: update changelog
  content/en/docs/changelog/release-3.8/3-8-17.md
  content/en/docs/changelog/release-3.8/_index.md
  content/en/docs/changelog/release-3.9/3-9-0.md
  content/en/docs/changelog/release-3.9/3-9-5.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.8/3-8-17.md
  content/zh/docs/development/changelog/release-3.8/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-5.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1137 fix: config version to v3.9.5
  config-ee.toml
  config.toml
Labels: size/XS

#1143 fix: image_repository of allinone config
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1144 Automated cherry pick of #1143: fix: image_repository of allinone config
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1145 Automated cherry pick of #1143: fix: image_repository of allinone config
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1141 Automated cherry pick of #1140: feat(k8s): offline service configuration
  content/zh/docs/function_principle/k8s/pre_env/_index.md
Labels: size/L

#1142 Automated cherry pick of #1140: feat(k8s): offline service configuration
  content/zh/docs/function_principle/k8s/pre_env/_index.md
Labels: size/L

#1146 feat(dev): command line usage
  content/zh/docs/development/contrib.md
Labels: size/M

#1147 Automated cherry pick of #1146: feat(dev): command line usage
  content/zh/docs/development/contrib.md
Labels: size/M

#1139 打开三级权限后，重启相关服务以便立即生效
  content/zh/docs/faq/others.md
Labels: size/XS

#1149 Automated cherry pick of #1139: 打开三级权限后，重启相关服务以便立即生效
  content/zh/docs/faq/others.md
Labels: size/XS

#1152 feat(development): doc contrib
  content/zh/docs/development/contrib.md
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/images/web_edit_doc.png
Labels: size/L

#1153 Automated cherry pick of #1152: feat(development): doc contrib
  content/zh/docs/development/contrib.md
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/images/web_edit_doc.png
Labels: size/L

#1155 fix: remove unused content of docs
  content/zh/docs/development/docs-dev.md
Labels: size/L

#1156 Automated cherry pick of #1155: fix: remove unused content of docs
  content/zh/docs/development/docs-dev.md
Labels: size/L

#1157 Automated cherry pick of #1152: feat(development): doc contrib #1155: fix: remove unused content of docs
  content/zh/docs/development/contrib.md
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/images/web_edit_doc.png
Labels: size/L

#1160 feat(3.10):华为hcs支持vpc对等连接新建
  content/zh/docs/web_ui/network/basicnetwork/_index.md
  content/zh/docs/web_ui/network/basicnetwork/peerlinkvpc.md
Labels: size/S

#1161 feat(3.10):kvm主机修改属性、修改启动顺序，详情增加电源状态
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1162 Update single_service_dev.md
  content/zh/docs/development/single_service_dev.md
Labels: size/XS

#1163 Update auto-migrate-on-hostdown.md
  content/zh/docs/function_principle/onpremise/host/auto-migrate-on-hostdown.md
Labels: size/XS

#1166 feat(3.10):多云、虚拟机操作新增proxmox，腾讯云新建cdn
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/network/cdn/domain.md
Labels: size/L

#1167 feat(3.9):谷歌云纳管步骤优化
  content/zh/docs/faq/image/google_create1.png
  content/zh/docs/faq/image/google_serviceaccount.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1168 Automated cherry pick of #1167: feat(3.9):谷歌云纳管步骤优化
  content/zh/docs/faq/image/google_create1.png
  content/zh/docs/faq/image/google_serviceaccount.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1169 feat: alert of how to deploy host inside vm
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/XS

#1170 Automated cherry pick of #1169: feat: alert of how to deploy host inside vm
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/XS
