Repository yunionio/docs, pull requests merged in 2022-03, with the labels that each got.

#720 fix 项目配额为商业版内容
  content/zh/docs/auth_security/iam/images/label1.png
  content/zh/docs/auth_security/iam/images/setting.png
  content/zh/docs/auth_security/iam/images/structure.png
  content/zh/docs/auth_security/iam/images/structure_show.png
  content/zh/docs/auth_security/iam/tutorial/project/quota.md
  content/zh/docs/auth_security/iam/tutorial/project/structure.md
  content/zh/docs/misc/globalsetting/tutorial/structure.md
Labels: size/M

#721 Automated cherry pick of #720: fix 项目配额为商业版内容
  content/zh/docs/auth_security/iam/tutorial/project/quota.md
Labels: size/XS

#722 feat(3.8)标签内容优化
  content/zh/docs/introduce/intro/common/tag/_index.md
  content/zh/docs/introduce/intro/common/tag/bind.md
  content/zh/docs/introduce/intro/common/tag/images/deltag.png
  content/zh/docs/introduce/intro/common/tag/images/edittag.png
  content/zh/docs/introduce/intro/common/tag/images/label1.png
  content/zh/docs/introduce/intro/common/tag/images/labelon1.png
  content/zh/docs/introduce/intro/common/tag/images/tagsearch1.png
  content/zh/docs/introduce/intro/common/tag/search.md
  content/zh/docs/introduce/intro/common/tag/unbind.md
Labels: size/M

#723 Automated cherry pick of #722: feat(3.8)标签内容优化
  content/zh/docs/introduce/intro/common/tag/_index.md
  content/zh/docs/introduce/intro/common/tag/bind.md
  content/zh/docs/introduce/intro/common/tag/images/deltag.png
  content/zh/docs/introduce/intro/common/tag/images/edittag.png
  content/zh/docs/introduce/intro/common/tag/images/label1.png
  content/zh/docs/introduce/intro/common/tag/images/labelon1.png
  content/zh/docs/introduce/intro/common/tag/images/tagsearch1.png
  content/zh/docs/introduce/intro/common/tag/search.md
  content/zh/docs/introduce/intro/common/tag/unbind.md
Labels: size/M

#724 feat(3.9)监控告警task处理
  content/zh/docs/introduce/intro/common/common.md
  content/zh/docs/monitor_ops/alert/images/alertpolicytip.png
  content/zh/docs/monitor_ops/alert/tutorial/alertrecord/uncoveralert.md
  content/zh/docs/monitor_ops/monitor/tutorial/overview/domain.md
  content/zh/docs/monitor_ops/monitor/tutorial/overview/project.md
  content/zh/docs/monitor_ops/monitor/tutorial/overview/system.md
  content/zh/docs/monitor_ops/monitor/tutorial/resource/host/monitor.md
  content/zh/docs/monitor_ops/monitor/tutorial/resource/vm/monitor.md
  content/zh/docs/onpremise/host/tutorial/viewhost.md
Labels: size/M

#726 3.8 bill
  content/zh/docs/meter_billing/analysis/tutorial/domain/show.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/view.md
  content/zh/docs/meter_billing/analysis/tutorial/project/show.md
  content/zh/docs/meter_billing/analysis/tutorial/resourcetype/show.md
  content/zh/docs/meter_billing/analysis/tutorial/tag/show.md
  content/zh/docs/meter_billing/analysis/tutorial/time/show.md
  content/zh/docs/meter_billing/overview/tutorial/view.md
Labels: size/M

#727 Automated cherry pick of #726: fix 费用总览优化
  content/zh/docs/meter_billing/analysis/tutorial/domain/show.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/view.md
  content/zh/docs/meter_billing/analysis/tutorial/project/show.md
  content/zh/docs/meter_billing/analysis/tutorial/resourcetype/show.md
  content/zh/docs/meter_billing/analysis/tutorial/tag/show.md
  content/zh/docs/meter_billing/analysis/tutorial/time/show.md
  content/zh/docs/meter_billing/overview/tutorial/view.md
Labels: size/M

#729 feat(3.8) License授权内容优化
  content/zh/docs/auth_security/iam/principle/_index.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/config.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/delete.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/log.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/show.md
  content/zh/docs/introduce/intro/images/copy1 copy.png
  content/zh/docs/introduce/intro/images/license.png
  content/zh/docs/introduce/intro/images/licensechange.png
  content/zh/docs/introduce/intro/images/licenseinfo1.png
  content/zh/docs/introduce/intro/images/licensesuccess.png
  content/zh/docs/introduce/intro/ui/more/about.md
  content/zh/docs/introduce/intro/ui/more/licenses.md
  content/zh/docs/introduce/intro/ui/more/versioninfo.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/cloudinbox.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/images/1-interface.png
  content/zh/docs/quickstart/images/bandwidth.png
  content/zh/docs/quickstart/images/cloudadmin1.png
  content/zh/docs/quickstart/images/complete.png
  content/zh/docs/quickstart/images/contact_me_qr_tech.png
  content/zh/docs/quickstart/images/https.png
  content/zh/docs/quickstart/images/install.png
  content/zh/docs/quickstart/images/login-password.png
  content/zh/docs/quickstart/images/login.png
  content/zh/docs/quickstart/images/networkconfig.png
  content/zh/docs/quickstart/images/vnc.png
  content/zh/docs/setup/HA.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/config.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/images/3node.png
  content/zh/docs/setup/images/4node.png
  content/zh/docs/setup/images/5node.png
  content/zh/docs/setup/images/centos-disk.png
  content/zh/docs/setup/images/centos-keyboard.png
  content/zh/docs/setup/images/centos-language.png
  content/zh/docs/setup/images/centos-network.png
  content/zh/docs/setup/images/centossetroot.png
  content/zh/docs/setup/images/haconfig.png
  content/zh/docs/setup/images/haenabled1.png
  content/zh/docs/setup/images/hamysqlconfig1.png
  content/zh/docs/setup/images/k8s-completed.png
  content/zh/docs/setup/images/k8s-config1.png
  content/zh/docs/setup/images/k8s-configmysql1.png
  content/zh/docs/setup/images/k8s-confirm.png
  content/zh/docs/setup/images/k8s-connectmysql1.png
  content/zh/docs/setup/images/k8s-firstnodeip1.png
  content/zh/docs/setup/images/k8s-jointoken1.png
  content/zh/docs/setup/images/k8s-network1.png
  content/zh/docs/setup/images/k8s-notfirstnodeconfig.png
  content/zh/docs/setup/images/k8s-reboot.png
  content/zh/docs/setup/images/k8s-selectnetwork1.png
  content/zh/docs/setup/images/k8s-token1.png
  content/zh/docs/setup/images/k8sha-network.png
  content/zh/docs/setup/images/k8sonecloud1.png
  content/zh/docs/setup/install.md
Labels: size/XL

#730 Automated cherry pick of #729: feat(3.8) License授权内容优化
  content/zh/docs/auth_security/iam/principle/_index.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/config.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/delete.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/log.md
  content/zh/docs/auth_security/notify/tutorial/mailconfig/show.md
  content/zh/docs/introduce/intro/images/copy1 copy.png
  content/zh/docs/introduce/intro/images/license.png
  content/zh/docs/introduce/intro/images/licensechange.png
  content/zh/docs/introduce/intro/images/licenseinfo1.png
  content/zh/docs/introduce/intro/images/licensesuccess.png
  content/zh/docs/introduce/intro/ui/more/about.md
  content/zh/docs/introduce/intro/ui/more/licenses.md
  content/zh/docs/introduce/intro/ui/more/versioninfo.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/cloudinbox.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/images/1-interface.png
  content/zh/docs/quickstart/images/bandwidth.png
  content/zh/docs/quickstart/images/cloudadmin1.png
  content/zh/docs/quickstart/images/complete.png
  content/zh/docs/quickstart/images/contact_me_qr_tech.png
  content/zh/docs/quickstart/images/https.png
  content/zh/docs/quickstart/images/install.png
  content/zh/docs/quickstart/images/login-password.png
  content/zh/docs/quickstart/images/login.png
  content/zh/docs/quickstart/images/networkconfig.png
  content/zh/docs/quickstart/images/vnc.png
  content/zh/docs/setup/HA.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/config.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/images/3node.png
  content/zh/docs/setup/images/4node.png
  content/zh/docs/setup/images/5node.png
  content/zh/docs/setup/images/centos-disk.png
  content/zh/docs/setup/images/centos-keyboard.png
  content/zh/docs/setup/images/centos-language.png
  content/zh/docs/setup/images/centos-network.png
  content/zh/docs/setup/images/centossetroot.png
  content/zh/docs/setup/images/haconfig.png
  content/zh/docs/setup/images/haenabled1.png
  content/zh/docs/setup/images/hamysqlconfig1.png
  content/zh/docs/setup/images/k8s-completed.png
  content/zh/docs/setup/images/k8s-config1.png
  content/zh/docs/setup/images/k8s-configmysql1.png
  content/zh/docs/setup/images/k8s-confirm.png
  content/zh/docs/setup/images/k8s-connectmysql1.png
  content/zh/docs/setup/images/k8s-firstnodeip1.png
  content/zh/docs/setup/images/k8s-jointoken1.png
  content/zh/docs/setup/images/k8s-network1.png
  content/zh/docs/setup/images/k8s-notfirstnodeconfig.png
  content/zh/docs/setup/images/k8s-reboot.png
  content/zh/docs/setup/images/k8s-selectnetwork1.png
  content/zh/docs/setup/images/k8s-token1.png
  content/zh/docs/setup/images/k8sha-network.png
  content/zh/docs/setup/images/k8sonecloud1.png
  content/zh/docs/setup/install.md
Labels: size/XL

#728 3.9 azure国际区支持RI&费用分析-平台、云账号内容修改
  content/zh/docs/meter_billing/analysis/tutorial/account/cost.md
  content/zh/docs/meter_billing/analysis/tutorial/account/list.md
  content/zh/docs/meter_billing/analysis/tutorial/account/overview.md
  content/zh/docs/meter_billing/analysis/tutorial/account/ri.md
  content/zh/docs/meter_billing/analysis/tutorial/account/show.md
  content/zh/docs/meter_billing/analysis/tutorial/domain/show.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/list.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/show.md
  content/zh/docs/meter_billing/analysis/tutorial/project/show.md
Labels: size/L

#731 fix error
  content/zh/docs/setup/baremetal.md
Labels: size/XS

#732 Automated cherry pick of #731: fix error
  content/zh/docs/setup/baremetal.md
Labels: size/XS

#733 feat(3.8)安装内容优化
  content/zh/docs/auth_security/iam/tutorial/policy/create.md
  content/zh/docs/auth_security/iam/tutorial/role/create.md
  content/zh/docs/misc/globalsetting/tutorial/brower.md
  content/zh/docs/misc/globalsetting/tutorial/common.md
  content/zh/docs/misc/globalsetting/tutorial/kvm.md
  content/zh/docs/misc/log/tutorial/logmgmt/_index.md
  content/zh/docs/misc/log/tutorial/logmgmt/delete.md
  content/zh/docs/onpremise/backup/tutorial/vm/delete.md
  content/zh/docs/onpremise/backup/tutorial/vm/import.md
  content/zh/docs/onpremise/backup/tutorial/vm/recover.md
  content/zh/docs/onpremise/backup/tutorial/vm/tar.md
  content/zh/docs/onpremise/host/tutorial/viewhost.md
  content/zh/docs/onpremise/network/tutorial/default/viewwire.md
  content/zh/docs/onpremise/snapshot/tutorial/instancesnapshot/rollback.md
  content/zh/docs/onpremise/vminstance/tutorial/connect.md
  content/zh/docs/onpremise/vminstance/tutorial/create.md
  content/zh/docs/onpremise/vminstance/tutorial/setting/bindcpu.md
  content/zh/docs/onpremise/vminstance/tutorial/setting/snapshot.md
  content/zh/docs/setup/ce-ee-switch.md
  content/zh/docs/setup/config.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/images/about.png
  content/zh/docs/setup/images/more.png
  content/zh/docs/setup/images/upgradetip1.png
  content/zh/docs/setup/install.md
  content/zh/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade_iso.md
Labels: size/L

#734 Automated cherry pick of #733: feat(3.8)安装内容优化
  content/zh/docs/setup/ce-ee-switch.md
  content/zh/docs/setup/config.md
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/images/about.png
  content/zh/docs/setup/images/more.png
  content/zh/docs/setup/images/upgradetip1.png
  content/zh/docs/setup/install.md
  content/zh/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade_iso.md
Labels: size/L

#735 排查cloudpods 纳管OpenStack后，资源同步为空
  content/zh/docs/multicloud/cloudaccounts/faq/openstack.md
Labels: size/S

#738 feat: db consistency config
  content/zh/docs/setup/db-record-consistency.md
Labels: size/M

#741 feat(3.8)消息订阅补充介绍内容
  content/zh/docs/auth_security/notify/tutorial/notify_topic/intro.md
  content/zh/docs/introduce/_index.md
Labels: size/S

#742 Automated cherry pick of #741: feat(3.8)消息订阅补充介绍内容
  content/zh/docs/auth_security/notify/tutorial/notify_topic/intro.md
  content/zh/docs/introduce/_index.md
Labels: size/S

#747 fix: ee docs displayed in ce edition
  scripts/converter/helper.py
  scripts/converter/processor.py
Labels: size/S

#748 Automated cherry pick of #747: fix: ee docs displayed in ce edition
  scripts/converter/helper.py
  scripts/converter/processor.py
Labels: size/S

#746 Automated cherry pick of #745: fix word
  content/zh/docs/apisdk/01_api.md
  content/zh/docs/apisdk/02_sdk.md
  content/zh/docs/apisdk/_index.md
  content/zh/docs/climc/_index.md
  content/zh/docs/climc/usage.md
  content/zh/docs/contact/_index.md
  content/zh/docs/development/codestruct.md
  content/zh/docs/development/dev-env.md
  content/zh/docs/k8s/_index.md
  content/zh/docs/k8s/pre_env/_index.md
  content/zh/docs/multicloud/_index.md
  content/zh/docs/multicloud/cloudaccounts/faq/openstack.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/delete.md
  content/zh/docs/multicloud/compute/vminstance/faq/create_failed.md
  content/zh/docs/onpremise/_index.md
  content/zh/docs/onpremise/baremetal/faq/manual_change_raid.md
  content/zh/docs/onpremise/baremetal/faq/nic_persistent_naming.md
  content/zh/docs/onpremise/glance/_index.md
  content/zh/docs/onpremise/lb/_index.md
Labels: size/M

#751 feat: add backend codestruct
  content/zh/docs/development/codestruct.md
Labels: size/L

#753 fix: k8s setup loadBalancerEndpoint
  content/zh/docs/quickstart/k8s.md
Labels: size/M

#754 Automated cherry pick of #753: fix: k8s setup loadBalancerEndpoint
  content/zh/docs/quickstart/k8s.md
Labels: size/M

#759 add k8s quickstart alert
  content/zh/docs/quickstart/k8s.md
Labels: size/XS

#757 feat（3.8）迁移内容优化
  content/zh/docs/multicloud/compute/image/tutorial/create.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/connect.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/createpublic.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/delete.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/push.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/sync.md
  content/zh/docs/multicloud/network/dns/tutorial/recordset/delete.md
  content/zh/docs/multicloud/network/dns/tutorial/vpc/add.md
  content/zh/docs/multicloud/network/dns/tutorial/vpc/delete.md
  content/zh/docs/multicloud/network/vpc/tutorial/create_public.md
  content/zh/docs/onpremise/baremetal/faq/nic_persistent_naming.md
  content/zh/docs/onpremise/baremetal/tutorial/create_register_redirect.md
  content/zh/docs/onpremise/glance/tutorial/sysimage/create.md
  content/zh/docs/onpremise/host/faq/troubleshooting.md
  content/zh/docs/onpremise/lb/tutorial/lbagent/deploy.md
  content/zh/docs/onpremise/network/faq/addnetwork.md
  content/zh/docs/onpremise/network/tutorial/vpc/vpcvip.md
  content/zh/docs/onpremise/vminstance/faq/import.md
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
  content/zh/docs/ops/agent.md
  content/zh/docs/ops/backendlogs.md
  content/zh/docs/ops/clearimage.md
  content/zh/docs/ops/commonops.md
  content/zh/docs/ops/component.md
  content/zh/docs/ops/log.md
  content/zh/docs/ops/poderror.md
Labels: size/L

#758 Automated cherry pick of #757: feat（3.8）迁移内容优化
  content/zh/docs/multicloud/compute/image/tutorial/create.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/connect.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/createpublic.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/delete.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/push.md
  content/zh/docs/multicloud/network/dns/tutorial/domain/sync.md
  content/zh/docs/multicloud/network/dns/tutorial/recordset/delete.md
  content/zh/docs/multicloud/network/dns/tutorial/vpc/add.md
  content/zh/docs/multicloud/network/dns/tutorial/vpc/delete.md
  content/zh/docs/multicloud/network/vpc/tutorial/create_public.md
  content/zh/docs/onpremise/baremetal/faq/nic_persistent_naming.md
  content/zh/docs/onpremise/baremetal/tutorial/create_register_redirect.md
  content/zh/docs/onpremise/glance/tutorial/sysimage/create.md
  content/zh/docs/onpremise/host/faq/troubleshooting.md
  content/zh/docs/onpremise/lb/tutorial/lbagent/deploy.md
  content/zh/docs/onpremise/network/faq/addnetwork.md
  content/zh/docs/onpremise/network/tutorial/vpc/vpcvip.md
  content/zh/docs/onpremise/vminstance/faq/import.md
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
  content/zh/docs/ops/agent.md
  content/zh/docs/ops/backendlogs.md
  content/zh/docs/ops/clearimage.md
  content/zh/docs/ops/commonops.md
  content/zh/docs/ops/component.md
  content/zh/docs/ops/log.md
  content/zh/docs/ops/poderror.md
Labels: size/L

#761 feature: network example configuration
  content/zh/docs/onpremise/network/faq/examples.md
Labels: size/L

#762 Automated cherry pick of #761: feature: network example configuration
  content/zh/docs/onpremise/network/faq/examples.md
Labels: size/L

#763 minor fixes
  content/zh/docs/onpremise/network/faq/examples.md
Labels: size/XS

#764 Automated cherry pick of #763: minor fixes
  content/zh/docs/onpremise/network/faq/examples.md
Labels: size/XS

#767 feat(3.9)三权
  content/zh/docs/auth_security/iam/best_practice/_index.md
  content/zh/docs/auth_security/iam/best_practice/separate_policy.md
Labels: size/L
