Repository yunionio/docs, pull requests merged in 2022-11, with the labels that each got.

#1062 fix: change container helm url
  content/zh/docs/web_ui/ops/Orchestration/k8s-repo.md
Labels: size/XS

#1061 feat(3.9):开源版发布日志v3.9.4
  content/zh/docs/release/v3_9_4.md
Labels: size/M

#1064 fix: misc docs 20221101
  content/zh/docs/function_principle/monitor_ops/monitor/monitoragent.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/L

#1066 Automated cherry pick of #1064: fix: misc docs 20221101
  content/zh/docs/function_principle/monitor_ops/monitor/monitoragent.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/L

#1067 feat(3.9):全局设置增加错误详情隐藏开关
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/XS

#1069 fix: iam example
  content/zh/docs/function_principle/auth_security/iam/best_practice/selfservice.md
Labels: size/S

#1070 Automated cherry pick of #1069: fix: iam example
  content/zh/docs/function_principle/auth_security/iam/best_practice/selfservice.md
Labels: size/S

#1072 fix(lb): yum repo url of lbagent
  content/zh/docs/web_ui/network/lbcluster/lbagent.md
Labels: size/XS

#1073 Automated cherry pick of #1072: fix(lb): yum repo url of lbagent
  content/zh/docs/web_ui/network/lbcluster/lbagent.md
Labels: size/XS

#1071 feat(3.9):块存储区分物理机宿主机、存储文案优化、控制面板磁贴增加调度标签、项目标签过滤
  content/zh/docs/web_ui/images/storage/blockstorage.png
  content/zh/docs/web_ui/images/storage/blockstorage1.png
  content/zh/docs/web_ui/intro/dashboard.md
  content/zh/docs/web_ui/storage/_index.md
  content/zh/docs/web_ui/storage/block.md
Labels: size/S

#1076 Automated cherry pick of #1071: feat(3.9):块存储区分物理机宿主机、存储文案优化、控制面板磁贴增加调度标签、项目标签过滤
  content/zh/docs/web_ui/images/storage/blockstorage.png
  content/zh/docs/web_ui/images/storage/blockstorage1.png
  content/zh/docs/web_ui/intro/dashboard.md
  content/zh/docs/web_ui/storage/_index.md
  content/zh/docs/web_ui/storage/block.md
Labels: size/S

#1074 feat(master):新增hcs纳管步骤、列表新增平台对接hcs的资源
  content/zh/docs/web_ui/images/multiplecloud/hcsaddaksk.png
  content/zh/docs/web_ui/images/multiplecloud/hcsaksk.png
  content/zh/docs/web_ui/images/multiplecloud/hcsbelongaksk.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/M

#1077 Automated cherry pick of #1075: feat(3.9):云账号hcso失效内部链接修复
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1084 Automated cherry pick of #1083: qa(ha): how to rejoin by manual way
  content/zh/docs/setup/ha-ce.md
Labels: size/M

#1081 add SR-IOV nic config docs
  content/zh/docs/function_principle/onpremise/vminstance/sriov.md
Labels: size/L

#1080 feat(3.9):共享控制面板、虚拟机详情页新增最大带宽等、rds详情页新增iops、mongodb详情页新增最大连接数，iops
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/database/mangodb.md
  content/zh/docs/web_ui/database/rds.md
  content/zh/docs/web_ui/database/redis.md
  content/zh/docs/web_ui/intro/dashboard.md
Labels: size/S

#1085 Automated cherry pick of #1080: feat(3.9):共享控制面板、虚拟机详情页新增最大带宽等、rds详情页新增iops、mongodb详情页新增最大连接数，iops
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/database/mangodb.md
  content/zh/docs/web_ui/database/rds.md
  content/zh/docs/web_ui/database/redis.md
  content/zh/docs/web_ui/intro/dashboard.md
Labels: size/S

#1082 feat(3.9):本地新建硬盘支持指定宿主机/虚拟机，迁移设置带宽、快速收敛等功能、重置密码kvm支持安装QGA开机重置、快照建磁盘
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/computing/storage/disk.md
Labels: size/M

#1087 fix(ha-rejoin): ocboot ref
  content/zh/docs/setup/ha-ce.md
Labels: size/XS

#1089 feat(3.9):控制面板磁贴优化、企业信息支持重置修改信息、保存镜像增加进度
  content/zh/docs/web_ui/computing/image/image.md
  content/zh/docs/web_ui/images/dashboard/hostnumber.png
  content/zh/docs/web_ui/intro/dashboard.md
  content/zh/docs/web_ui/systemconfig/system/companyinfo.md
Labels: size/M

#1090 Automated cherry pick of #1089: feat(3.9):控制面板磁贴优化、企业信息支持重置修改信息、保存镜像增加进度
  content/zh/docs/web_ui/computing/image/image.md
  content/zh/docs/web_ui/images/dashboard/hostnumber.png
  content/zh/docs/web_ui/intro/dashboard.md
  content/zh/docs/web_ui/systemconfig/system/companyinfo.md
Labels: size/M

#1091 feat(3.9):云账号定时任务、全局搜索新增ID、云上ID
  content/zh/docs/web_ui/images/intro/cloudid.png
  content/zh/docs/web_ui/images/intro/id.png
  content/zh/docs/web_ui/intro/ui/globalsearch.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1098 Automated cherry pick of #1095: feat(3.9):多云资源纳管、多云虚拟机新增操作
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/L

#1099 Automated cherry pick of #1096: feat(3.9):iso安装增加注意事项
  content/zh/docs/setup/install.md
Labels: size/S

#1097 feature: recover mysql HA
  content/zh/docs/ops/halt_cluster.md
  content/zh/docs/ops/mysql_ha_recovery.md
Labels: size/L

#1101 fix: update docs 20221123
  content/zh/docs/ops/halt_cluster.md
Labels: size/XS

#1103 feat(3.9):KVM更换块存储、产品手册链接自定义、开源文档新增产品手册和版本信息、全局配置增加网络ping探测开关、实例账单新增优…
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/images/bill/associatebill.png
  content/zh/docs/web_ui/images/bill/associatebill1.png
  content/zh/docs/web_ui/intro/ui/productmanual.md
  content/zh/docs/web_ui/intro/ui/version.md
  content/zh/docs/web_ui/ops/scheduledtask.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
Labels: size/M

#1106 Automated cherry pick of #1103: feat(3.9):KVM更换块存储、产品手册链接自定义、开源文档新增产品手册和版本信息、全局配置增加网络ping探测开关、实例账单新增优惠率字段、运维工具-定时任务文案补充优化
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/images/bill/associatebill.png
  content/zh/docs/web_ui/images/bill/associatebill1.png
  content/zh/docs/web_ui/intro/ui/productmanual.md
  content/zh/docs/web_ui/intro/ui/version.md
  content/zh/docs/web_ui/ops/scheduledtask.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
Labels: size/M

#1107 Automated cherry pick of #1103: feat(3.9):KVM更换块存储、产品手册链接自定义、开源文档新增产品手册和版本信息、全局配置增加网络ping探测开关、实例账单新增优惠率字段、运维工具-定时任务文案补充优化
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/images/bill/associatebill.png
  content/zh/docs/web_ui/images/bill/associatebill1.png
  content/zh/docs/web_ui/intro/ui/productmanual.md
  content/zh/docs/web_ui/intro/ui/version.md
  content/zh/docs/web_ui/ops/scheduledtask.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
Labels: size/M

#1104 fix: minor update 20221129
  content/zh/docs/quickstart/k8s.md
Labels: size/XS

#1109 feat(blog): cloudpods on k8s experience sharing
  content/zh/blog/_posts/2022-11-29-cloudpods-k8s-experience-sharing.md
Labels: size/L

#1110 Automated cherry pick of #1109: feat(blog): cloudpods on k8s experience sharing
  content/zh/blog/_posts/2022-11-29-cloudpods-k8s-experience-sharing.md
Labels: size/L

#1111 Automated cherry pick of #1109: feat(blog): cloudpods on k8s experience sharing
  content/zh/blog/_posts/2022-11-29-cloudpods-k8s-experience-sharing.md
Labels: size/L

#1112 fix: update k8s container content
  content/zh/blog/_posts/2022-11-29-cloudpods-k8s-experience-sharing.md
Labels: size/M

#1113 Automated cherry pick of #1112: fix: update k8s container content
  content/zh/blog/_posts/2022-11-29-cloudpods-k8s-experience-sharing.md
Labels: size/M
