Repository yunionio/docs, pull requests merged in 2022-04, with the labels that each got.

#771 changelog 3.8.8
  content/en/docs/changelog/release-3.8/3-8-8.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-8.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/L

#772 Automated cherry pick of #771: changelog 3.8.8
  content/en/docs/changelog/release-3.8/3-8-8.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-8.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/L

#775 feat: release note of 3.8.8
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/release/v3_8_8.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#773 fix word
  content/zh/docs/onpremise/baremetal/faq/_index.md
  content/zh/docs/onpremise/baremetal/principle/_index.md
  content/zh/docs/onpremise/baremetal/tutorial/_index.md
  content/zh/docs/onpremise/scheduler/_index.md
  content/zh/docs/setup/baremetal.md
Labels: size/S

#774 Automated cherry pick of #773: fix word
  content/zh/docs/onpremise/baremetal/faq/_index.md
  content/zh/docs/onpremise/baremetal/principle/_index.md
  content/zh/docs/onpremise/baremetal/tutorial/_index.md
  content/zh/docs/onpremise/scheduler/_index.md
  content/zh/docs/setup/baremetal.md
Labels: size/S

#769 feat(3.8)补充all in one安装无宿主机faq
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/images/hostnameerror.png
  content/zh/docs/quickstart/images/iperror.png
  content/zh/docs/quickstart/images/nohost.png
Labels: size/M

#770 Automated cherry pick of #769: feat(3.8)补充all in one安装无宿主机faq
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/images/hostnameerror.png
  content/zh/docs/quickstart/images/iperror.png
  content/zh/docs/quickstart/images/nohost.png
Labels: size/M

#777 Automated cherry pick of #768: 具体化获取调用栈步骤
  content/zh/docs/development/devtools.md
Labels: size/L

#768 具体化获取调用栈步骤
  content/zh/docs/development/devtools.md
Labels: size/L

#779 add service subscription link
  config.toml
  content/zh/_index.html
Labels: size/XS

#781 set ocboot branch to release/3.8
  content/en/docs/quickstart/allinone.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/host.md
Labels: size/XS

#736 升级内核.md
  content/zh/docs/setup/升级内核.md
Labels: size/M

#778 Automated cherry pick of #736: Create 升级内核.md
  content/zh/docs/setup/升级内核.md
Labels: size/M

#784 feat(3.8) 开源版UI截图更新
  content/zh/docs/introduce/ui/baremetal.md
  content/zh/docs/introduce/ui/cloudsso.md
  content/zh/docs/introduce/ui/images/addsamluser.png
  content/zh/docs/introduce/ui/images/cloudsamluser.png
  content/zh/docs/introduce/ui/images/cloudssoentry.png
  content/zh/docs/introduce/ui/images/createvmware.png
  content/zh/docs/introduce/ui/images/createvmwarevm1.png
  content/zh/docs/introduce/ui/images/createvmwarevm2.png
  content/zh/docs/introduce/ui/images/domainlist.png
  content/zh/docs/introduce/ui/images/eiplist.png
  content/zh/docs/introduce/ui/images/enablecloudsso.png
  content/zh/docs/introduce/ui/images/grouplist.png
  content/zh/docs/introduce/ui/images/idplist.png
  content/zh/docs/introduce/ui/images/imagelist.png
  content/zh/docs/introduce/ui/images/ipsubnetlist.png
  content/zh/docs/introduce/ui/images/kvmvmvnc.png
  content/zh/docs/introduce/ui/images/lblist.png
  content/zh/docs/introduce/ui/images/policylist.png
  content/zh/docs/introduce/ui/images/projectlist.png
  content/zh/docs/introduce/ui/images/rolelist.png
  content/zh/docs/introduce/ui/images/userlist.png
  content/zh/docs/introduce/ui/images/vmwareipsubnetlist.png
  content/zh/docs/introduce/ui/images/vmwarelist.png
  content/zh/docs/introduce/ui/images/vmwarewirelist.png
  content/zh/docs/introduce/ui/images/vpclist.png
  content/zh/docs/introduce/ui/images/wirelist.png
  content/zh/docs/introduce/ui/keystone.md
  content/zh/docs/introduce/ui/kvm.md
  content/zh/docs/introduce/ui/multicloud.md
  content/zh/docs/introduce/ui/vmware.md
Labels: size/L

#785 Automated cherry pick of #784: feat(3.8) 开源版UI截图更新
  content/zh/docs/introduce/ui/baremetal.md
  content/zh/docs/introduce/ui/cloudsso.md
  content/zh/docs/introduce/ui/images/addsamluser.png
  content/zh/docs/introduce/ui/images/cloudsamluser.png
  content/zh/docs/introduce/ui/images/cloudssoentry.png
  content/zh/docs/introduce/ui/images/createvmware.png
  content/zh/docs/introduce/ui/images/createvmwarevm1.png
  content/zh/docs/introduce/ui/images/createvmwarevm2.png
  content/zh/docs/introduce/ui/images/domainlist.png
  content/zh/docs/introduce/ui/images/eiplist.png
  content/zh/docs/introduce/ui/images/enablecloudsso.png
  content/zh/docs/introduce/ui/images/grouplist.png
  content/zh/docs/introduce/ui/images/idplist.png
  content/zh/docs/introduce/ui/images/imagelist.png
  content/zh/docs/introduce/ui/images/ipsubnetlist.png
  content/zh/docs/introduce/ui/images/kvmvmvnc.png
  content/zh/docs/introduce/ui/images/lblist.png
  content/zh/docs/introduce/ui/images/policylist.png
  content/zh/docs/introduce/ui/images/projectlist.png
  content/zh/docs/introduce/ui/images/rolelist.png
  content/zh/docs/introduce/ui/images/userlist.png
  content/zh/docs/introduce/ui/images/vmwareipsubnetlist.png
  content/zh/docs/introduce/ui/images/vmwarelist.png
  content/zh/docs/introduce/ui/images/vmwarewirelist.png
  content/zh/docs/introduce/ui/images/vpclist.png
  content/zh/docs/introduce/ui/images/wirelist.png
  content/zh/docs/introduce/ui/keystone.md
  content/zh/docs/introduce/ui/kvm.md
  content/zh/docs/introduce/ui/multicloud.md
  content/zh/docs/introduce/ui/vmware.md
Labels: size/L

#787 feat(3.8) 添加faq
  content/zh/docs/multicloud/cloudaccounts/faq/delete_failed.md
  content/zh/docs/multicloud/compute/vminstance/faq/common_failed.md
  content/zh/docs/onpremise/network/faq/examples.md
  content/zh/docs/onpremise/storage/blockstorage/faq/add-storage.md
Labels: size/XS

#788 feat(3.9) 标签支持分割&新增全局配置
  content/zh/docs/meter_billing/analysis/tutorial/account/list.md
  content/zh/docs/meter_billing/multi-analysis/tutorial/view.md
  content/zh/docs/misc/globalsetting/tutorial/kvm.md
  content/zh/docs/misc/globalsetting/tutorial/multicloud.md
Labels: size/S

#786 fix: account sync faq
  content/zh/docs/multicloud/cloudaccounts/faq/sync.md
  content/zh/docs/multicloud/cloudaccounts/images/cloudprovider_disabled.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudprovider_region_disabled.png
  content/zh/docs/multicloud/cloudaccounts/images/lake_of_permission.png
Labels: size/M

#790 Automated cherry pick of #786: fix: account sync faq
  content/zh/docs/multicloud/cloudaccounts/faq/sync.md
  content/zh/docs/multicloud/cloudaccounts/images/cloudprovider_disabled.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudprovider_region_disabled.png
  content/zh/docs/multicloud/cloudaccounts/images/lake_of_permission.png
Labels: size/M

#792 docs for scheduler
  content/zh/docs/onpremise/scheduler/principle/_index.md
  content/zh/docs/onpremise/scheduler/principle/algorithm.md
  content/zh/docs/onpremise/scheduler/principle/schedtags.md
Labels: size/L

#793 Automated cherry pick of #792: docs for scheduler
  content/zh/docs/onpremise/scheduler/principle/_index.md
  content/zh/docs/onpremise/scheduler/principle/algorithm.md
  content/zh/docs/onpremise/scheduler/principle/schedtags.md
Labels: size/L

#749 fix: add doc for bingocloud
  content/zh/docs/multicloud/_index.md
Labels: size/M

#794 fix补充飞天RDS监控项
  content/zh/docs/multicloud/db/rds/tutorial/monitor.md
Labels: size/XS

#795 Automated cherry pick of #794: fix补充飞天RDS监控项
  content/zh/docs/multicloud/db/rds/tutorial/monitor.md
Labels: size/XS

#799 more detailed dns setting
  content/zh/docs/onpremise/network/tutorial/configuration.md
Labels: size/M

#800 Automated cherry pick of #799: more detailed dns setting
  content/zh/docs/onpremise/network/tutorial/configuration.md
Labels: size/M

#796 feat(3.9) 命令记录
  content/zh/docs/misc/log/tutorial/command.md
Labels: size/S
