Repository yunionio/docs, pull requests merged in 2022-05, with the labels that each got.

#827 feat(3.8) 批量迁移添加说明&fix word
  content/zh/docs/multicloud/cloudaccounts/images/aliyunossbucket.png
  content/zh/docs/multicloud/cloudaccounts/images/aliyunossbucket1.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/billinfo.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
Labels: size/S

#828 Automated cherry pick of #827: feat(3.8) 批量迁移添加说明&fix word
  content/zh/docs/multicloud/cloudaccounts/images/aliyunossbucket.png
  content/zh/docs/multicloud/cloudaccounts/images/aliyunossbucket1.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/billinfo.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
Labels: size/S

#826 feat(3.9) 远程连接MFA认证&权限支持资源标签
  content/zh/docs/auth_security/iam/tutorial/policy/create.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/connect.md
  content/zh/docs/onpremise/baremetal/tutorial/baremetal/console.md
  content/zh/docs/onpremise/baremetal/tutorial/machine/console.md
  content/zh/docs/onpremise/host/tutorial/console.md
  content/zh/docs/onpremise/vminstance/tutorial/connect.md
Labels: size/S

#829 fix: swagger api show
  content/en/docs/swagger/index.html
  content/en/docs/swagger/redoc.standalone.js
  content/zh/docs/swagger/index.html
  content/zh/docs/swagger/redoc.standalone.js
Labels: size/XXL

#834 feat: release 3.8.10
  content/en/docs/changelog/release-3.8/3-8-11.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-11.md
  content/zh/docs/changelog/release-3.8/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/upgrade.md
Labels: size/L

#831 fix: add docs for code
  content/zh/docs/development/api-model.md
  content/zh/docs/development/images/vms-api.png
  content/zh/docs/development/images/vms-network.png
  content/zh/docs/development/images/vms-rpc.png
  content/zh/docs/development/images/vms.png
Labels: size/L

#832 Automated cherry pick of #831: fix: add docs for code
  content/zh/docs/development/api-model.md
  content/zh/docs/development/images/vms-api.png
  content/zh/docs/development/images/vms-network.png
  content/zh/docs/development/images/vms-rpc.png
  content/zh/docs/development/images/vms.png
Labels: size/L
