Repository yunionio/docs, pull requests merged in 2022-09, with the labels that each got.

#939 Remove logos
  static/images/logos/DCITS/favicon.png
  static/images/logos/DCITS/login.png
  static/images/logos/DCITS/logo.png
  static/images/logos/GZYUN/favicon.png
  static/images/logos/GZYUN/login.png
  static/images/logos/GZYUN/logo.png
  static/images/logos/MultiCloud/favicon.png
  static/images/logos/MultiCloud/login.png
  static/images/logos/MultiCloud/logo.png
  static/images/logos/TRANSWARP/favicon.png
  static/images/logos/TRANSWARP/login.png
  static/images/logos/TRANSWARP/logo.png
  static/images/logos/UUCLOUD/favicon.png
  static/images/logos/UUCLOUD/login.png
  static/images/logos/UUCLOUD/logo.png
  static/images/logos/Ucloud/login.png
  static/images/logos/Ucloud/logo.png
  static/images/logos/ZYCetcCloud/login.png
  static/images/logos/ZYCetcCloud/logo.png
  static/images/logos/aisenzhe/favicon.png
  static/images/logos/aisenzhe/login.png
  static/images/logos/aisenzhe/logo.png
  static/images/logos/dianxin/favicon.png
  static/images/logos/dianxin/login.png
  static/images/logos/dianxin/logo.png
  static/images/logos/didicloud/favicon.png
  static/images/logos/didicloud/login.png
  static/images/logos/didicloud/logo.png
  static/images/logos/hengyuntai/favicon.png
  static/images/logos/hengyuntai/login.png
  static/images/logos/hengyuntai/logo.png
  static/images/logos/kunlian/favicon.png
  static/images/logos/kunlian/login.png
  static/images/logos/kunlian/logo.png
  static/images/logos/liantai/favicon.png
  static/images/logos/liantai/login.png
  static/images/logos/liantai/logo.png
  static/images/logos/qishang/favicon.png
  static/images/logos/qishang/login.png
  static/images/logos/qishang/logo.png
  static/images/logos/sinoage/login.png
  static/images/logos/sinoage/logo.png
  static/images/logos/weiyi/favicon.png
  static/images/logos/weiyi/login.png
  static/images/logos/weiyi/logo.png
  static/images/logos/yunfan/favicon.png
  static/images/logos/yunfan/login.png
  static/images/logos/yunfan/logo.png
  static/images/logos/yungoal/favicon.png
  static/images/logos/yungoal/login.png
  static/images/logos/yungoal/logo.png
  static/images/logos/zhiyun/favicon.png
  static/images/logos/zhiyun/login.png
  static/images/logos/zhiyun/logo.png
  static/images/logos/zhizhen/favicon.png
  static/images/logos/zhizhen/login.png
  static/images/logos/zhizhen/logo.png
Labels: size/XS

#943 增加hugo的timeout时间配置
  config-ee.toml
Labels: size/XS

#944 Automated cherry pick of #943: 增加hugo的timeout时间配置
  config-ee.toml
Labels: size/XS

#938 feat:3.9多层级组织架构以及azure订阅授权给应用程序步骤
  content/zh/docs/faq/image/azure1.png
  content/zh/docs/faq/image/azure2.png
  content/zh/docs/faq/image/azure3.png
  content/zh/docs/faq/image/azure4.png
  content/zh/docs/faq/image/azure5.png
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/database/rds.md
  content/zh/docs/web_ui/iam/keystone/project.md
  content/zh/docs/web_ui/images/computing/VMware1.png
  content/zh/docs/web_ui/images/database/rds1.png
  content/zh/docs/web_ui/images/iam/project1.png
  content/zh/docs/web_ui/images/network/lb.png
  content/zh/docs/web_ui/images/storage/bucket.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/network/lb/lb.md
  content/zh/docs/web_ui/storage/bucket.md
Labels: size/M

#941 feat:3.9常用镜像链接 开源版
  content/zh/docs/function_principle/onpremise/glance/common.md
Labels: size/L

#942 feat:3.9华为云获取短信参数步骤
  content/zh/docs/web_ui/iam/notify/mailconfig.md
Labels: size/S

#945 Automated cherry pick of #938: feat:3.9多层级组织架构以及azure订阅授权给应用程序步骤 #941: feat:3.9常用镜像链接 开源版 #942: feat:3.9华为云获取短信参数步骤
  content/zh/docs/faq/image/azure1.png
  content/zh/docs/faq/image/azure2.png
  content/zh/docs/faq/image/azure3.png
  content/zh/docs/faq/image/azure4.png
  content/zh/docs/faq/image/azure5.png
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/database/rds.md
  content/zh/docs/web_ui/iam/keystone/project.md
  content/zh/docs/web_ui/iam/notify/mailconfig.md
  content/zh/docs/web_ui/images/computing/VMware1.png
  content/zh/docs/web_ui/images/database/rds1.png
  content/zh/docs/web_ui/images/iam/project1.png
  content/zh/docs/web_ui/images/network/lb.png
  content/zh/docs/web_ui/images/storage/bucket.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/network/lb/lb.md
  content/zh/docs/web_ui/storage/bucket.md
Labels: size/L

#946 feat:3.9文档、全局设置、费用总览、多维度分析、多云管理资源支持表更新
  content/zh/docs/web_ui/cost/analysis/billaccount.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billstatistics.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/cost/analysis/billtime.md
  content/zh/docs/web_ui/cost/billoverview.md
  content/zh/docs/web_ui/images/bill/account.png
  content/zh/docs/web_ui/images/bill/account1.png
  content/zh/docs/web_ui/images/bill/analysis1.png
  content/zh/docs/web_ui/images/bill/billdomain.png
  content/zh/docs/web_ui/images/bill/billdomain1.png
  content/zh/docs/web_ui/images/bill/billoverview.png
  content/zh/docs/web_ui/images/bill/billproject.png
  content/zh/docs/web_ui/images/bill/billproject1.png
  content/zh/docs/web_ui/images/bill/billresourcetype.png
  content/zh/docs/web_ui/images/bill/billresourcetype1.png
  content/zh/docs/web_ui/images/bill/billtag.png
  content/zh/docs/web_ui/images/bill/billtag1.png
  content/zh/docs/web_ui/images/bill/billtime.png
  content/zh/docs/web_ui/images/bill/billtime1.png
  content/zh/docs/web_ui/images/bill/platform.png
  content/zh/docs/web_ui/images/bill/platform1.png
  content/zh/docs/web_ui/images/system/globalsetting.png
  content/zh/docs/web_ui/images/system/globalsetting1.png
  content/zh/docs/web_ui/images/system/globalsetting2.png
  content/zh/docs/web_ui/images/system/globalsetting3.png
  content/zh/docs/web_ui/images/system/globalsetting4.png
  content/zh/docs/web_ui/images/system/globalsetting5.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/L

#947 fix: add webhook docs
  content/zh/docs/development/webhook.md
  content/zh/docs/setup/repo.md
  content/zh/docs/setup/update_kernel.md
  content/zh/docs/setup/upgrade.md
Labels: size/L

#948 Automated cherry pick of #947: fix: add webhook docs
  content/zh/docs/development/webhook.md
  content/zh/docs/setup/repo.md
  content/zh/docs/setup/update_kernel.md
  content/zh/docs/setup/upgrade.md
Labels: size/L

#949 Automated cherry pick of #946: feat:3.9文档、全局设置、费用总览、多维度分析、多云管理资源支持表更新
  content/zh/docs/web_ui/cost/analysis/billaccount.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billstatistics.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/cost/analysis/billtime.md
  content/zh/docs/web_ui/cost/billoverview.md
  content/zh/docs/web_ui/images/bill/account.png
  content/zh/docs/web_ui/images/bill/account1.png
  content/zh/docs/web_ui/images/bill/analysis1.png
  content/zh/docs/web_ui/images/bill/billdomain.png
  content/zh/docs/web_ui/images/bill/billdomain1.png
  content/zh/docs/web_ui/images/bill/billoverview.png
  content/zh/docs/web_ui/images/bill/billproject.png
  content/zh/docs/web_ui/images/bill/billproject1.png
  content/zh/docs/web_ui/images/bill/billresourcetype.png
  content/zh/docs/web_ui/images/bill/billresourcetype1.png
  content/zh/docs/web_ui/images/bill/billtag.png
  content/zh/docs/web_ui/images/bill/billtag1.png
  content/zh/docs/web_ui/images/bill/billtime.png
  content/zh/docs/web_ui/images/bill/billtime1.png
  content/zh/docs/web_ui/images/bill/platform.png
  content/zh/docs/web_ui/images/bill/platform1.png
  content/zh/docs/web_ui/images/system/globalsetting.png
  content/zh/docs/web_ui/images/system/globalsetting1.png
  content/zh/docs/web_ui/images/system/globalsetting2.png
  content/zh/docs/web_ui/images/system/globalsetting3.png
  content/zh/docs/web_ui/images/system/globalsetting4.png
  content/zh/docs/web_ui/images/system/globalsetting5.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/L

#950 fix: repo url typo
  content/zh/docs/setup/repo.md
Labels: size/XS

#951 Automated cherry pick of #950: fix: repo url typo
  content/zh/docs/setup/repo.md
Labels: size/XS

#953 Automated cherry pick of #952: feature: about oc
  content/zh/docs/setup/oc-update.md
Labels: size/L

#954 fix: hide lastmod git info
  layouts/_default/content.html
  layouts/docs/list.html
Labels: size/XS

#956 Create add-api.md
  content/zh/docs/development/add-api.md
Labels: lgtm, size/L

#957 feat(3.9):vpc互联、vpc对等连接、多云管理所有新建云账号步骤完善、错误修改
  content/zh/docs/web_ui/images/network/linkvpc1.png
  content/zh/docs/web_ui/images/network/peerlinkvpc1.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/network/basicnetwork/linkvpc.md
  content/zh/docs/web_ui/network/basicnetwork/peerlinkvpc.md
Labels: size/L

#959 feat(3.9):开源版发布日志、changelog完善至v3.9.1,新增网络-路由表
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/release/v3_7_6.md
  content/zh/docs/release/v3_7_7.md
  content/zh/docs/release/v3_8_10.md
  content/zh/docs/release/v3_8_11.md
  content/zh/docs/release/v3_8_12.md
  content/zh/docs/release/v3_8_3.md
  content/zh/docs/release/v3_8_4.md
  content/zh/docs/release/v3_8_5.md
  content/zh/docs/release/v3_8_6.md
  content/zh/docs/release/v3_8_7.md
  content/zh/docs/release/v3_8_8.md
  content/zh/docs/release/v3_9_1.md
  content/zh/docs/web_ui/images/network/routetable.png
  content/zh/docs/web_ui/network/basicnetwork/routetable.md
Labels: size/L

#963 feat: use helm deploy CMP
  content/zh/docs/quickstart/k8s.md
Labels: size/L

#964 Automated cherry pick of #963: feat: use helm deploy CMP
  content/zh/docs/quickstart/k8s.md
Labels: size/L

#958 对 proxmox 开发接口一些补充
  content/zh/docs/development/proxmox-support.md
Labels: size/M

#966 feat(3.9):licenses
  content/zh/docs/quickuse/quickstart/_index.md
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/quickuse/quickstart/ldp.md
  content/zh/docs/quickuse/quickstart/licenses.md
  content/zh/docs/quickuse/quickstart/project.md
Labels: size/L

#968 feature: add service configuration docs
  content/zh/docs/function_principle/misc/configuration.md
Labels: size/L

#969 Automated cherry pick of #968: feature: add service configuration docs
  content/zh/docs/function_principle/misc/configuration.md
Labels: size/L

#970 misc: remove development content about telepresence
  content/zh/docs/development/dev-env.md
Labels: size/L

#971 Automated cherry pick of #970: misc: remove development content about telepresence
  content/zh/docs/development/dev-env.md
Labels: size/L

#972 feat(3.9):商业版导航栏说明、20多处文档内部链接失效问题修复
  content/zh/docs/development/dev-env.md
  content/zh/docs/faq/others.md
  content/zh/docs/faq/setup.md
  content/zh/docs/function_principle/misc/configuration.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/delete_failed.md
  content/zh/docs/introduce/intro/common/import.md
  content/zh/docs/introduce/intro/ui/cloudshell.md
  content/zh/docs/introduce/intro/ui/userinfo/cloudsso.md
  content/zh/docs/ops/climc/usage.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/upgrade.md
  content/zh/docs/web_ui/images/intro/alert1.png
  content/zh/docs/web_ui/images/intro/alert2.png
  content/zh/docs/web_ui/images/intro/cloudshellui.png
  content/zh/docs/web_ui/images/intro/fold.png
  content/zh/docs/web_ui/images/intro/ui.png
  content/zh/docs/web_ui/images/intro/ui1.png
  content/zh/docs/web_ui/images/intro/unfold.png
  content/zh/docs/web_ui/intro.md
Labels: size/L

#973 Automated cherry pick of #972: feat(3.9):商业版导航栏说明、20多处文档内部链接失效问题修复
  content/zh/docs/development/dev-env.md
  content/zh/docs/faq/others.md
  content/zh/docs/faq/setup.md
  content/zh/docs/function_principle/misc/configuration.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/delete_failed.md
  content/zh/docs/introduce/intro/common/import.md
  content/zh/docs/introduce/intro/ui/cloudshell.md
  content/zh/docs/introduce/intro/ui/userinfo/cloudsso.md
  content/zh/docs/ops/climc/usage.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/upgrade.md
  content/zh/docs/web_ui/images/intro/alert1.png
  content/zh/docs/web_ui/images/intro/alert2.png
  content/zh/docs/web_ui/images/intro/cloudshellui.png
  content/zh/docs/web_ui/images/intro/fold.png
  content/zh/docs/web_ui/images/intro/ui.png
  content/zh/docs/web_ui/images/intro/ui1.png
  content/zh/docs/web_ui/images/intro/unfold.png
  content/zh/docs/web_ui/intro.md
Labels: size/L

#975 feat: release v3.9.2
  Makefile
  content/en/docs/changelog/_index.md
  content/en/docs/changelog/release-3.8/3-8-14.md
  content/en/docs/changelog/release-3.8/3-8-15.md
  content/en/docs/changelog/release-3.8/_index.md
  content/en/docs/changelog/release-3.9/3-9-0.md
  content/en/docs/changelog/release-3.9/3-9-1.md
  content/en/docs/changelog/release-3.9/3-9-2.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.8/3-8-15.md
  content/zh/docs/development/changelog/release-3.8/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-2.md
  content/zh/docs/development/changelog/release-3.9/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/quickstart/nodes.md
Labels: size/XXL

#976 Automated cherry pick of #975: feat: release v3.9.2
  Makefile
  content/en/docs/changelog/_index.md
  content/en/docs/changelog/release-3.8/3-8-14.md
  content/en/docs/changelog/release-3.8/3-8-15.md
  content/en/docs/changelog/release-3.8/_index.md
  content/en/docs/changelog/release-3.9/3-9-0.md
  content/en/docs/changelog/release-3.9/3-9-1.md
  content/en/docs/changelog/release-3.9/3-9-2.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.8/3-8-15.md
  content/zh/docs/development/changelog/release-3.8/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-2.md
  content/zh/docs/development/changelog/release-3.9/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/quickstart/nodes.md
Labels: size/XXL

#977 fix: add yunionconf
  content/zh/docs/development/single_service_dev.md
Labels: size/M

#978 Automated cherry pick of #977: fix: add yunionconf
  content/zh/docs/development/single_service_dev.md
Labels: size/M

#983 feat(3.9):失效内部引用链接15个已全部修改，新增表格存储、流量镜像目录
  content/zh/docs/development/add-api.md
  content/zh/docs/development/apisdk/01_api.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/delete_failed.md
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/function_principle/onpremise/vminstance/create.md
  content/zh/docs/quickuse/feature/cost.md
  content/zh/docs/quickuse/feature/iam.md
  content/zh/docs/quickuse/feature/multicloud.md
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/quickuse/quickstart/ldp.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/web_ui/computing/network/_index.md
  content/zh/docs/web_ui/computing/network/eip.md
  content/zh/docs/web_ui/computing/network/trafficimages.md
  content/zh/docs/web_ui/images/computing/trafficimages.png
  content/zh/docs/web_ui/images/storage/table.png
  content/zh/docs/web_ui/storage/nas/_index.md
  content/zh/docs/web_ui/storage/table.md
Labels: size/L

#985 Automated cherry pick of #983: feat(3.9):失效内部引用链接15个已全部修改，新增表格存储、流量镜像目录
  content/zh/docs/development/add-api.md
  content/zh/docs/development/apisdk/01_api.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/delete_failed.md
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/function_principle/onpremise/vminstance/create.md
  content/zh/docs/quickuse/feature/cost.md
  content/zh/docs/quickuse/feature/iam.md
  content/zh/docs/quickuse/feature/multicloud.md
  content/zh/docs/quickuse/quickstart/account.md
  content/zh/docs/quickuse/quickstart/ldp.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/web_ui/computing/network/_index.md
  content/zh/docs/web_ui/computing/network/eip.md
  content/zh/docs/web_ui/computing/network/trafficimages.md
  content/zh/docs/web_ui/images/computing/trafficimages.png
  content/zh/docs/web_ui/images/storage/table.png
  content/zh/docs/web_ui/storage/nas/_index.md
  content/zh/docs/web_ui/storage/table.md
Labels: size/L

#987 misc 20220916-22
  content/zh/docs/function_principle/misc/configuration.md
  content/zh/docs/quickstart/_index.md
Labels: size/XS

#989 feat: let version as params
  config-ee.toml
  config.toml
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/ha-ce.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/upgrade.md
  layouts/shortcodes/pre_release_version.html
  layouts/shortcodes/release_branch.html
  layouts/shortcodes/release_version.html
Labels: size/M

#990 Automated cherry pick of #989: feat: let version as params
  config-ee.toml
  config.toml
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/ha-ce.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/upgrade.md
  layouts/shortcodes/pre_release_version.html
  layouts/shortcodes/release_branch.html
  layouts/shortcodes/release_version.html
Labels: size/M

#994 fix: 修复文档样式
  assets/scss/section-index.scss
  config.toml
  content/en/docs/_index.md
  content/en/docs/changelog/_index.md
  content/en/docs/contact/_index.md
  content/en/docs/contribute/_index.md
  content/en/docs/quickstart/_index.md
  content/en/docs/roadmap/_index.md
  content/en/docs/setup/_index.md
  content/zh/docs/_index.md
  content/zh/docs/contact/_index.md
  content/zh/docs/development/_index.md
  content/zh/docs/function_principle/_index.md
  content/zh/docs/introduce/_index.md
  content/zh/docs/ops/_index.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/release/_index.md
  content/zh/docs/setup/_index.md
  layouts/docs/list.html
  layouts/partials/index-guide.html
  package.json
  static/images/icons/icon-contact.svg
  static/images/icons/icon-function-principle.svg
  static/images/icons/icon-introduce.svg
  static/images/icons/icon-ops.svg
  static/images/icons/icon-quickstart.svg
  static/images/icons/icon-release.svg
  static/images/icons/icon-setup.svg
Labels: size/L

#996 fix: 文档首页样式优化
  layouts/docs/list.html
Labels: size/XS

#997 Automated cherry pick of #996: fix: 文档首页样式优化
  layouts/docs/list.html
Labels: size/XS

#991 fix: add sku service
  content/zh/docs/development/single_service_dev.md
Labels: size/S

#992 Automated cherry pick of #991: fix: add sku service
  content/zh/docs/development/single_service_dev.md
Labels: size/S

#993 feat(3.9):开源changelogv3.9.2、ipv6、备份存储、日志管理、命令记录菜单补充
  content/zh/docs/release/v3_9_2.md
  content/zh/docs/web_ui/images/network/ipv6.png
  content/zh/docs/web_ui/images/storage/backup.png
  content/zh/docs/web_ui/images/system/commandrecord.png
  content/zh/docs/web_ui/images/system/logmanage.png
  content/zh/docs/web_ui/network/networkservice/ipv6.md
  content/zh/docs/web_ui/storage/backup.md
  content/zh/docs/web_ui/systemconfig/log/cloudevent.md
  content/zh/docs/web_ui/systemconfig/log/commandrecord.md
  content/zh/docs/web_ui/systemconfig/log/logmanage.md
Labels: size/L

#999 fix: 首页图片路径修复
  content/zh/docs/release/_index.md
  layouts/partials/index-guide.html
Labels: size/S

#1000 Automated cherry pick of #999: fix: 首页图片路径修复
  content/zh/docs/release/_index.md
  layouts/partials/index-guide.html
Labels: size/S

#1001 updates 20220919
  content/zh/docs/_index.md
  content/zh/docs/function_principle/onpremise/baremetal/testcase.md
  content/zh/docs/setup/behindnginx.md
  content/zh/docs/setup/db-record-consistency.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/oc-update.md
  content/zh/docs/setup/repo.md
  content/zh/docs/setup/traefik-mutual-tls.md
Labels: size/M

#1002 Automated cherry pick of #1001: updates 20220919
  content/zh/docs/_index.md
  content/zh/docs/function_principle/onpremise/baremetal/testcase.md
  content/zh/docs/setup/behindnginx.md
  content/zh/docs/setup/db-record-consistency.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/oc-update.md
  content/zh/docs/setup/repo.md
  content/zh/docs/setup/traefik-mutual-tls.md
Labels: size/M

#1003 fix: 图标路径修复
  layouts/partials/index-guide.html
Labels: size/S

#1004 Automated cherry pick of #1003: fix: 图标路径修复
  layouts/partials/index-guide.html
Labels: size/S

#1006 Update create.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/S

#1011 fix: faq for vm sync
  content/zh/docs/faq/image/cloudprovider_disabled.png
  content/zh/docs/faq/image/cloudprovider_region_disabled.png
  content/zh/docs/faq/image/lake_of_permission.png
  content/zh/docs/faq/sync.md
Labels: size/M

#1012 Automated cherry pick of #1011: fix: faq for vm sync
  content/zh/docs/faq/image/cloudprovider_disabled.png
  content/zh/docs/faq/image/cloudprovider_region_disabled.png
  content/zh/docs/faq/image/lake_of_permission.png
  content/zh/docs/faq/sync.md
Labels: size/M

#1010 宿主机添加块存储后要同时重启host和host-image服务
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1015 Automated cherry pick of #1010: Update heterresource.md
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1013 fix: host vlan extended
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/quickstart/allinone.md
Labels: size/M

#1014 Automated cherry pick of #1013: fix: host vlan extended
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/quickstart/allinone.md
Labels: size/M

#1016 fix: update logs splitable
  content/zh/docs/ops/images/deletelogtable2.png
  content/zh/docs/ops/images/logtable2.png
  content/zh/docs/ops/log.md
Labels: size/S

#1017 Automated cherry pick of #1016: fix: update logs splitable
  content/zh/docs/ops/images/deletelogtable2.png
  content/zh/docs/ops/images/logtable2.png
  content/zh/docs/ops/log.md
Labels: size/S

#1019 feat(dev): monitor setup docs
  content/zh/docs/development/single_service_dev.md
Labels: size/M

#1018 docs: host auto migrate on host down
  content/zh/docs/function_principle/onpremise/host/auto-migrate-on-hostdown.md
Labels: size/M

#1021 Automated cherry pick of #1018: docs: host auto migrate on host down
  content/zh/docs/function_principle/onpremise/host/auto-migrate-on-hostdown.md
Labels: size/M

#1023 Automated cherry pick of #1022: minor fixes
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1022 minor fixes
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1026 Secgroup principle
  content/zh/docs/function_principle/multicloud/compute/_index.md
  content/zh/docs/function_principle/multicloud/compute/disk/_index.md
  content/zh/docs/function_principle/multicloud/compute/image/_index.md
  content/zh/docs/function_principle/multicloud/compute/keypair/_index.md
  content/zh/docs/function_principle/multicloud/compute/scalinggroup/_index.md
  content/zh/docs/function_principle/multicloud/compute/secgroup/_index.md
  content/zh/docs/function_principle/multicloud/compute/secgroup/principle.md
  content/zh/docs/function_principle/multicloud/compute/sku/_index.md
  content/zh/docs/function_principle/multicloud/compute/template/_index.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/_index.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/common_failed.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/create_failed.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/images/no_region.png
  content/zh/docs/function_principle/multicloud/compute/vminstance/images/vm_log.png
  content/zh/docs/function_principle/multicloud/compute/vminstance/no_region.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/reset_password.md
  content/zh/docs/function_principle/multicloud/compute/webapp/_index.md
  content/zh/docs/function_principle/multicloud/compute/webapp/principle.md
Labels: size/L

#1027 Automated cherry pick of #1026: fix: add secgroup cache principle
  content/zh/docs/function_principle/multicloud/compute/_index.md
  content/zh/docs/function_principle/multicloud/compute/disk/_index.md
  content/zh/docs/function_principle/multicloud/compute/image/_index.md
  content/zh/docs/function_principle/multicloud/compute/keypair/_index.md
  content/zh/docs/function_principle/multicloud/compute/scalinggroup/_index.md
  content/zh/docs/function_principle/multicloud/compute/secgroup/_index.md
  content/zh/docs/function_principle/multicloud/compute/secgroup/principle.md
  content/zh/docs/function_principle/multicloud/compute/sku/_index.md
  content/zh/docs/function_principle/multicloud/compute/template/_index.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/_index.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/common_failed.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/create_failed.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/images/no_region.png
  content/zh/docs/function_principle/multicloud/compute/vminstance/images/vm_log.png
  content/zh/docs/function_principle/multicloud/compute/vminstance/no_region.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/reset_password.md
  content/zh/docs/function_principle/multicloud/compute/webapp/_index.md
  content/zh/docs/function_principle/multicloud/compute/webapp/principle.md
Labels: size/L

#1024 feat(3.9):开源常用镜像添加
  content/zh/docs/function_principle/onpremise/glance/common.md
Labels: size/S

#1028 Automated cherry pick of #1024: feat(3.9):开源常用镜像添加
  content/zh/docs/function_principle/onpremise/glance/common.md
Labels: size/S

#1025 fix: add remote file desc
  content/zh/docs/faq/cloudaccount/remotefile.md
Labels: size/L

#1029 fix: add multiqueue docs
  content/zh/docs/function_principle/onpremise/network/configuration.md
  content/zh/docs/function_principle/onpremise/network/multiqueue.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcvip.md
Labels: size/M

#1030 Automated cherry pick of #1029: fix: add multiqueue docs
  content/zh/docs/function_principle/onpremise/network/configuration.md
  content/zh/docs/function_principle/onpremise/network/multiqueue.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcvip.md
Labels: size/M

#1031 docs(ansible,python3): 更新安装文档中,关于Python3/ansible的安装命令
  content/en/docs/quickstart/allinone.md
  content/en/docs/setup/upgrade.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/backup.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#1032 Automated cherry pick of #1031: docs(ansible,python3): 更新安装文档中,关于Python3/ansible的安装命令
  content/en/docs/quickstart/allinone.md
  content/en/docs/setup/upgrade.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/backup.md
  content/zh/docs/setup/upgrade.md
Labels: size/M
