Repository yunionio/docs, pull requests merged in 2022-06, with the labels that each got.

#836 fix: nginx conf
  content/zh/docs/development/single_service_dev.md
Labels: size/S

#837 Automated cherry pick of #836: fix: nginx conf
  content/zh/docs/development/single_service_dev.md
Labels: size/S

#838 fix: more details on api framework
  content/zh/docs/development/framework.md
Labels: size/M

#839 Automated cherry pick of #838: fix: more details on api framework
  content/zh/docs/development/framework.md
Labels: size/M

#840 feat(3.9) 只读模式&虚拟机添加透传设备页签
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/readonly.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/show.md
  content/zh/docs/onpremise/vminstance/tutorial/show/passthrough.md
Labels: size/M

#842 feat(3.8) 补充京东云账号新建的内容
  content/zh/docs/multicloud/cloudaccounts/images/jdak.png
  content/zh/docs/multicloud/cloudaccounts/images/jdaksk.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/aksk.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
Labels: size/M

#848 feature: add docs for apigateway endpoint
  content/zh/docs/apisdk/01_apigateway.md
Labels: size/M

#846 fix: add docs on service config
  content/zh/docs/auth_security/iam/images/oidc_procedures.png
  content/zh/docs/auth_security/iam/principle/_index.md
  content/zh/docs/auth_security/iam/principle/serviceconfig.md
  content/zh/docs/auth_security/iam/tutorial/idp/oidc_idp.md
Labels: size/L

#851 fix: dead link of development content
  content/zh/docs/development/framework.md
Labels: size/XS

#852 Automated cherry pick of #851: fix: dead link of development content
  content/zh/docs/development/framework.md
Labels: size/XS

#844 feat(3.9) 增加集群监控以及支持同步的公有云集群信息
  content/zh/docs/auth_security/security/_index.md
  content/zh/docs/auth_security/security/tutorial/config.md
  content/zh/docs/auth_security/security/tutorial/list.md
  content/zh/docs/k8s/_index.md
  content/zh/docs/k8s/monitor.md
  content/zh/docs/meter_billing/multi-analysis/tutorial/view.md
  content/zh/docs/multicloud/db/rds/tutorial/_index.md
Labels: size/M

#845 feat: #3765 文档配色兼容开源商业
  assets/scss/_variables_project.scss
  layouts/docs/baseof.html
  layouts/partials/navbar.html
  static/css/global.css
Labels: size/L

#855 feat(3.9) roadmap update
  content/zh/docs/release/v3_8_11.md
Labels: size/S

#858 fix(baremetal): server-create options
  content/zh/docs/onpremise/baremetal/tutorial/create_server.md
Labels: size/XS

#859 Automated cherry pick of #858: fix(baremetal): server-create options
  content/zh/docs/onpremise/baremetal/tutorial/create_server.md
Labels: size/XS

#857 add Q&A
  content/zh/docs/qa/_index.md
Labels: size/M

#862 Automated cherry pick of #857: add Q&A
  content/zh/docs/qa/_index.md
Labels: size/M

#864 update 3.8.12
  content/zh/docs/release/v3_8_12.md
Labels: size/M

#865 fix: hugo compilation error
  config.toml
  scripts/build.py
Labels: size/S

#867 feat(allinone): tips for pure OS
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#869 fix: kubeadm reset -f
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#871 feat(monitor): alert migration
  content/zh/docs/monitor_ops/monitor/tutorial/auto_migration.md
Labels: size/L
