Repository yunionio/docs, pull requests merged in 2022-08, with the labels that each got.

#897 release 3.8.14
  content/zh/docs/changelog/release-3.8/3-8-14.md
  content/zh/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.9/3-9-0.md
  content/zh/docs/changelog/release-3.9/3-9-1.md
  content/zh/docs/changelog/release-3.9/_index.md
Labels: size/L

#898 Automated cherry pick of #897: release 3.8.14
  content/zh/docs/changelog/release-3.8/3-8-14.md
  content/zh/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.9/3-9-0.md
  content/zh/docs/changelog/release-3.9/3-9-1.md
  content/zh/docs/changelog/release-3.9/_index.md
Labels: size/L

#905 Automated cherry pick of #903: fix: dev content not rendored
  content/zh/docs/development/dev-env.md
Labels: size/S

#906 fix: add go spec
  content/zh/docs/development/specification.md
Labels: size/L

#907 Automated cherry pick of #906: fix: add go spec
  content/zh/docs/development/specification.md
Labels: size/L

#909 fix: update license v4 docs 2022/8/15
  content/zh/docs/introduce/intro/ui/more/licenses.md
Labels: size/M

#910 Automated cherry pick of #909: fix: update license v4 docs 2022/8/15
  content/zh/docs/introduce/intro/ui/more/licenses.md
Labels: size/M

#908 add docs reserve cpus
  content/zh/docs/onpremise/host/tutorial/reservecpus.md
Labels: size/M

#911 Automated cherry pick of #908: add docs reserve cpus
  content/zh/docs/onpremise/host/tutorial/reservecpus.md
Labels: size/M

#912 fix: skip server sync
  content/zh/docs/multicloud/cloudaccounts/faq/sync.md
Labels: size/XS

#913 Automated cherry pick of #912: fix: skip server sync
  content/zh/docs/multicloud/cloudaccounts/faq/sync.md
Labels: size/XS

#915 feat(content): feature-config docs
  content/zh/docs/setup/feature-config.md
Labels: size/L

#914 extra-search-docExtra search
  content/zh/docs/development/extra-order.md
  content/zh/docs/development/git-convention.md
Labels: size/M

#918 feature: com passthrough
  content/zh/docs/onpremise/vminstance/tutorial/com-passthrough.md
Labels: size/M

#919 Automated cherry pick of #918: feature: com passthrough
  content/zh/docs/onpremise/vminstance/tutorial/com-passthrough.md
Labels: size/M

#920 fix: update feature config
  content/zh/docs/setup/feature-config.md
Labels: size/M

#921 Automated cherry pick of #920: fix: update feature config
  content/zh/docs/setup/feature-config.md
Labels: size/M

#924 fix: hugo make local serve all ips
  Makefile
Labels: size/XS

#922 add qga docs
  content/zh/docs/onpremise/vminstance/tutorial/qga.md
Labels: size/L

#923 fix: add secgroup cache principle
  content/zh/docs/multicloud/compute/secgroup/principle/_index.md
Labels: size/M

#925 Automated cherry pick of #922: add qga docs
  content/zh/docs/onpremise/vminstance/tutorial/qga.md
Labels: size/L

#926 Automated cherry pick of #923: fix: add secgroup cache principle
  content/zh/docs/multicloud/compute/secgroup/principle/_index.md
Labels: size/M

#931 feat: ce-local-serve
  Makefile
Labels: size/XS

#934 fix: intro of changing usb controller
  content/zh/docs/function_principle/onpremise/vminstance/usb-passthrough.md
  content/zh/docs/introduce/intro/tenant.md
  layouts/docs/baseof.html
  layouts/partials/navbar.html
Labels: size/S

#935 Automated cherry pick of #934: fix: intro of changing usb controller
  content/zh/docs/function_principle/onpremise/vminstance/usb-passthrough.md
  content/zh/docs/introduce/intro/tenant.md
  layouts/docs/baseof.html
  layouts/partials/navbar.html
Labels: size/S

#936 fix: ensure base_url end with '/'
  scripts/builder/hugo.py
Labels: size/XS
