Repository yunionio/docs, pull requests merged in 2022-02, with the labels that each got.

#675 fix: sky computing blog add reference
  content/zh/blog/_posts/2022-01-21-skycomputing/index.md
Labels: size/XS

#676 Automated cherry pick of #675: fix: sky computing blog add reference
  content/zh/blog/_posts/2022-01-21-skycomputing/index.md
Labels: size/XS

#677 feature: add blog cloudpods golang
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/01-cloudpods-arch.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/02-golang-framework.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/03-keystone.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/04-crud.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/05-model-manager.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/06-api-model-methods.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/07-encoding-json.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/08-jsonutils.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/09-jsonutils-deprecated.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/10-sqlchemy.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/11-sqlchemy-query.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/12-structarg.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/13-pkg.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/index.md
Labels: size/L

#678 Automated cherry pick of #677: feature: add blog cloudpods golang
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/01-cloudpods-arch.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/02-golang-framework.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/03-keystone.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/04-crud.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/05-model-manager.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/06-api-model-methods.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/07-encoding-json.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/08-jsonutils.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/09-jsonutils-deprecated.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/10-sqlchemy.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/11-sqlchemy-query.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/12-structarg.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/13-pkg.png
  content/zh/blog/_posts/2022-02-02-cloudpods-golang/index.md
Labels: size/L

#679 feature: hugepage
  content/zh/docs/onpremise/vminstance/tutorial/hugepage.md
  content/zh/docs/onpremise/vminstance/tutorial/usb.md
Labels: size/M

#680 Automated cherry pick of #679: feature: hugepage
  content/zh/docs/onpremise/vminstance/tutorial/hugepage.md
  content/zh/docs/onpremise/vminstance/tutorial/usb.md
Labels: size/M

#682 Automated cherry pick of #681: fix: security
  content/zh/docs/architecture/security.md
Labels: size/S

#684 Automated cherry pick of #683: fix: relref edition ee
  content/zh/docs/meter_billing/conversion/tutorial/_index.md
  content/zh/docs/meter_billing/exchange/_index.md
  content/zh/docs/meter_billing/exchange/tutorial/_index.md
  content/zh/docs/meter_billing/overview/tutorial/switch.md
  content/zh/docs/misc/globalsetting/tutorial/bill.md
Labels: size/XS

#687 fix edition:ee display
  content/zh/docs/misc/ticket/tutorial/_index.md
  content/zh/docs/misc/ticket/tutorial/approval/_index.md
  content/zh/docs/misc/ticket/tutorial/common/_index.md
  content/zh/docs/misc/ticket/tutorial/support/_index.md
  content/zh/docs/misc/ticket/tutorial/third/_index.md
  content/zh/docs/misc/uipolicy/tutorial/allocation/_index.md
  content/zh/docs/misc/uipolicy/tutorial/definition/_index.md
Labels: size/XS

#688 Automated cherry pick of #687: fix edition:ee display
  content/zh/docs/misc/ticket/tutorial/_index.md
  content/zh/docs/misc/ticket/tutorial/approval/_index.md
  content/zh/docs/misc/ticket/tutorial/common/_index.md
  content/zh/docs/misc/ticket/tutorial/support/_index.md
  content/zh/docs/misc/ticket/tutorial/third/_index.md
  content/zh/docs/misc/uipolicy/tutorial/allocation/_index.md
  content/zh/docs/misc/uipolicy/tutorial/definition/_index.md
Labels: size/XS

#691 fix typo
  content/zh/docs/auth_security/iam/principle/_index.md
Labels: size/XS

#695 Automated cherry pick of #691: fix typo
  content/zh/docs/auth_security/iam/principle/_index.md
Labels: size/XS

#693 fix: add ceph doc
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
Labels: size/XS

#694 Automated cherry pick of #693: fix: add ceph doc
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
Labels: size/XS

#697 feat(3.8)Nutanix&硬盘/主机备份恢复
  content/zh/docs/meter_billing/billrate/tutorial/_index.md
  content/zh/docs/misc/globalsetting/tutorial/kvm.md
  content/zh/docs/multicloud/_index.md
  content/zh/docs/multicloud/cloudaccounts/images/azurecreateapi.png
  content/zh/docs/multicloud/cloudaccounts/images/azurecreateapi1.png
  content/zh/docs/multicloud/cloudaccounts/images/azurerequestapi.png
  content/zh/docs/multicloud/cloudaccounts/images/azurerequestapi1.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaddaksk.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaksk.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaksklist.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/aksk.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/aksk_grant.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/connect.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/image/save_private.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/bindkeypair.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/reset.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/unbindkeypair.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/network/bindeip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/network/unbindeip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/rebuild.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/sameconfig.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/snapshot.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/show/eip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/show/network.md
  content/zh/docs/onpremise/backup/_index.md
  content/zh/docs/onpremise/backup/faq/_index.md
  content/zh/docs/onpremise/backup/principle/_index.md
  content/zh/docs/onpremise/backup/tutorial/_index.md
  content/zh/docs/onpremise/backup/tutorial/disk/_index.md
  content/zh/docs/onpremise/backup/tutorial/disk/create.md
  content/zh/docs/onpremise/backup/tutorial/disk/delete.md
  content/zh/docs/onpremise/backup/tutorial/disk/log.md
  content/zh/docs/onpremise/backup/tutorial/disk/recover.md
  content/zh/docs/onpremise/backup/tutorial/disk/show.md
  content/zh/docs/onpremise/backup/tutorial/disk/sync.md
  content/zh/docs/onpremise/backup/tutorial/vm/_index.md
  content/zh/docs/onpremise/backup/tutorial/vm/create.md
  content/zh/docs/onpremise/backup/tutorial/vm/delete.md
  content/zh/docs/onpremise/backup/tutorial/vm/log.md
  content/zh/docs/onpremise/backup/tutorial/vm/recover.md
  content/zh/docs/onpremise/backup/tutorial/vm/show.md
  content/zh/docs/onpremise/backup/tutorial/vm/sync.md
  content/zh/docs/onpremise/vminstance/tutorial/show/eip.md
  content/zh/docs/onpremise/vminstance/tutorial/show/network.md
Labels: size/L

#698 Automated cherry pick of #697: feat(3.8)Nutanix&硬盘/主机备份恢复
  content/zh/docs/meter_billing/billrate/tutorial/_index.md
  content/zh/docs/misc/globalsetting/tutorial/kvm.md
  content/zh/docs/multicloud/_index.md
  content/zh/docs/multicloud/cloudaccounts/images/azurecreateapi.png
  content/zh/docs/multicloud/cloudaccounts/images/azurecreateapi1.png
  content/zh/docs/multicloud/cloudaccounts/images/azurerequestapi.png
  content/zh/docs/multicloud/cloudaccounts/images/azurerequestapi1.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaddaksk.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaksk.png
  content/zh/docs/multicloud/cloudaccounts/images/cloudpodsaksklist.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/aksk.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/aksk_grant.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/connect.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/image/save_private.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/bindkeypair.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/reset.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/keypair/unbindkeypair.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/network/bindeip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/network/unbindeip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/rebuild.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/sameconfig.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/setting/snapshot.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/show/eip.md
  content/zh/docs/multicloud/compute/vminstance/tutorial/show/network.md
  content/zh/docs/onpremise/backup/_index.md
  content/zh/docs/onpremise/backup/faq/_index.md
  content/zh/docs/onpremise/backup/principle/_index.md
  content/zh/docs/onpremise/backup/tutorial/_index.md
  content/zh/docs/onpremise/backup/tutorial/disk/_index.md
  content/zh/docs/onpremise/backup/tutorial/disk/create.md
  content/zh/docs/onpremise/backup/tutorial/disk/delete.md
  content/zh/docs/onpremise/backup/tutorial/disk/log.md
  content/zh/docs/onpremise/backup/tutorial/disk/recover.md
  content/zh/docs/onpremise/backup/tutorial/disk/show.md
  content/zh/docs/onpremise/backup/tutorial/disk/sync.md
  content/zh/docs/onpremise/backup/tutorial/vm/_index.md
  content/zh/docs/onpremise/backup/tutorial/vm/create.md
  content/zh/docs/onpremise/backup/tutorial/vm/delete.md
  content/zh/docs/onpremise/backup/tutorial/vm/log.md
  content/zh/docs/onpremise/backup/tutorial/vm/recover.md
  content/zh/docs/onpremise/backup/tutorial/vm/show.md
  content/zh/docs/onpremise/backup/tutorial/vm/sync.md
  content/zh/docs/onpremise/vminstance/tutorial/show/eip.md
  content/zh/docs/onpremise/vminstance/tutorial/show/network.md
Labels: size/L

#703 fix cloudaccout create docs
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
Labels: size/L

#704 Automated cherry pick of #703: fix cloudaccout create docs
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
Labels: size/L

#701 fix word
  content/zh/docs/multicloud/compute/image/tutorial/download.md
  content/zh/docs/multicloud/compute/image/tutorial/query.md
  content/zh/docs/multicloud/compute/image/tutorial/show.md
  content/zh/docs/multicloud/compute/image/tutorial/upload.md
  content/zh/docs/onpremise/image/tutorial/sysimage/download.md
  content/zh/docs/onpremise/image/tutorial/sysimage/query.md
  content/zh/docs/onpremise/image/tutorial/sysimage/show.md
  content/zh/docs/onpremise/image/tutorial/sysimage/upload.md
  content/zh/docs/onpremise/vminstance/tutorial/create.md
Labels: size/L

#702 Automated cherry pick of #701: fix word
  content/zh/docs/multicloud/compute/image/tutorial/download.md
  content/zh/docs/multicloud/compute/image/tutorial/query.md
  content/zh/docs/multicloud/compute/image/tutorial/show.md
  content/zh/docs/multicloud/compute/image/tutorial/upload.md
  content/zh/docs/onpremise/image/tutorial/sysimage/download.md
  content/zh/docs/onpremise/image/tutorial/sysimage/query.md
  content/zh/docs/onpremise/image/tutorial/sysimage/show.md
  content/zh/docs/onpremise/image/tutorial/sysimage/upload.md
  content/zh/docs/onpremise/vminstance/tutorial/create.md
Labels: size/L

#706 feat(changelog): update v3.8.7 changelog
  content/en/docs/changelog/release-3.8/3-8-7.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-7.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/XL

#707 Automated cherry pick of #706: feat(changelog): update v3.8.7 changelog
  content/en/docs/changelog/release-3.8/3-8-7.md
  content/en/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.8/3-8-7.md
  content/zh/docs/changelog/release-3.8/_index.md
Labels: size/XL

#709 feat(3.8) 费用模块内容优化
  content/zh/docs/auth_security/iam/tutorial/user/reset.md
  content/zh/docs/introduce/intro/common/common.md
  content/zh/docs/meter_billing/analysis/tutorial/account/cost.md
  content/zh/docs/meter_billing/analysis/tutorial/analysis/view.md
  content/zh/docs/meter_billing/analysis/tutorial/domain/show.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/view.md
  content/zh/docs/meter_billing/analysis/tutorial/project/show.md
  content/zh/docs/meter_billing/analysis/tutorial/resourcetype/show.md
  content/zh/docs/meter_billing/analysis/tutorial/tag/show.md
  content/zh/docs/meter_billing/analysis/tutorial/time/show.md
  content/zh/docs/meter_billing/bill/tutorial/instance/view.md
  content/zh/docs/meter_billing/bill/tutorial/resource/view.md
  content/zh/docs/meter_billing/dimension/tutorial/usage.md
  content/zh/docs/meter_billing/overview/tutorial/view.md
  content/zh/docs/onpremise/backup/_index.md
  content/zh/docs/onpremise/network/tutorial/default/viewvpc.md
  content/zh/docs/onpremise/network/tutorial/vpc/viewvpc.md
Labels: size/L

#710 Automated cherry pick of #709: feat(3.8) 费用模块内容优化
  content/zh/docs/auth_security/iam/tutorial/user/reset.md
  content/zh/docs/introduce/intro/common/common.md
  content/zh/docs/meter_billing/analysis/tutorial/account/cost.md
  content/zh/docs/meter_billing/analysis/tutorial/analysis/view.md
  content/zh/docs/meter_billing/analysis/tutorial/domain/show.md
  content/zh/docs/meter_billing/analysis/tutorial/platform/view.md
  content/zh/docs/meter_billing/analysis/tutorial/project/show.md
  content/zh/docs/meter_billing/analysis/tutorial/resourcetype/show.md
  content/zh/docs/meter_billing/analysis/tutorial/tag/show.md
  content/zh/docs/meter_billing/analysis/tutorial/time/show.md
  content/zh/docs/meter_billing/bill/tutorial/instance/view.md
  content/zh/docs/meter_billing/bill/tutorial/resource/view.md
  content/zh/docs/meter_billing/dimension/tutorial/usage.md
  content/zh/docs/meter_billing/overview/tutorial/view.md
  content/zh/docs/onpremise/backup/_index.md
  content/zh/docs/onpremise/network/tutorial/default/viewvpc.md
  content/zh/docs/onpremise/network/tutorial/vpc/viewvpc.md
Labels: size/L

#708 feat: add release note of v3.8.7
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/release/v3_8_7.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#715 feat(3.8)添加云上项目的内容
  content/zh/docs/multicloud/cloudaccounts/images/edit.png
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/switch.md
Labels: size/M

#716 Automated cherry pick of #715: feat(3.8)添加云上项目的内容
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/switch.md
Labels: size/M

#718 fix: add api doc
  content/zh/docs/apisdk/01_api.md
Labels: size/XXL

#719 Automated cherry pick of #718: fix: add api doc
  content/zh/docs/apisdk/01_api.md
Labels: size/XXL

#711 fix: climc help doc
  content/zh/docs/climc/usage.md
  content/zh/docs/multicloud/compute/image/tutorial/show.md
  content/zh/docs/multicloud/compute/image/tutorial/upload.md
  content/zh/docs/onpremise/image/tutorial/sysimage/show.md
  content/zh/docs/onpremise/image/tutorial/sysimage/upload.md
  content/zh/docs/onpremise/vminstance/faq/change_disk_driver.md
  content/zh/docs/onpremise/vminstance/tutorial/create.md
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
Labels: size/S

#714 feat(3.9)镜像缓存到存储
  content/zh/docs/multicloud/compute/image/tutorial/cache/create_private.md
  content/zh/docs/multicloud/compute/image/tutorial/cache/create_public.md
  content/zh/docs/onpremise/backup/_index.md
  content/zh/docs/onpremise/image/tutorial/sysimage/cache/_index.md
  content/zh/docs/onpremise/image/tutorial/sysimage/cache/create_idc.md
  content/zh/docs/onpremise/image/tutorial/sysimage/cache/delete.md
Labels: size/M

#717 feat(3.9) 迁移不检查内核版本
  content/zh/docs/onpremise/vminstance/tutorial/migrate.md
Labels: size/XS

#705 feat（3.9）云账号定时同步
  content/zh/docs/misc/dashboard/create.md
  content/zh/docs/misc/dashboard/modify.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/autosync/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/autosync/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/autosync/delete.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/autosync/enable.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/fullsync.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/region.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/sync/subscription.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/update_billing.md
  content/zh/docs/multicloud/compute/image/tutorial/download.md
  content/zh/docs/onpremise/image/tutorial/sysimage/download.md
Labels: size/L

#713 feat(3.9)更新SAML配置文档
  content/zh/docs/auth_security/iam/images/commonsamlentity.png
  content/zh/docs/auth_security/iam/images/commonsamlinfo.png
  content/zh/docs/auth_security/iam/images/commonsamlinfo1.png
  content/zh/docs/auth_security/iam/tutorial/idp/create_saml.md
Labels: size/S
