Repository yunionio/docs, pull requests merged in 2022-10, with the labels that each got.

#1035 修改错别字
  content/zh/docs/quickstart/k8s.md
Labels: size/XS

#1038 fix: apsara aksk
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1039 Automated cherry pick of #1038: fix: apsara aksk
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1040 feat(3.9):"块存储"、" Openstack 对接常见问题"、"创建页面无任何资源" 失效链接修复
  content/zh/docs/function_principle/multicloud/cloudaccounts/openstack.md
  content/zh/docs/function_principle/multicloud/compute/vminstance/no_region.md
  content/zh/docs/web_ui/storage/block.md
Labels: size/XS

#1043 Automated cherry pick of #1037: feat(3.9):all in one部署视频，主机-创建备份，主机-更换块存储，主机-绑定物理CPU，主机-快速恢复，主机-设置USB透传
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1047 fix: add AWS assume role doc
  content/zh/docs/development/apisdk/01_apigateway.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/aws.md
Labels: size/M

#1048 Automated cherry pick of #1047: fix: add AWS assume role doc
  content/zh/docs/development/apisdk/01_apigateway.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/aws.md
Labels: size/M

#1046 feat(3.9):新建华为云账号仅支持中国区类型
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1045 feat(master):ui策略定义新增隐藏实例账单列表项、隐藏资源账单列表项、隐藏流水账单列表项
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
Labels: size/XS

#1050 Automated cherry pick of #1046: feat(3.9):新建华为云账号仅支持中国区类型
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1049 Automated cherry pick of #1045: feat(master):ui策略定义新增隐藏实例账单列表项、隐藏资源账单列表项、隐藏流水账单列表项
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
Labels: size/XS

#1052 fix: docs on recycle_bin disk recover vm
  content/zh/docs/function_principle/onpremise/storage/blockstorage/recycle.md
Labels: size/S

#1053 Automated cherry pick of #1052: fix: docs on recycle_bin disk recover vm
  content/zh/docs/function_principle/onpremise/storage/blockstorage/recycle.md
Labels: size/S

#1051 feat(3.9):常用镜像新增、权限支持搜索新增、linux、windows安装agent说明、cpu、内存不限新增
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/iam/keystone/policy.md
Labels: size/S

#1054 Automated cherry pick of #1051: feat(3.9):常用镜像新增、权限支持搜索新增、linux、windows安装agent说明、cpu、内存不限新增
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/iam/keystone/policy.md
Labels: size/S

#1055 docs: guest migration
  content/zh/docs/function_principle/onpremise/vminstance/migrate.md
Labels: size/M

#1056 Automated cherry pick of #1055: docs: guest migration
  content/zh/docs/function_principle/onpremise/vminstance/migrate.md
Labels: size/M
