Repository yunionio/docs, pull requests merged in 2022-07, with the labels that each got.

#872 "feat(3.9)新建云上项目"
  content/zh/docs/multicloud/_index.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/create.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/cloudproject/switch.md
  content/zh/docs/multicloud/cloudaccounts/tutorial/readonly.md
Labels: size/M

#874 3.8更新配置需求
  content/zh/docs/setup/config.md
Labels: size/S

#876 feat: add icp link
  config.toml
  layouts/partials/footer.html
Labels: size/XS

#877 Automated cherry pick of #876: feat: add icp link
  config.toml
  layouts/partials/footer.html
Labels: size/XS

#878 Automated cherry pick of #877: feat: add icp link
  config.toml
  layouts/partials/footer.html
Labels: size/XS

#879 Automated cherry pick of #877: feat: add icp link
  config.toml
  layouts/partials/footer.html
Labels: size/XS

#875 misc fix
  content/zh/docs/development/single_service_dev.md
  content/zh/docs/multicloud/_index.md
  content/zh/docs/quickstart/allinone.md
Labels: size/M

#881 Automated cherry pick of #875: misc fix
  content/zh/docs/development/single_service_dev.md
  content/zh/docs/multicloud/_index.md
  content/zh/docs/quickstart/allinone.md
Labels: size/M

#885 feat: v3.9 change log
  content/zh/docs/changelog/release-3.8/3-8-13.md
  content/zh/docs/changelog/release-3.8/_index.md
  content/zh/docs/changelog/release-3.9/3-9-0.md
  content/zh/docs/changelog/release-3.9/3-9-1.md
  content/zh/docs/changelog/release-3.9/_index.md
Labels: size/XXL

#889 fix: update content to 3.9
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/quickstart/ha.md
  content/zh/docs/quickstart/nodes.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#883 cherry-pick-pull
  content/zh/docs/development/git-convention.md
  content/zh/docs/development/images/github_token_location.png
Labels: size/M

#882 add mac install docker step
  content/zh/docs/development/dev-env.md
Labels: size/S

#892 Automated cherry pick of #882: add mac install docker step
  content/zh/docs/development/dev-env.md
Labels: size/S

#893 fix(k8s): feature toggle
  content/zh/docs/k8s/_index.md
Labels: size/S

#895 k8s: content complement
  content/zh/docs/k8s/_index.md
Labels: size/XS
