Repository yunionio/docs, pull requests merged in 2023-06, with the labels that each got.

#1501 feat(3.10):3.10.2发布日志
  content/zh/docs/release/v3_10_2.md
Labels: size/M

#1502 Automated cherry pick of #1501: feat(3.10):3.10.2发布日志
  content/zh/docs/release/v3_10_2.md
Labels: size/M

#1497 move dev docs 20230530
  content/zh/docs/development/resource_sync/images/resource.png
  content/zh/docs/development/resource_sync/proxmox-support.md
  content/zh/docs/development/resource_sync/remotefile.md
Labels: size/XS

#1498 Automated cherry pick of #1497: move dev docs 20230530
  content/zh/docs/development/resource_sync/images/resource.png
  content/zh/docs/development/resource_sync/proxmox-support.md
  content/zh/docs/development/resource_sync/remotefile.md
Labels: size/XS

#1495 add blog
  content/zh/blog/_posts/2023-05-15-introduction-to-the-skypilot-open-source-project.md
  content/zh/blog/_posts/2023-05-23-refactoring-bash-scripts-to-comply-with-the-google-coding-style.md
Labels: size/L

#1496 Automated cherry pick of #1495: add blog
  content/zh/blog/_posts/2023-05-15-introduction-to-the-skypilot-open-source-project.md
  content/zh/blog/_posts/2023-05-23-refactoring-bash-scripts-to-comply-with-the-google-coding-style.md
Labels: size/L

#1505 fix: change swagger to apifox
  config.toml
Labels: size/XS

#1503 fix: windows time setting
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/S

#1504 Automated cherry pick of #1503: fix: windows time setting
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/S

#1511 fix: update log splitable cmd
  content/zh/docs/function_principle/misc/log/log-purge.md
Labels: size/S

#1512 Automated cherry pick of #1511: fix: update log splitable cmd
  content/zh/docs/function_principle/misc/log/log-purge.md
Labels: size/S

#1531 fix: add docs for device passthrough
  content/zh/docs/faq/network.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/_index.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/com-passthrough.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/gpu.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb-passthrough.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb.md
Labels: size/L

#1532 Automated cherry pick of #1531: fix: add docs for device passthrough
  content/zh/docs/faq/network.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/_index.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/com-passthrough.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/gpu.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb-passthrough.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb.md
Labels: size/L

#1533 Automated cherry pick of #1525: 增加手工恢复数据库和k8s配置步骤
  content/zh/docs/setup/auto-backup.md
Labels: size/S

#1536 fix: passthrough fixes
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/_index.md
Labels: size/S

#1537 Automated cherry pick of #1536: fix: passthrough fixes
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/_index.md
Labels: size/S

#1534 fix: database ops docs
  content/zh/docs/ops/databases/_index.md
  content/zh/docs/ops/databases/mysql_config.md
  content/zh/docs/ops/databases/mysql_ha_recovery.md
Labels: size/L

#1535 Automated cherry pick of #1534: fix: database ops docs
  content/zh/docs/ops/databases/_index.md
  content/zh/docs/ops/databases/mysql_config.md
  content/zh/docs/ops/databases/mysql_ha_recovery.md
Labels: size/L

#1538 feat(docs): add lvm storage
  content/zh/docs/function_principle/onpremise/storage/blockstorage/add-storage.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
Labels: size/M

#1539 Automated cherry pick of #1538: feat(docs): add lvm storage
  content/zh/docs/function_principle/onpremise/storage/blockstorage/add-storage.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
Labels: size/M

#1540 fix: add provider version
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/S

#1541 Automated cherry pick of #1540: fix: add provider version
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/S

#1546 Automated cherry pick of #1544: feat(3.9):飞天支持菜单优化
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/XS

#1545 Automated cherry pick of #1544: feat(3.9):飞天支持菜单优化
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/XS

#1544 feat(3.9):飞天支持菜单优化
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/XS

#1543 Automated cherry pick of #1542: fix: opeation k8s
  content/zh/docs/function_principle/onpremise/glance/sysimage/supported.md
  content/zh/docs/ops/k8s/_index.md
  content/zh/docs/ops/k8s/dnserror.md
  content/zh/docs/ops/k8s/eviction_threshold.md
  content/zh/docs/ops/k8s/halt_cluster.md
  content/zh/docs/ops/k8s/poderror.md
Labels: size/M

#1542 fix: opeation k8s
  content/zh/docs/function_principle/onpremise/glance/sysimage/supported.md
  content/zh/docs/ops/k8s/_index.md
  content/zh/docs/ops/k8s/dnserror.md
  content/zh/docs/ops/k8s/eviction_threshold.md
  content/zh/docs/ops/k8s/halt_cluster.md
  content/zh/docs/ops/k8s/poderror.md
Labels: size/M
