Repository yunionio/docs, pull requests merged in 2023-11, with the labels that each got.

#1806 fix: update run.py pos args
  content/zh/docs/quickstart/allinone-converge.md
  content/zh/docs/quickstart/allinone-multicloud.md
  content/zh/docs/quickstart/allinone-private.md
Labels: size/S

#1811 feat: Organization Contributors
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/summer-ospp.png
  static/images/provider/tuyou.png
Labels: size/M

#1813 fix: docker compose info
  content/zh/docs/quickstart/docker-compose.md
Labels: size/XS

#1814 Automated cherry pick of #1813: fix: docker compose info
  content/zh/docs/quickstart/docker-compose.md
Labels: size/XS

#1810 feat(4617): update index
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  static/css/global.css
Labels: size/L

#1816 feat: release v3.10.7
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-7.md
  content/en/docs/changelog/release-3.10/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-7.md
  content/zh/docs/development/changelog/release-3.10/_index.md
Labels: size/XL

#1818 update v3.10.7 changelog
  content/en/docs/changelog/release-3.10/3-10-7.md
  content/zh/docs/development/changelog/release-3.10/3-10-7.md
Labels: size/S

#1820 add v3.10.7 and v3.10.6 release notes
  content/zh/docs/release/v3_10_6.md
  content/zh/docs/release/v3_10_7.md
Labels: size/L

#1822 refactor(quickstart): remove stale content
  content/zh/_index.html
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone-converge.md
  content/zh/docs/quickstart/allinone-full.md
  content/zh/docs/quickstart/allinone-virt.md
  content/zh/docs/quickstart/cmp/_index.md
  content/zh/docs/quickstart/cmp/allinone-multicloud.md
  content/zh/docs/quickstart/cmp/docker-compose.md
  content/zh/docs/quickstart/cmp/k8s.md
  content/zh/docs/setup/ha-ce.md
Labels: size/XL

#1824 translation(en): completion of quickstart part
  content/en/_index.html
  content/en/docs/quickstart/_index.md
  content/en/docs/quickstart/allinone-full.md
  content/en/docs/quickstart/allinone-virt.md
  content/en/docs/quickstart/allinone.md
  content/en/docs/quickstart/cmp/_index.md
  content/en/docs/quickstart/cmp/allinone-multicloud.md
  content/en/docs/quickstart/cmp/docker-compose.md
  content/en/docs/quickstart/cmp/k8s.md
  content/en/docs/quickstart/nodes.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone-full.md
  content/zh/docs/quickstart/allinone-virt.md
  content/zh/docs/quickstart/cmp/docker-compose.md
  content/zh/docs/quickstart/cmp/k8s.md
Labels: size/XXL

#1830 fix: vmware管理员账号说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1832 Automated cherry pick of #1830: fix: vmware管理员账号说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1826 docs(db,ha): 数据库高可用相关优化
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/ha-ce.md
Labels: size/L

#1828 Automated cherry pick of #1826: docs(db,ha): 数据库高可用相关优化
  content/zh/docs/setup/db-ha.md
  content/zh/docs/setup/ha-ce.md
Labels: size/L

#1834 Automated cherry pick of #1833: fix: upgrade hugo
  Makefile
  README.md
  README_CN.md
  config.toml
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  layouts/partials/head.html
  layouts/partials/page-meta-links.html
Labels: size/M

#1835 fix(action): use hugo-version 0.120.0
  .github/workflows/release.yml
Labels: size/XS

#1837 Automated cherry pick of #1833: fix: upgrade hugo
  .github/workflows/release.yml
  Makefile
  README.md
  README_CN.md
  config.toml
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  layouts/partials/head.html
  layouts/partials/page-meta-links.html
Labels: size/M

#1838 feat: only build 3.10 and 3.9 content
  scripts/builder/consts.py
Labels: size/S

#1839 Automated cherry pick of #1838: feat: only build 3.10 and 3.9 content
  scripts/builder/consts.py
Labels: size/S

#1840 Automated cherry pick of #1838: feat: only build 3.10 and 3.9 content
  scripts/builder/consts.py
Labels: size/S

#1841 fix: remove unused image Baidu NetDisk links
  content/zh/docs/function_principle/onpremise/glance/common.md
Labels: size/L

#1842 Automated cherry pick of #1841: fix: remove unused image Baidu NetDisk links
  content/zh/docs/function_principle/onpremise/glance/common.md
Labels: size/L

#1843 fix: remove unused docs
  content/en/content/zh/docs/multicloud/compute/snapshot/_index.md
  content/en/content/zh/docs/multicloud/dns/tutorial/cache/_index.md
  content/en/content/zh/docs/multicloud/dns/tutorial/cache/create.md
  content/en/content/zh/docs/multicloud/dns/tutorial/cache/delete.md
  content/en/content/zh/docs/multicloud/nas/tutorial/nasgroup/cache/_index.md
  content/en/content/zh/docs/multicloud/nas/tutorial/nasgroup/cache/delete.md
  content/en/content/zh/docs/multicloud/nas/tutorial/nasgroup/cache/sync.md
  content/en/search.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/intro.md
Labels: size/M
