Repository yunionio/docs, pull requests merged in 2023-03, with the labels that each got.

#1266 fix: update changeip steps
  content/zh/docs/faq/heterresource.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/changeip.md
  content/zh/docs/setup/removehost.md
Labels: size/M

#1267 Automated cherry pick of #1266: fix: update changeip steps
  content/zh/docs/faq/heterresource.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/setup/changeip.md
  content/zh/docs/setup/removehost.md
Labels: size/M

#1261 Update account.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/account.md
Labels: size/XS

#1263 Automated cherry pick of #1261: Update account.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/account.md
Labels: size/XS

#1264 Automated cherry pick of #1261: Update account.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/account.md
Labels: size/XS

#1262 lbagent deploy fixes
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/XS

#1265 Automated cherry pick of #1262: lbagent deploy fixes
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/XS

#1271 Automated cherry pick of #1270: fix: restart baremetal agent after cleanup
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1269 云管平台内设置OpenStack的虚拟机免密登陆及安装监控agent
  content/zh/docs/faq/cloudaccount/_index.md
Labels: size/XS

#1273 Automated cherry pick of #1269: Update _index.md
  content/zh/docs/faq/cloudaccount/_index.md
Labels: size/XS

#1274 Automated cherry pick of #1269: Update _index.md
  content/zh/docs/faq/cloudaccount/_index.md
Labels: size/XS

#1275 feature: new front page
  content/en/_index.html
  content/zh/_index.html
Labels: size/M

#1276 feat(3.10):v2v迁移功能、报表新增批量操作说明
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/report/reportconfig/fields.md
  content/zh/docs/web_ui/report/reportconfig/template.md
Labels: size/M

#1277 feat(3.9):开源文档快速开始增加一个配图
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/images/quickstarthomepage.png
Labels: size/XS

#1283 feature: guest image create
  content/zh/docs/function_principle/onpremise/glance/guestimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/M

#1284 Automated cherry pick of #1283: feature: guest image create
  content/zh/docs/function_principle/onpremise/glance/guestimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/M

#1285 Automated cherry pick of #1283: feature: guest image create
  content/zh/docs/function_principle/onpremise/glance/guestimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
Labels: size/M

#1289 feat(3.10):负载均衡集群更新、负载均衡节点更新、负载均衡支持VPC，弹性公网IP支持绑定LB，虚拟机块存储缺失说明补充
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/network/lb/lb.md
  content/zh/docs/web_ui/network/lbcluster/lbagent.md
  content/zh/docs/web_ui/network/lbcluster/lbcluster.md
  content/zh/docs/web_ui/network/networkservice/eip.md
Labels: size/L

#1286 feat: new front page
  assets/scss/_nav.scss
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  static/images/cloudpods_screen_img.gif
Labels: size/L

#1287 Automated cherry pick of #1286: feat: new front page
  assets/scss/_nav.scss
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  static/images/cloudpods_screen.gif
Labels: size/L

#1288 Automated cherry pick of #1286: feat: new front page
  assets/scss/_nav.scss
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
  layouts/partials/footer.html
  static/images/cloudpods_screen_img.gif
Labels: size/L

#1291 feat(3.10):费用分析列表本年消费移除、云账号资源归属项目、IP子网支持更换二层网络、新建报表模板数据范围新增云账号和项目标签、透…
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/network/basicnetwork/network.md
  content/zh/docs/web_ui/report/reportconfig/template.md
Labels: size/M

#1293 fix: imporove offline search experience
  assets/js/offline-search.js
  layouts/partials/head.html
Labels: size/M

#1294 Automated cherry pick of #1293: fix: imporove offline search experience
  assets/js/offline-search.js
  layouts/partials/head.html
Labels: size/M

#1295 Automated cherry pick of #1293: fix: imporove offline search experience
  assets/js/offline-search.js
  layouts/partials/head.html
Labels: size/M

#1296 feat: screen img loading add default w-h
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#1297 Automated cherry pick of #1296: feat: screen img loading add default w-h
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#1298 Automated cherry pick of #1296: feat: screen img loading add default w-h
  assets/scss/_variables_project.scss
  content/en/_index.html
  content/zh/_index.html
Labels: size/S

#1303 fix: update log options
  content/zh/docs/function_principle/misc/log/log-options.md
  content/zh/docs/function_principle/misc/log/log-purge.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
Labels: size/M

#1305 Automated cherry pick of #1303: fix: update log options
  content/zh/docs/function_principle/misc/log/log-options.md
  content/zh/docs/function_principle/misc/log/log-purge.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
Labels: size/M

#1306 Automated cherry pick of #1303: fix: update log options
  content/zh/docs/function_principle/misc/log/log-options.md
  content/zh/docs/function_principle/misc/log/log-purge.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/create.md
Labels: size/M

#1307 fix: vendor updates
  content/zh/docs/contact/_index.md
  content/zh/docs/development/dev-env.md
  static/images/contact_me_qr_20230321.png
Labels: size/S

#1308 Automated cherry pick of #1307: fix: vendor updates
  content/zh/docs/contact/_index.md
  content/zh/docs/development/dev-env.md
  static/images/contact_me_qr_20230321.png
Labels: size/S

#1302 feat(3.9):反亲和组添加VIP、新建块存储本地存储增加跳转链接、全局搜索增加DNS、监控查询增加标签、新建虚机支持GPU分类
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/computing/server/vminstancegroup.md
  content/zh/docs/web_ui/intro/ui/globalsearch.md
  content/zh/docs/web_ui/monitor/metric/explorer.md
  content/zh/docs/web_ui/storage/block.md
Labels: size/S

#1304 feat(3.9):release note 3.9.8
  content/zh/docs/release/v3_9_8.md
Labels: size/M

#1313 feat(3.10):HCS纳管信息补充
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1314 Automated cherry pick of #1313: feat(3.10):HCS纳管信息补充
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1316 feat(quickstart): docker compose setup
  content/zh/docs/quickstart/docker-compose.md
  content/zh/docs/quickstart/k8s.md
Labels: size/L

#1315 feat(3.9):商业文档-开发手册新增OIDC认证
  content/zh/docs/development/images/oidc.png
  content/zh/docs/development/images/openid.png
  content/zh/docs/development/oidc.md
Labels: size/L

#1318 Automated cherry pick of #1315: feat(3.9):商业文档-开发手册新增OIDC认证
  content/zh/docs/development/images/oidc.png
  content/zh/docs/development/images/openid.png
  content/zh/docs/development/oidc.md
Labels: size/L

#1322 fix(compose): how to update
  content/zh/docs/quickstart/docker-compose.md
Labels: size/S

#1324 docs(ce,ee): 一键切换开源、商业版本的文档
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#1325 Automated cherry pick of #1324: docs(ce,ee): 一键切换开源、商业版本的文档
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#1326 Automated cherry pick of #1324: docs(ce,ee): 一键切换开源、商业版本的文档
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S
