Repository yunionio/docs, pull requests merged in 2023-01, with the labels that each got.

#1173 feat(3.10):sriov网卡、透传设备增加网卡
  content/zh/docs/web_ui/computing/resources/_index.md
  content/zh/docs/web_ui/computing/resources/gpu.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1174 feat(3.10):sriov网卡透传内容补充
  content/zh/docs/web_ui/computing/resources/gpu.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/S

#1176 feat: release v3.9.6
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.8/3-8-0.md
  content/en/docs/changelog/release-3.8/3-8-1.md
  content/en/docs/changelog/release-3.9/3-9-6.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.8/3-8-0.md
  content/zh/docs/development/changelog/release-3.8/3-8-1.md
  content/zh/docs/development/changelog/release-3.9/3-9-6.md
  content/zh/docs/development/changelog/release-3.9/_index.md
  content/zh/docs/release/v3_9_5.md
Labels: size/XXL

#1178 feat(3.9):v3.9.5发布日志顺序更新
  content/zh/docs/release/v3_9_5.md
Labels: size/XS

#1179 feat(3.9):主备机相关操作优化、宿主机CPU预留资源、宿主机设置透传设备预留资源批量操作、虚拟机详情增加刷新操作
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/images/computing/refresh.png
Labels: size/M

#1182 fix(ee): upgrade steps
  content/zh/docs/setup/upgrade-guide/upgrade.md
Labels: size/S

#1188 docs(backup): ocboot备份功能更新：备份文件的名称修正；增加精简备份选项
  content/zh/docs/setup/backup.md
Labels: size/M

#1191 Automated cherry pick of #1188: docs(backup): ocboot备份功能更新：备份文件的名称修正；增加精简备份选项
  content/zh/docs/setup/backup.md
Labels: size/M

#1190 Automated cherry pick of #1188: docs(backup): ocboot备份功能更新：备份文件的名称修正；增加精简备份选项
  content/zh/docs/setup/backup.md
Labels: size/M

#1189 Automated cherry pick of #1188: docs(backup): ocboot备份功能更新：备份文件的名称修正；增加精简备份选项
  content/zh/docs/setup/backup.md
Labels: size/M

#1187 feat(3.9):常用镜像增加两个x86centos7,3.9.6发布日志
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/release/v3_9_6.md
Labels: size/M

#1193 Gso off
  content/zh/docs/ops/dnserror.md
Labels: size/XS

#1198 fix: add php sdk
  content/zh/docs/development/apisdk/02_sdk.md
  content/zh/docs/function_principle/onpremise/network/examples.md
Labels: size/XS

#1199 Automated cherry pick of #1198: fix: add php sdk
  content/zh/docs/development/apisdk/02_sdk.md
  content/zh/docs/function_principle/onpremise/network/examples.md
Labels: size/XS

#1200 Automated cherry pick of #1198: fix: add php sdk
  content/zh/docs/development/apisdk/02_sdk.md
  content/zh/docs/function_principle/onpremise/network/examples.md
Labels: size/XS

#1196 feat(3.10):云账号增加设置同步策略，云账号新增新建云上项目操作
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1197 feat(3.10):报表、报表订阅、账单汇总订阅
  content/zh/docs/web_ui/cost/bill/billsummary.md
  content/zh/docs/web_ui/images/report/diy.png
  content/zh/docs/web_ui/images/report/domain.png
  content/zh/docs/web_ui/images/report/fields.png
  content/zh/docs/web_ui/images/report/project.png
  content/zh/docs/web_ui/images/report/template.png
  content/zh/docs/web_ui/report/_index.md
  content/zh/docs/web_ui/report/reportconfig/_index.md
  content/zh/docs/web_ui/report/reportconfig/fields.md
  content/zh/docs/web_ui/report/reportconfig/template.md
  content/zh/docs/web_ui/report/reportform/_index.md
  content/zh/docs/web_ui/report/reportform/diy.md
  content/zh/docs/web_ui/report/reportform/domain.md
  content/zh/docs/web_ui/report/reportform/project.md
  content/zh/docs/web_ui/storage/backup.md
  content/zh/docs/web_ui/storage/bucket.md
Labels: size/XL

#1204 fix: submodule --force update
  scripts/setup.sh
Labels: size/XS

#1206 Automated cherry pick of #1204: fix: submodule --force update
  scripts/setup.sh
Labels: size/XS

#1207 Update hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
Labels: size/M

#1208 Automated cherry pick of #1207: Update hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
Labels: size/M

#1212 Automated cherry pick of #1210: fix: server-create mem spec
  content/zh/docs/function_principle/onpremise/vminstance/create.md
Labels: size/XS

#1211 Automated cherry pick of #1210: fix: server-create mem spec
  content/zh/docs/function_principle/onpremise/vminstance/create.md
Labels: size/XS

#1201 错误文案修改
  content/zh/docs/function_principle/onpremise/vminstance/change-disk-storge.md
Labels: size/XS

#1214 Automated cherry pick of #1201: Update change-disk-storge.md
  content/zh/docs/function_principle/onpremise/vminstance/change-disk-storge.md
Labels: size/XS

#1216 Update hosterror.md
  content/zh/docs/ops/hosterror.md
Labels: size/XS

#1220 Automated cherry pick of #1216: Update hosterror.md
  content/zh/docs/ops/hosterror.md
Labels: size/XS

#1221 Automated cherry pick of #1216: Update hosterror.md
  content/zh/docs/ops/hosterror.md
Labels: size/XS

#1217 fix: vmware network concepts
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware_net.md
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/L

#1219 Automated cherry pick of #1217: fix: vmware network concepts
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware_net.md
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/L

#1218 Automated cherry pick of #1217: fix: vmware network concepts
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/vmware_net.md
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/L
