Repository yunionio/docs, pull requests merged in 2023-07, with the labels that each got.

#1547 fix: k8s network troubleshooting docs
  content/zh/docs/ops/k8s/dnserror.md
Labels: size/XS

#1548 Automated cherry pick of #1547: fix: k8s network troubleshooting docs
  content/zh/docs/ops/k8s/dnserror.md
Labels: size/XS

#1549 feat: release 3.10.3
  config-ee.toml
  config.toml
  content/zh/docs/development/changelog/release-3.10/3-10-3.md
  content/zh/docs/development/changelog/release-3.10/_index.md
Labels: size/L

#1551 feat:release note v3.10.3
  content/zh/docs/release/v3_10_3.md
Labels: size/M

#1552 Automated cherry pick of #1551: feat:release note v3.10.3
  content/zh/docs/release/v3_10_3.md
Labels: size/M

#1553 feat:release note升级方式文案
  content/zh/docs/release/v3_10_0.md
  content/zh/docs/release/v3_10_1.md
  content/zh/docs/release/v3_10_2.md
  content/zh/docs/release/v3_10_3.md
Labels: size/XS

#1554 Automated cherry pick of #1553: feat:release note升级方式文案
  content/zh/docs/release/v3_10_0.md
  content/zh/docs/release/v3_10_1.md
  content/zh/docs/release/v3_10_2.md
  content/zh/docs/release/v3_10_3.md
Labels: size/XS

#1555 Fix typo and edit add-cloud implementation directory description
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS

#1561 Automated cherry pick of #1555: Fix typo and edit add-cloud implementation directory description
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS

#1557 Update usage.md：增加自动补全指引
  content/zh/docs/ops/climc/usage.md
Labels: size/S

#1562 Automated cherry pick of #1557: Update usage.md：增加自动补全指引
  content/zh/docs/ops/climc/usage.md
Labels: size/S

#1558 增加部署cloudpods的操作系统类型，数据库默认安装版本及ansible的版本要求
  content/zh/docs/quickstart/allinone.md
Labels: size/S

#1563 Automated cherry pick of #1558: 增加部署cloudpods的操作系统类型，数据库默认安装版本及ansible的版本要求
  content/zh/docs/quickstart/allinone.md
Labels: size/S

#1559 Slave97
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/intro/usercenter/userinfor.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/S

#1560 Automated cherry pick of #1559: feat(3.10):新建aws读写权限文案修改
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/intro/usercenter/userinfor.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/S

#1568 docs(gpt): 更新release version
  Makefile
Labels: size/XS

#1565 feat(3.9):阿里云获取存储痛URL文档更新
  content/zh/docs/faq/image/aliyunossbucket1.png
  content/zh/docs/faq/image/aliyunusercenter.png
  content/zh/docs/faq/image/aliyunusercenterhome.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1567 Automated cherry pick of #1565: feat(3.9):阿里云获取存储痛URL文档更新
  content/zh/docs/faq/image/aliyunossbucket1.png
  content/zh/docs/faq/image/aliyunusercenter.png
  content/zh/docs/faq/image/aliyunusercenterhome.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1566 Automated cherry pick of #1565: feat(3.9):阿里云获取存储痛URL文档更新
  content/zh/docs/faq/image/aliyunossbucket1.png
  content/zh/docs/faq/image/aliyunusercenter.png
  content/zh/docs/faq/image/aliyunusercenterhome.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1569 更改https 443为自定义端口
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/M

#1572 Automated cherry pick of #1569: 更改https 443为自定义端口
  content/zh/docs/setup/config-ssl-certs.md
Labels: size/M

#1573 Automated cherry pick of #1564: Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1564 Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1574 Update db-ha.md：增加节点IP 信息说明
  content/zh/docs/setup/db-ha.md
Labels: size/XS

#1578 增加公有云环境部署时不要用MySQL 5.6及以下版本的提示信息
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1582 Automated cherry pick of #1578: 增加公有云环境部署时不要用MySQL 5.6及以下版本的提示信息
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1579 feat: 支持隐藏引导页子页面链接
  layouts/partials/section-index.html
Labels: size/S

#1580 Automated cherry pick of #1579: feat: 支持隐藏引导页子页面链接
  layouts/partials/section-index.html
Labels: size/S

#1581 Automated cherry pick of #1579: feat: 支持隐藏引导页子页面链接
  layouts/partials/section-index.html
Labels: size/S

#1583 changelog of v3.9.12
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.10/3-10-3.md
  content/en/docs/changelog/release-3.10/_index.md
  content/en/docs/changelog/release-3.9/3-9-12.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-12.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/L

#1586 feat:v3.9.12 release note
  content/zh/docs/release/v3_9_12.md
Labels: size/M

#1587 Automated cherry pick of #1586: feat:v3.9.12 release note
  content/zh/docs/release/v3_9_12.md
Labels: size/M

#1588 Automated cherry pick of #1586: feat:v3.9.12 release note
  content/zh/docs/release/v3_9_12.md
Labels: size/M

#1585 Update host.md：增加常见问题一节，添加介质不准的修改指引
  content/zh/docs/setup/host.md
Labels: size/XS

#1592 Automated cherry pick of #1590: feat(3.9):错别字，二次网络-->二层网络
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/XS

#1590 feat(3.9):错别字，二次网络-->二层网络
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/XS

#1591 Automated cherry pick of #1590: feat(3.9):错别字，二次网络-->二层网络
  content/zh/docs/function_principle/onpremise/network/_index.md
Labels: size/XS

#1594 feat: k8s readonly import
  content/zh/docs/function_principle/k8s/readonly-import.md
Labels: size/L

#1601 fix: tabs end label
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1597 feat(3.9):上传系统镜像优化
  content/zh/docs/web_ui/computing/image/image.md
Labels: size/XS

#1599 Automated cherry pick of #1597: feat(3.9):上传系统镜像优化
  content/zh/docs/web_ui/computing/image/image.md
Labels: size/XS

#1603 update docs
  content/zh/docs/development/devtools.md
  content/zh/docs/function_principle/onpremise/lb/lbhowto.md
  content/zh/docs/function_principle/onpremise/network/vpc/_index.md
  content/zh/docs/function_principle/onpremise/network/vpc/eiphowto.md
  content/zh/docs/function_principle/onpremise/network/vpc/mtu.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpc-ovn.png
  content/zh/docs/function_principle/onpremise/network/vpc/vpc_internal.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcnat.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcnat.png
  content/zh/docs/ops/changeip.md
  content/zh/docs/ops/databases/db-record-consistency.md
  content/zh/docs/ops/ha/_index.md
  content/zh/docs/ops/ha/auto-backup.md
  content/zh/docs/ops/ha/backup.md
  content/zh/docs/ops/ha/ha.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/k8s/commonops.md
  content/zh/docs/ops/k8s/oc-update.md
  content/zh/docs/ops/log/_index.md
  content/zh/docs/ops/log/backendlogs.md
  content/zh/docs/ops/log/log.md
  content/zh/docs/ops/nginx/_index.md
  content/zh/docs/ops/nginx/behindnginx.md
  content/zh/docs/ops/nginx/config-ssl-certs.md
  content/zh/docs/ops/nginx/traefik-mutual-tls.md
  content/zh/docs/ops/nginx/web-use-http.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/removehost.md
  content/zh/docs/setup/uninstall.md
Labels: size/L

#1604 Automated cherry pick of #1603: update docs
  content/zh/docs/development/devtools.md
  content/zh/docs/function_principle/onpremise/lb/lbhowto.md
  content/zh/docs/function_principle/onpremise/network/vpc/_index.md
  content/zh/docs/function_principle/onpremise/network/vpc/eiphowto.md
  content/zh/docs/function_principle/onpremise/network/vpc/mtu.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpc-ovn.png
  content/zh/docs/function_principle/onpremise/network/vpc/vpc_internal.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcnat.md
  content/zh/docs/function_principle/onpremise/network/vpc/vpcnat.png
  content/zh/docs/ops/changeip.md
  content/zh/docs/ops/databases/db-record-consistency.md
  content/zh/docs/ops/ha/_index.md
  content/zh/docs/ops/ha/auto-backup.md
  content/zh/docs/ops/ha/backup.md
  content/zh/docs/ops/ha/ha.md
  content/zh/docs/ops/hosterror.md
  content/zh/docs/ops/k8s/commonops.md
  content/zh/docs/ops/k8s/oc-update.md
  content/zh/docs/ops/log/_index.md
  content/zh/docs/ops/log/backendlogs.md
  content/zh/docs/ops/log/log.md
  content/zh/docs/ops/nginx/_index.md
  content/zh/docs/ops/nginx/behindnginx.md
  content/zh/docs/ops/nginx/config-ssl-certs.md
  content/zh/docs/ops/nginx/traefik-mutual-tls.md
  content/zh/docs/ops/nginx/web-use-http.md
  content/zh/docs/setup/baremetal.md
  content/zh/docs/setup/controlplane.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/nodes.md
  content/zh/docs/setup/removehost.md
  content/zh/docs/setup/uninstall.md
Labels: size/L

#1605 fix: update docs 20230718-2
  content/zh/docs/ops/update_kernel.md
  content/zh/docs/setup/repo.md
Labels: size/XS

#1606 Automated cherry pick of #1605: fix: update docs 20230718-2
  content/zh/docs/ops/update_kernel.md
  content/zh/docs/setup/repo.md
Labels: size/XS

#1614 Automated cherry pick of #1612: docs(uos): 去掉uos相关支持的wording
  content/en/docs/quickstart/allinone.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/release/v3_9_12.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/intro.md
Labels: size/M

#1612 docs(uos): 去掉uos、增加debian11的描述
  content/en/docs/quickstart/allinone.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/release/v3_9_12.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/intro.md
Labels: size/M

#1613 Automated cherry pick of #1612: docs(uos): 去掉uos相关支持的wording
  content/en/docs/quickstart/allinone.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/create.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone.md
  content/zh/docs/release/v3_9_12.md
  content/zh/docs/setup/host-aarch64.md
  content/zh/docs/setup/intro.md
Labels: size/M

#1609 更换微信二维码
  content/en/_index.html
  content/en/docs/contact/_index.md
  content/zh/_index.html
Labels: size/XS

#1610 Automated cherry pick of #1609: 更换微信二维码
  content/en/_index.html
  content/en/docs/contact/_index.md
  content/zh/_index.html
Labels: size/XS

#1611 Automated cherry pick of #1609: 更换微信二维码
  content/en/_index.html
  content/en/docs/contact/_index.md
  content/zh/_index.html
Labels: size/XS

#1617 fix: add docs for storage
  content/zh/docs/function_principle/onpremise/storage/backupstorage/_index.md
  content/zh/docs/function_principle/onpremise/storage/backupstorage/create.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/_index.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/add-storage.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/ceph.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
Labels: size/L

#1618 Automated cherry pick of #1617: fix: add docs for storage
  content/zh/docs/function_principle/onpremise/storage/backupstorage/_index.md
  content/zh/docs/function_principle/onpremise/storage/backupstorage/create.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/_index.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/add-storage.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/ceph.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
Labels: size/L

#1616 Automated cherry pick of #1615: feat(3.9):文档内容和目录的一些优化
  content/zh/docs/faq/intro.md
  content/zh/docs/function_principle/onpremise/baremetal/bonding_shared_bmc_nic.md
  content/zh/docs/function_principle/onpremise/baremetal/change_ip_address.md
  content/zh/docs/function_principle/onpremise/baremetal/change_netif.md
  content/zh/docs/function_principle/onpremise/baremetal/convert.md
  content/zh/docs/function_principle/onpremise/baremetal/create_register_redirect.md
  content/zh/docs/function_principle/onpremise/baremetal/create_server.md
  content/zh/docs/function_principle/onpremise/baremetal/hardware-requirements.md
  content/zh/docs/function_principle/onpremise/baremetal/machine/_index.md
  content/zh/docs/function_principle/onpremise/baremetal/manual_change_raid.md
  content/zh/docs/function_principle/onpremise/baremetal/nic_persistent_naming.md
  content/zh/docs/function_principle/onpremise/baremetal/principle.md
  content/zh/docs/function_principle/onpremise/baremetal/testcase.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/_index.md
  content/zh/docs/function_principle/onpremise/host/auto-migrate-on-hostdown.md
  content/zh/docs/function_principle/onpremise/host/enable.md
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/function_principle/onpremise/host/hosterror.md
  content/zh/docs/function_principle/onpremise/host/list.md
  content/zh/docs/function_principle/onpremise/host/reservecpus.md
  content/zh/docs/function_principle/onpremise/host/troubleshooting.md
  content/zh/docs/function_principle/onpremise/host/update_kernel.md
  content/zh/docs/function_principle/onpremise/vminstance/change-disk-storge.md
  content/zh/docs/function_principle/onpremise/vminstance/change_disk_driver.md
  content/zh/docs/function_principle/onpremise/vminstance/customize.md
  content/zh/docs/function_principle/onpremise/vminstance/delete.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/import.md
  content/zh/docs/function_principle/onpremise/vminstance/migrate.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/_index.md
  content/zh/docs/function_principle/onpremise/vminstance/perf-test/_index.md
  content/zh/docs/function_principle/onpremise/vminstance/purge.md
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
  content/zh/docs/function_principle/onpremise/vminstance/time.md
Labels: size/L

#1619 Automated cherry pick of #1615: feat(3.9):文档内容和目录的一些优化
  content/zh/docs/faq/intro.md
  content/zh/docs/function_principle/onpremise/baremetal/bonding_shared_bmc_nic.md
  content/zh/docs/function_principle/onpremise/baremetal/change_ip_address.md
  content/zh/docs/function_principle/onpremise/baremetal/change_netif.md
  content/zh/docs/function_principle/onpremise/baremetal/convert.md
  content/zh/docs/function_principle/onpremise/baremetal/create_register_redirect.md
  content/zh/docs/function_principle/onpremise/baremetal/create_server.md
  content/zh/docs/function_principle/onpremise/baremetal/hardware-requirements.md
  content/zh/docs/function_principle/onpremise/baremetal/machine/_index.md
  content/zh/docs/function_principle/onpremise/baremetal/manual_change_raid.md
  content/zh/docs/function_principle/onpremise/baremetal/nic_persistent_naming.md
  content/zh/docs/function_principle/onpremise/baremetal/principle.md
  content/zh/docs/function_principle/onpremise/baremetal/testcase.md
  content/zh/docs/function_principle/onpremise/glance/guestimage/_index.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/_index.md
  content/zh/docs/function_principle/onpremise/host/auto-migrate-on-hostdown.md
  content/zh/docs/function_principle/onpremise/host/enable.md
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/function_principle/onpremise/host/hosterror.md
  content/zh/docs/function_principle/onpremise/host/list.md
  content/zh/docs/function_principle/onpremise/host/reservecpus.md
  content/zh/docs/function_principle/onpremise/host/troubleshooting.md
  content/zh/docs/function_principle/onpremise/host/update_kernel.md
  content/zh/docs/function_principle/onpremise/vminstance/change-disk-storge.md
  content/zh/docs/function_principle/onpremise/vminstance/change_disk_driver.md
  content/zh/docs/function_principle/onpremise/vminstance/customize.md
  content/zh/docs/function_principle/onpremise/vminstance/delete.md
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
  content/zh/docs/function_principle/onpremise/vminstance/import.md
  content/zh/docs/function_principle/onpremise/vminstance/migrate.md
  content/zh/docs/function_principle/onpremise/vminstance/perf-test/_index.md
  content/zh/docs/function_principle/onpremise/vminstance/purge.md
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
  content/zh/docs/function_principle/onpremise/vminstance/time.md
  content/zh/docs/ops/hosterror.md
Labels: size/L

#1624 fix: add description for adding node when use HA environment
  content/zh/docs/setup/ha-ce.md
  content/zh/docs/setup/host.md
Labels: size/S

#1622 feat(3.10)：月报订阅-月报、日报
  content/zh/docs/web_ui/images/report/daily.png
  content/zh/docs/web_ui/images/report/monthly.png
  content/zh/docs/web_ui/report/monthlyreport/_index.md
  content/zh/docs/web_ui/report/monthlyreport/daily.md
  content/zh/docs/web_ui/report/monthlyreport/monthly.md
Labels: size/L

#1626 fix: replace HA controlplane node
  content/zh/docs/ops/ha/replace.md
Labels: size/L

#1627 Automated cherry pick of #1626: fix: replace HA controlplane node
  content/zh/docs/ops/ha/replace.md
Labels: size/L

#1628 fix: grafana password
  content/zh/docs/ops/log/backendlogs.md
Labels: size/S

#1629 Automated cherry pick of #1628: fix: grafana password
  content/zh/docs/ops/log/backendlogs.md
Labels: size/S

#1631 Automated cherry pick of #1630: fix: ceph df intro
  content/zh/docs/function_principle/onpremise/storage/blockstorage/_index.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/ceph.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/storage_sync.md
Labels: size/L

#1632 fix: usb-passthrough refresh docs
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb-passthrough.md
Labels: size/XS

#1633 Automated cherry pick of #1632: fix: usb-passthrough refresh docs
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/usb-passthrough.md
Labels: size/XS

#1634 feat(3.10)；webhook机器人、npu透传、屏蔽资源类型
  content/zh/docs/web_ui/computing/resources/gpu.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/iam/notify/bot.md
  content/zh/docs/web_ui/images/computing/gpu.png
  content/zh/docs/web_ui/images/computing/gpu1.png
  content/zh/docs/web_ui/images/computing/pci.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L
