Repository yunionio/docs, pull requests merged in 2023-04, with the labels that each got.

#1329 Automated cherry pick of #1304: feat(3.9):release note 3.9.8
  content/zh/docs/release/v3_9_8.md
Labels: size/M

#1330 Automated cherry pick of #1304: feat(3.9):release note 3.9.8
  content/zh/docs/release/v3_9_8.md
Labels: size/M

#1331 fix(dev): how to add GITHUB_TOKEN
  content/zh/docs/development/contrib.md
Labels: size/XS

#1337 fix(convert): add host convert image
  content/zh/docs/function_principle/onpremise/baremetal/convert.md
Labels: size/XS

#1338 Automated cherry pick of #1337: fix(convert): add host convert image
  content/zh/docs/function_principle/onpremise/baremetal/convert.md
Labels: size/XS

#1334 feat:常见问题移除三级权限说明
  content/zh/docs/faq/others.md
Labels: size/XS

#1335 Automated cherry pick of #1334: feat:常见问题移除三级权限说明
  content/zh/docs/faq/others.md
Labels: size/XS

#1336 Automated cherry pick of #1334: feat:常见问题移除三级权限说明
  content/zh/docs/faq/others.md
Labels: size/XS

#1340 Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1341 Automated cherry pick of #1340: Update allinone.md
  content/zh/docs/quickstart/allinone.md
Labels: size/XS

#1346 add providers
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/JDCloud.png
  static/images/provider/Nutanix.png
  static/images/provider/Proxmox.png
  static/images/provider/ceph.png
  static/images/provider/cmecloud.png
  static/images/provider/ctyun.png
  static/images/provider/google_cloud.png
  static/images/provider/huaweicloud.png
  static/images/provider/lexin.png
  static/images/provider/minio.png
  static/images/provider/pingaocloud.png
  static/images/provider/shanghaijisuankeji.png
  static/images/provider/weilai.png
  static/images/provider/xiaoyingkeji.png
Labels: size/M

#1347 Automated cherry pick of #1346: add providers
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/JDCloud.png
  static/images/provider/Nutanix.png
  static/images/provider/Proxmox.png
  static/images/provider/ceph.png
  static/images/provider/cmecloud.png
  static/images/provider/ctyun.png
  static/images/provider/google_cloud.png
  static/images/provider/huaweicloud.png
  static/images/provider/lexin.png
  static/images/provider/minio.png
  static/images/provider/pingaocloud.png
  static/images/provider/shanghaijisuankeji.png
  static/images/provider/weilai.png
  static/images/provider/xiaoyingkeji.png
Labels: size/M

#1348 Automated cherry pick of #1346: add providers
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/JDCloud.png
  static/images/provider/Nutanix.png
  static/images/provider/Proxmox.png
  static/images/provider/ceph.png
  static/images/provider/cmecloud.png
  static/images/provider/ctyun.png
  static/images/provider/google_cloud.png
  static/images/provider/huaweicloud.png
  static/images/provider/lexin.png
  static/images/provider/minio.png
  static/images/provider/pingaocloud.png
  static/images/provider/shanghaijisuankeji.png
  static/images/provider/weilai.png
  static/images/provider/xiaoyingkeji.png
Labels: size/M

#1343 fix: add openstack vnc doc
  content/zh/docs/faq/cloudaccount/openstack.md
Labels: size/S

#1344 Automated cherry pick of #1343: fix: add openstack vnc doc
  content/zh/docs/faq/cloudaccount/openstack.md
Labels: size/S

#1345 Automated cherry pick of #1343: fix: add openstack vnc doc
  content/zh/docs/faq/cloudaccount/openstack.md
Labels: size/S

#1353 Automated cherry pick of #1352: fix: python version
  .github/workflows/release.yml
Labels: size/XS

#1357 changelog of v3.9.9
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.9/3-9-9.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-9.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/L

#1358 Automated cherry pick of #1357: changelog of v3.9.9
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.9/3-9-9.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-9.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/L

#1355 fix: add sdk of easy cloudpods
  content/zh/docs/development/apisdk/02_sdk.md
Labels: size/XS

#1356 Automated cherry pick of #1355: fix: add sdk of easy cloudpods
  content/zh/docs/development/apisdk/02_sdk.md
Labels: size/XS

#1365 docs(backup): 新增「自动备份」子命令的文档
  content/zh/docs/setup/auto-backup.md
  content/zh/docs/setup/backup.md
Labels: size/M

#1366 Automated cherry pick of #1365: docs(backup): 新增「自动备份」子命令的文档
  content/zh/docs/setup/auto-backup.md
  content/zh/docs/setup/backup.md
Labels: size/M

#1367 Automated cherry pick of #1365: docs(backup): 新增「自动备份」子命令的文档
  content/zh/docs/setup/auto-backup.md
  content/zh/docs/setup/backup.md
Labels: size/M

#1363 fix(climc): add climc args doc
  content/zh/docs/ops/climc/_index.md
  content/zh/docs/ops/climc/auth.md
  content/zh/docs/ops/climc/install.md
  content/zh/docs/ops/climc/list.md
  content/zh/docs/ops/climc/usage.md
Labels: size/XXL

#1364 Automated cherry pick of #1363: fix(climc): add climc args doc
  content/zh/docs/ops/climc/_index.md
  content/zh/docs/ops/climc/auth.md
  content/zh/docs/ops/climc/install.md
  content/zh/docs/ops/climc/list.md
  content/zh/docs/ops/climc/usage.md
Labels: size/XXL

#1360 Update baremetal.md
  content/zh/docs/setup/baremetal.md
Labels: size/S

#1368 Automated cherry pick of #1360: Update baremetal.md
  content/zh/docs/setup/baremetal.md
Labels: size/S

#1369 Automated cherry pick of #1360: Update baremetal.md
  content/zh/docs/setup/baremetal.md
Labels: size/S

#1372 Automated cherry pick of #1371: fix: issues link
  layouts/partials/page-meta-links.html
Labels: size/M

#1373 Automated cherry pick of #1371: fix: issues link
  layouts/partials/page-meta-links.html
Labels: size/M

#1378 Automated cherry pick of #1377: fix: add cloudmon doc
  content/zh/docs/function_principle/monitor_ops/monitor/cloudmon.md
Labels: size/L

#1379 Automated cherry pick of #1377: fix: add cloudmon doc
  content/zh/docs/function_principle/monitor_ops/monitor/cloudmon.md
Labels: size/L

#1374 feat:配置要求修改操作系统版本范围，虚拟机文档完善agent说明
  content/zh/docs/setup/config.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1375 Automated cherry pick of #1374: feat:配置要求修改操作系统版本范围，虚拟机文档完善agent说明
  content/zh/docs/setup/config.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1376 Automated cherry pick of #1374: feat:配置要求修改操作系统版本范围，虚拟机文档完善agent说明
  content/zh/docs/setup/config.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1383 feat(3.10):多云纳管新增proxmox纳管步骤说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1384 Automated cherry pick of #1383: feat(3.10):多云纳管新增proxmox纳管步骤说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1380 feat(3.9):文档中涉及cloudpods和Nutanix纳管的一些错误修改
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1382 Automated cherry pick of #1380: feat(3.9):文档中涉及cloudpods和Nutanix纳管的一些错误修改
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1385 feat(3.10):云账号纳管增加同步策略和资源归属方式说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/projectmappping.md
Labels: size/L

#1386 Automated cherry pick of #1385: feat(3.10):云账号纳管增加同步策略和资源归属方式说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/projectmappping.md
Labels: size/L

#1361 fix: secgroup design doc
  content/zh/docs/function_principle/multicloud/compute/secgroup/principle.md
  content/zh/docs/web_ui/computing/network/secgroup.md
Labels: size/M

#1362 Automated cherry pick of #1361: fix: secgroup design doc
  content/zh/docs/function_principle/multicloud/compute/secgroup/principle.md
  content/zh/docs/web_ui/computing/network/secgroup.md
Labels: size/M

#1387 feat(3.10):同步策略不仅支持公有云
  content/zh/docs/web_ui/multiplecloud/cloudaccount/projectmappping.md
Labels: size/XS

#1388 Automated cherry pick of #1387: feat(3.10):同步策略不仅支持公有云
  content/zh/docs/web_ui/multiplecloud/cloudaccount/projectmappping.md
Labels: size/XS

#1389 feat(3.10):proxmoxve云账号纳管增加认证方式和账号说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1390 Automated cherry pick of #1389: feat(3.10):proxmoxve云账号纳管增加认证方式和账号说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1394 fix: change bootstrap src
  layouts/partials/scripts.html
Labels: size/S

#1395 Automated cherry pick of #1394: fix: change bootstrap src
  layouts/partials/scripts.html
Labels: size/S

#1397 Ee build singlever
  Makefile.ee
  config-ee.toml
Labels: size/XS

#1398 Automated cherry pick of #1397: - only build single version on ee - enable sidebar search
  Makefile.ee
  config-ee.toml
Labels: size/XS

#1399 Automated cherry pick of #1397: - only build single version on ee - enable sidebar search
  Makefile.ee
  config-ee.toml
Labels: size/XS

#1391 fix: add host network image
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/function_principle/onpremise/network/singleport.png
  content/zh/docs/function_principle/onpremise/network/singleportvlan.png
Labels: size/XS

#1392 Automated cherry pick of #1391: fix: add host network image
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/function_principle/onpremise/network/singleport.png
  content/zh/docs/function_principle/onpremise/network/singleportvlan.png
Labels: size/XS

#1393 Automated cherry pick of #1391: fix: add host network image
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/function_principle/onpremise/network/singleport.png
  content/zh/docs/function_principle/onpremise/network/singleportvlan.png
Labels: size/XS

#1401 feat(3.10):多云管理proxmox纳管信息完善、操作菜单细化、同步策略新增说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/synchronizationpolicy.md
Labels: size/L

#1402 Automated cherry pick of #1401: feat(3.10):多云管理proxmox纳管信息完善、操作菜单细化、同步策略新增说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/synchronizationpolicy.md
Labels: size/L

#1403 feat(3.10):费用新增项目分摊
  content/zh/docs/web_ui/cost/analysis/billaccount.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billstatistics.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/cost/analysis/billtime.md
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/cost/bill/billdetail.md
  content/zh/docs/web_ui/cost/bill/billresource.md
  content/zh/docs/web_ui/cost/bill/billsummary.md
  content/zh/docs/web_ui/cost/billoverview.md
Labels: size/M

#1404 Automated cherry pick of #1403: feat(3.10):费用新增项目分摊
  content/zh/docs/web_ui/cost/analysis/billaccount.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/cost/analysis/billdomain.md
  content/zh/docs/web_ui/cost/analysis/billproject.md
  content/zh/docs/web_ui/cost/analysis/billresoursetype.md
  content/zh/docs/web_ui/cost/analysis/billstatistics.md
  content/zh/docs/web_ui/cost/analysis/billtag.md
  content/zh/docs/web_ui/cost/analysis/billtime.md
  content/zh/docs/web_ui/cost/bill/billassociate.md
  content/zh/docs/web_ui/cost/bill/billdetail.md
  content/zh/docs/web_ui/cost/bill/billresource.md
  content/zh/docs/web_ui/cost/bill/billsummary.md
  content/zh/docs/web_ui/cost/billoverview.md
Labels: size/M

#1405 feat:一键巡检功能
  content/zh/docs/web_ui/systemconfig/inspection/_index.md
  content/zh/docs/web_ui/systemconfig/inspection/inspection.md
Labels: size/M

#1406 Automated cherry pick of #1405: feat:一键巡检功能
  content/zh/docs/web_ui/systemconfig/inspection/_index.md
  content/zh/docs/web_ui/systemconfig/inspection/inspection.md
Labels: size/M

#1407 Automated cherry pick of #1405: feat:一键巡检功能
  content/zh/docs/web_ui/systemconfig/inspection/_index.md
  content/zh/docs/web_ui/systemconfig/inspection/inspection.md
Labels: size/M

#1408 fix: typo of host-disable
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1409 Automated cherry pick of #1408: fix: typo of host-disable
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1410 Automated cherry pick of #1408: fix: typo of host-disable
  content/zh/docs/faq/heterresource.md
Labels: size/XS

#1412 feat: monitor query api
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/monitor/_index.md
  content/zh/docs/development/monitor/query.md
Labels: size/L

#1413 Automated cherry pick of #1412: feat: monitor query api
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/monitor/_index.md
  content/zh/docs/development/monitor/query.md
Labels: size/L

#1414 Automated cherry pick of #1412: feat: monitor query api
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/monitor/_index.md
  content/zh/docs/development/monitor/query.md
Labels: size/L

#1411 fix: add cloud doc
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/L

#1418 Automated cherry pick of #1416: fix: add metric_query
  content/zh/docs/development/monitor/query.md
Labels: size/XS

#1419 feat:开源版无工单、镜像市场，宿主机相关说明补齐
  content/zh/docs/web_ui/computing/image/hostimage.md
  content/zh/docs/web_ui/computing/image/image.md
  content/zh/docs/web_ui/computing/image/market.md
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1421 Automated cherry pick of #1419: feat:开源版无工单、镜像市场，宿主机相关说明补齐
  content/zh/docs/web_ui/computing/image/hostimage.md
  content/zh/docs/web_ui/computing/image/image.md
  content/zh/docs/web_ui/computing/image/market.md
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1424 update v3.10.0 changelog
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.10/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.10/_index.md
Labels: size/XXL

#1426 release note for v3.10.0
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/release/v3_10_0.md
  content/zh/docs/setup/upgrade.md
Labels: size/XXL

#1428 update ee VERSIONS to 3.10
  Makefile.ee
Labels: size/XS

#1432 feat(3.10):优化开源文档快速开始增加一种安装方式说明
  content/zh/docs/quickstart/_index.md
Labels: size/XS

#1433 Automated cherry pick of #1432: feat(3.10):优化开源文档快速开始增加一种安装方式说明
  content/zh/docs/quickstart/_index.md
Labels: size/XS

#1430 fix: typo
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS

#1431 Automated cherry pick of #1430: fix: typo
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS
