Repository yunionio/docs, pull requests merged in 2023-02, with the labels that each got.

#1222 fix: update k8s preparing image distribution
  content/zh/docs/function_principle/k8s/pre_env/_index.md
Labels: size/XS

#1223 Automated cherry pick of #1222: fix: update k8s preparing image distribution
  content/zh/docs/function_principle/k8s/pre_env/_index.md
Labels: size/XS

#1225 feat(3.10):消息订阅新增全局admin，ip子网新增mac映射表
  content/zh/docs/web_ui/iam/notify/notify-topic.md
  content/zh/docs/web_ui/images/network/ipmac1.png
  content/zh/docs/web_ui/network/basicnetwork/network.md
Labels: size/M

#1227 fix(upgrade): checkout release_version
  content/en/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#1228 Automated cherry pick of #1227: fix(upgrade): checkout release_version
  content/en/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#1229 Automated cherry pick of #1227: fix(upgrade): checkout release_version
  content/en/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade.md
Labels: size/XS

#1231 Automated cherry pick of #1230: feat(setup): web http configuration
  content/zh/docs/setup/oc-update.md
  content/zh/docs/setup/web-use-http.md
Labels: size/L

#1233 update bilibili contact 20230211
  content/zh/docs/contact/_index.md
Labels: size/XS

#1234 Automated cherry pick of #1233: update bilibili contact 20230211
  content/zh/docs/contact/_index.md
Labels: size/XS

#1235 Automated cherry pick of #1233: update bilibili contact 20230211
  content/zh/docs/contact/_index.md
Labels: size/XS

#1239 fix: change upgrade steps
  content/zh/docs/setup/upgrade.md
Labels: size/S

#1240 Automated cherry pick of #1239: fix: change upgrade steps
  content/zh/docs/setup/upgrade.md
Labels: size/S

#1236 add ovs offload docs
  content/zh/docs/function_principle/onpremise/vminstance/sriov.md
Labels: size/M

#1237 Automated cherry pick of #1236: add ovs offload docs
  content/zh/docs/function_principle/onpremise/vminstance/sriov.md
Labels: size/M

#1238 feat(3.10):公有云权限列表介绍优化
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1244 update changelog of v3.9.7
  config-ee.toml
  config.toml
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-1.md
  content/zh/docs/development/changelog/release-3.9/3-9-2.md
  content/zh/docs/development/changelog/release-3.9/3-9-3.md
  content/zh/docs/development/changelog/release-3.9/3-9-4.md
  content/zh/docs/development/changelog/release-3.9/3-9-5.md
  content/zh/docs/development/changelog/release-3.9/3-9-6.md
  content/zh/docs/development/changelog/release-3.9/3-9-7.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1245 Automated cherry pick of #1244: update changelog of v3.9.7
  config-ee.toml
  config.toml
  content/zh/docs/development/changelog/release-3.9/3-9-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-1.md
  content/zh/docs/development/changelog/release-3.9/3-9-2.md
  content/zh/docs/development/changelog/release-3.9/3-9-3.md
  content/zh/docs/development/changelog/release-3.9/3-9-4.md
  content/zh/docs/development/changelog/release-3.9/3-9-5.md
  content/zh/docs/development/changelog/release-3.9/3-9-6.md
  content/zh/docs/development/changelog/release-3.9/3-9-7.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1247 fix: update upgrade content
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/setup/update_kernel.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#1248 Automated cherry pick of #1247: fix: update upgrade content
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/setup/update_kernel.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#1249 Automated cherry pick of #1247: fix: update upgrade content
  content/zh/docs/function_principle/onpremise/host/host-service.md
  content/zh/docs/setup/host.md
  content/zh/docs/setup/multi-zone.md
  content/zh/docs/setup/update_kernel.md
  content/zh/docs/setup/upgrade.md
Labels: size/M

#1243 feat(3.10):虚拟机监控监控查询优化、全局设置新增启用消费预测、云上日志同步开关
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/XS

#1251 feature: lbagent deployment
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/L

#1252 Automated cherry pick of #1251: feature: lbagent deployment
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/L

#1254 fix(3.10):vmware云账号纳管新增网络说明跳转链接
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1256 feat(3.10):监控新增聚合函数
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS
