Repository yunionio/docs, pull requests merged in 2023-05, with the labels that each got.

#1434 fix huagepage reserve docs
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
Labels: size/XS

#1435 Automated cherry pick of #1434: fix huagepage reserve docs
  content/zh/docs/function_principle/onpremise/vminstance/hugepage.md
Labels: size/XS

#1438 feat(3.10):3.10.1发布日志，H3C虚机相关操作及多云纳管步骤
  content/zh/docs/release/v3_10_1.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1439 Automated cherry pick of #1438: feat(3.10):3.10.1发布日志，H3C虚机相关操作及多云纳管步骤
  content/zh/docs/release/v3_10_1.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1440 fix: add pve feature switch
  content/zh/docs/setup/feature-config.md
Labels: size/XS

#1441 Automated cherry pick of #1440: fix: add pve feature switch
  content/zh/docs/setup/feature-config.md
Labels: size/XS

#1442 fix: add api doc
  content/zh/docs/development/add-api.md
Labels: size/XS

#1443 Automated cherry pick of #1442: fix: add api doc
  content/zh/docs/development/add-api.md
Labels: size/XS

#1445 feat(api): helm related apis
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/orchestration/_index.md
  content/zh/docs/development/orchestration/chart.md
  content/zh/docs/development/orchestration/release.md
  content/zh/docs/development/orchestration/repo.md
Labels: size/XL

#1456 feat: release v3.9.10
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.9/3-9-10.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-10.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/L

#1457 Automated cherry pick of #1456: feat: release v3.9.10
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.9/3-9-10.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.9/3-9-10.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/L

#1447 fix(climc): add climc token auto
  content/zh/docs/ops/climc/auth.md
Labels: size/S

#1448 Automated cherry pick of #1447: fix(climc): add climc token auto
  content/zh/docs/ops/climc/auth.md
Labels: size/S

#1451 Automated cherry pick of #1449: docs(docs): 新增3.10 repo 路径
  content/zh/docs/setup/repo.md
Labels: size/XS

#1450 Automated cherry pick of #1449: docs(docs): 新增3.10 repo 路径
  content/zh/docs/setup/repo.md
Labels: size/XS

#1449 docs(docs): 文档更新，新增3.10 repo 路径
  content/zh/docs/setup/repo.md
Labels: size/XS

#1452 feat(3.10):文档优化飞天hcso hcs资源对接支持情况
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/S

#1453 Automated cherry pick of #1452: feat(3.10):文档优化飞天hcso hcs资源对接支持情况
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/S

#1454 feat(3.10):文档宿主机增加预留核、权限增加域标签、云账号增量同步
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/iam/keystone/policy.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/M

#1455 Automated cherry pick of #1454: feat(3.10):文档宿主机增加预留核、权限增加域标签、云账号增量同步
  content/zh/docs/web_ui/computing/resources/host.md
  content/zh/docs/web_ui/iam/keystone/policy.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/M

#1458 feat(CI): release on tag
  .github/workflows/release.yml
Labels: size/XS

#1470 fix: create_register_redirect missing image
  content/zh/docs/function_principle/onpremise/baremetal/create_register_redirect.md
Labels: size/XS

#1468 docs: custom pci devices
  content/zh/docs/function_principle/onpremise/vminstance/custom-pci-devices.md
Labels: size/M

#1469 Automated cherry pick of #1468: docs: custom pci devices
  content/zh/docs/function_principle/onpremise/vminstance/custom-pci-devices.md
Labels: size/M

#1463 feat:v3.9.10发布日志
  content/zh/docs/release/v3_9_10.md
Labels: size/M

#1464 Automated cherry pick of #1463: feat:v3.9.10发布日志
  content/zh/docs/release/v3_9_10.md
Labels: size/M

#1466 fix: v3.10 sync new resource
  content/zh/docs/development/resource_sync/new_resource.md
Labels: size/XS

#1467 Automated cherry pick of #1466: fix: v3.10 sync new resource
  content/zh/docs/development/resource_sync/new_resource.md
Labels: size/XS

#1472 update lbagent docs
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/S

#1473 Automated cherry pick of #1472: update lbagent docs
  content/zh/docs/function_principle/onpremise/lb/lbagent.md
Labels: size/S

#1477 docs(intro.md): update `debian(arm64)` -> `debian(x86_64,arm64)`
  content/zh/docs/setup/intro.md
Labels: size/XS

#1478 Automated cherry pick of #1477: fix docs: intro.md
  content/zh/docs/setup/intro.md
Labels: size/XS

#1480 Automated cherry pick of #1479: fix: add '/' to version base url
  scripts/builder/hugo.py
Labels: size/XS

#1479 fix: add '/' to version base url
  scripts/builder/hugo.py
Labels: size/XS

#1482 fix: index provider img url
  content/en/_index.html
  content/zh/_index.html
Labels: size/XS

#1483 Automated cherry pick of #1482: fix: index provider img url
  content/en/_index.html
  content/zh/_index.html
Labels: size/XS

#1484 Automated cherry pick of #1482: fix: index provider img url
  content/en/_index.html
  content/zh/_index.html
Labels: size/XS

#1485 add customer logo
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/asiainfodata.png
  static/images/provider/changhong.png
  static/images/provider/grgbanking.png
  static/images/provider/iscas.png
  static/images/provider/stoneatom.png
  static/images/provider/tcl.png
Labels: size/S

#1486 Automated cherry pick of #1485: add customer logo
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/asiainfodata.png
  static/images/provider/changhong.png
  static/images/provider/grgbanking.png
  static/images/provider/iscas.png
  static/images/provider/stoneatom.png
  static/images/provider/tcl.png
Labels: size/S

#1487 Automated cherry pick of #1485: add customer logo
  content/en/_index.html
  content/zh/_index.html
  static/images/provider/asiainfodata.png
  static/images/provider/changhong.png
  static/images/provider/grgbanking.png
  static/images/provider/iscas.png
  static/images/provider/stoneatom.png
  static/images/provider/tcl.png
Labels: size/S

#1488 fix: add cloud sdk auth desc
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/S

#1489 Automated cherry pick of #1488: fix: add cloud sdk auth desc
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/S

#1492 Automated cherry pick of #1490: feat:常见问题增加“为什么部分平台无法纳管？”
  content/zh/docs/faq/others.md
Labels: size/XS

#1490 feat:常见问题增加“为什么部分平台无法纳管？”
  content/zh/docs/faq/others.md
Labels: size/XS

#1491 Automated cherry pick of #1490: feat:常见问题增加“为什么部分平台无法纳管？”
  content/zh/docs/faq/others.md
Labels: size/XS

#1493 feat:常见问题中外部数据导入仅商业版可见
  content/zh/docs/faq/cloudaccount/remotefile.md
Labels: size/XS

#1494 Automated cherry pick of #1493: feat:常见问题中外部数据导入仅商业版可见
  content/zh/docs/faq/cloudaccount/remotefile.md
Labels: size/XS
