Repository yunionio/docs, pull requests merged in 2023-09, with the labels that each got.

#1685 Automated cherry pick of #1684: docs: traffic limit and daemon server
  content/zh/docs/function_principle/onpremise/network/traffic_limit.md
  content/zh/docs/function_principle/onpremise/vminstance/daemon_server.md
Labels: size/M

#1651 增加all in one 卸载 数据库步骤
  content/zh/docs/setup/uninstall.md
Labels: size/M

#1704 feat: release 3.9.5
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.10/3-10-5.md
  content/en/docs/changelog/release-3.10/_index.md
  content/en/docs/changelog/release-3.9/3-9-13.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.10/3-10-5.md
  content/zh/docs/development/changelog/release-3.10/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-13.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XXL

#1703 Automated cherry pick of #1701: feat: image add box shadow style
  static/css/global.css
Labels: size/XS

#1701 feat: image add box shadow style
  static/css/global.css
Labels: size/S

#1702 Automated cherry pick of #1701: feat: image add box shadow style
  static/css/global.css
Labels: size/S

#1708 Automated cherry pick of #1706: feat(3.9):增加阿里云国际账号账单配置说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1707 Automated cherry pick of #1706: feat(3.9):增加阿里云国际账号账单配置说明
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1710 Automated cherry pick of #1709: feat(3.10):v3.10.5版本发布、gpu更新类型、新建硬盘指定块存储
  content/zh/docs/release/v3_10_5.md
  content/zh/docs/web_ui/computing/resources/gpu.md
  content/zh/docs/web_ui/computing/storage/disk.md
  content/zh/docs/web_ui/images/computing/gpu.png
  content/zh/docs/web_ui/images/computing/gpu1.png
Labels: size/M

#1712 docs/vgpu: change nvidia vgpu mark from # to $
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/vgpu.md
Labels: size/XS

#1713 Automated cherry pick of #1712: docs/vgpu: change nvidia vgpu mark from # to $
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/vgpu.md
Labels: size/XS

#1711 fix(region): 本地项目删除时, 重新建立映射关系
  content/zh/docs/function_principle/multicloud/cloudaccounts/project_sync.md
Labels: size/XS

#1718 feat(3.9):v3.9.13版本发布日志
  content/zh/docs/release/v3_9_13.md
Labels: size/S

#1719 Automated cherry pick of #1718: feat(3.9):v3.9.13版本发布日志
  content/zh/docs/release/v3_9_13.md
Labels: size/S

#1720 Automated cherry pick of #1718: feat(3.9):v3.9.13版本发布日志
  content/zh/docs/release/v3_9_13.md
Labels: size/S

#1733 fix: merge host troubleshooting steps
  content/zh/docs/function_principle/onpremise/host/hosterror.md
  content/zh/docs/function_principle/onpremise/host/troubleshooting.md
  content/zh/docs/quickstart/allinone-multicloud.md
  content/zh/docs/setup/host.md
Labels: size/L

#1730 feat(3.9):merge mirrors
  content/zh/docs/web_ui/computing/image/image.md
Labels: size/S

#1732 Automated cherry pick of #1730: feat(3.9):merge mirrors
  content/zh/docs/web_ui/computing/image/image.md
Labels: size/S

#1731 Automated cherry pick of #1730: feat(3.9):merge mirrors
  content/zh/docs/web_ui/computing/image/image.md
Labels: size/S

#1725 feat(3.10):improve release v3.10.5
  content/zh/docs/release/v3_10_5.md
Labels: size/M

#1726 Automated cherry pick of #1725: feat(3.10):improve release v3.10.5
  content/zh/docs/release/v3_10_5.md
Labels: size/M

#1722 Automated cherry pick of #1721: feat(3.10):ui策略新增定义、华为云纳管去除账号类型、工单增加主机关机重启
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
  content/zh/docs/web_ui/systemconfig/strategy/strategydefinition.md
  content/zh/docs/web_ui/systemconfig/workorder/processmanage.md
Labels: size/M

#1736 feat(master):容器计费、组织架构、全局设置增加开关
  content/zh/docs/function_principle/k8s/k8scharge.md
  content/zh/docs/function_principle/k8s/pre_env/images/podpvc.png
  content/zh/docs/web_ui/iam/keystone/domain.md
  content/zh/docs/web_ui/iam/keystone/group.md
  content/zh/docs/web_ui/iam/keystone/organization.md
  content/zh/docs/web_ui/iam/keystone/policy.md
  content/zh/docs/web_ui/iam/keystone/project.md
  content/zh/docs/web_ui/iam/keystone/role.md
  content/zh/docs/web_ui/iam/keystone/systemuser.md
  content/zh/docs/web_ui/images/iam/nav1.png
  content/zh/docs/web_ui/images/iam/org.png
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/L

#1739 Automated cherry pick of #1738: fix: add docs for subips
  content/zh/docs/function_principle/onpremise/network/subips.md
Labels: size/M

#1741 update telegraf rpm url
  content/zh/docs/ops/agent.md
Labels: size/XS

#1744 Automated cherry pick of #1740: Update baremetal.md
  content/zh/docs/setup/baremetal.md
Labels: size/XS

#1740 修改 启用baremetal agent 文案信息
  content/zh/docs/setup/baremetal.md
Labels: size/XS

#1745 host_raid.adpter 开启说明
  content/zh/docs/web_ui/monitor/alert/commonalerts.md
Labels: size/XS

#1742 fix:add docs for qga
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip.png
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip_dashboard.png
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip_detail.png
  content/zh/docs/function_principle/onpremise/vminstance/images/curr_net.png
  content/zh/docs/function_principle/onpremise/vminstance/images/prev_net.png
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
Labels: lgtm, size/L

#1747 Automated cherry pick of #1742: fix:add docs for qga
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip.png
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip_dashboard.png
  content/zh/docs/function_principle/onpremise/vminstance/images/change_ip_detail.png
  content/zh/docs/function_principle/onpremise/vminstance/images/curr_net.png
  content/zh/docs/function_principle/onpremise/vminstance/images/prev_net.png
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
Labels: size/L

#1748 fix: misc 20230927
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/quickstart/_index.md
Labels: size/S

#1749 Automated cherry pick of #1748: fix: misc 20230927
  content/zh/docs/function_principle/onpremise/network/examples.md
  content/zh/docs/quickstart/_index.md
Labels: size/S
