Repository yunionio/docs, pull requests merged in 2023-08, with the labels that each got.

#1639 Automated cherry pick of #1638: feat(3.10):v3.10.4 release note
  content/zh/docs/release/v3_10_4.md
Labels: size/M

#1640 fix: customize pci device
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices.md
Labels: size/M

#1641 Automated cherry pick of #1640: fix: customize pci device
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/custom-pci-devices.md
Labels: size/M

#1642 fix: add k8s-cluster-set-kubeconfig content
  content/zh/docs/function_principle/k8s/readonly-import.md
Labels: size/S

#1643 Automated cherry pick of #1642: fix: add k8s-cluster-set-kubeconfig content
  content/zh/docs/function_principle/k8s/readonly-import.md
Labels: size/S

#1648 feat(3.9):daemon虚拟机改为自动启动
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1650 Automated cherry pick of #1648: feat(3.9):daemon虚拟机改为自动启动
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/M

#1649 Automated cherry pick of #1648: feat(3.9):daemon虚拟机改为自动启动
  content/zh/docs/web_ui/computing/server/vminstance.md
Labels: size/XS

#1657 feat(3.9):阿里云获取短信参数文案修改
  content/zh/docs/web_ui/iam/notify/mailconfig.md
Labels: size/XS

#1659 Automated cherry pick of #1657: feat(3.9):阿里云获取短信参数文案修改
  content/zh/docs/web_ui/iam/notify/mailconfig.md
Labels: size/XS

#1658 Automated cherry pick of #1657: feat(3.9):阿里云获取短信参数文案修改
  content/zh/docs/web_ui/iam/notify/mailconfig.md
Labels: size/XS

#1653 feat(3.10):cloudshell开关、阿里eip线路类型、平台升级记录
  content/zh/docs/web_ui/computing/network/eip.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/intro/ui/about.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/S

#1654 Automated cherry pick of #1653: feat(3.10):cloudshell开关、阿里eip线路类型、平台升级记录
  content/zh/docs/web_ui/computing/network/eip.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/intro/ui/about.md
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
Labels: size/S

#1655 vgpu configure docs
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/gpu.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/vgpu.md
Labels: size/L

#1656 Automated cherry pick of #1655: vgpu configure docs
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/gpu.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/vgpu.md
Labels: size/L

#1644 docs: ovs offload nic config
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
Labels: size/L

#1645 Automated cherry pick of #1644: docs: ovs offload nic config
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
Labels: size/L

#1660 feat(4326): table fixed title
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/L

#1662 feat(4326): table fixed title
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/L

#1661 Automated cherry pick of #1660: feat(4326): table fixed title
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
Labels: size/L

#1663 fix: go error return spec
  content/zh/docs/development/specification.md
Labels: size/S

#1665 fix: project sync
  content/zh/docs/function_principle/multicloud/cloudaccounts/project_sync.md
Labels: size/M

#1666 Automated cherry pick of #1665: fix: project sync
  content/zh/docs/function_principle/multicloud/cloudaccounts/project_sync.md
Labels: size/M

#1667 fix: aliyun waf sync
  content/zh/docs/faq/sync.md
Labels: size/XS

#1669 feat(3.10):百度云联通云金山云青云纳管文档
  content/zh/docs/faq/image/baidu-accesskeys.png
  content/zh/docs/faq/image/baidu-get_access_key_secret.png
  content/zh/docs/faq/image/baidu-get_accesskey_list.png
  content/zh/docs/faq/image/jinshan-accesskeys.png
  content/zh/docs/faq/image/jinshan-get_access_key_secret.png
  content/zh/docs/faq/image/liantong-accesskeys.png
  content/zh/docs/faq/image/liantong-accesskeys1.png
  content/zh/docs/faq/image/liantong-get_access_key_secret.png
  content/zh/docs/faq/image/qingcloud-accesskeys.png
  content/zh/docs/faq/image/qingcloud-get_access_key_secret.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1670 Automated cherry pick of #1669: feat(3.10):百度云联通云金山云青云纳管文档
  content/zh/docs/faq/image/baidu-accesskeys.png
  content/zh/docs/faq/image/baidu-get_access_key_secret.png
  content/zh/docs/faq/image/baidu-get_accesskey_list.png
  content/zh/docs/faq/image/jinshan-accesskeys.png
  content/zh/docs/faq/image/jinshan-get_access_key_secret.png
  content/zh/docs/faq/image/liantong-accesskeys.png
  content/zh/docs/faq/image/liantong-accesskeys1.png
  content/zh/docs/faq/image/liantong-get_access_key_secret.png
  content/zh/docs/faq/image/qingcloud-accesskeys.png
  content/zh/docs/faq/image/qingcloud-get_access_key_secret.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/_index.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/L

#1671 feat(3.10):堡垒机、表头固定、自定义数据支持私有云公有云、水印
  content/zh/docs/function_principle/multicloud/_index.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/images/bill/analysis.png
  content/zh/docs/web_ui/images/bill/analysis1.png
  content/zh/docs/web_ui/images/system/fortress.png
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
  content/zh/docs/web_ui/systemconfig/system/fortress.md
  static/css/global.css
Labels: size/XXL

#1672 Automated cherry pick of #1671: feat(3.10):堡垒机、表头固定、自定义数据支持私有云公有云、水印
  content/zh/docs/function_principle/multicloud/_index.md
  content/zh/docs/web_ui/computing/server/vminstance.md
  content/zh/docs/web_ui/cost/analysis/billanalysis.md
  content/zh/docs/web_ui/images/bill/analysis.png
  content/zh/docs/web_ui/images/bill/analysis1.png
  content/zh/docs/web_ui/images/system/fortress.png
  content/zh/docs/web_ui/systemconfig/globalsetting/globalsetting.md
  content/zh/docs/web_ui/systemconfig/system/fortress.md
  static/css/global.css
Labels: size/XXL

#1673 fix: azure创建订阅设置
  content/zh/docs/function_principle/multicloud/cloudaccounts/azure_subscription.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_app_id.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_assign_role.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_cloud_shell.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_enrollment_account.png
Labels: size/M

#1674 Automated cherry pick of #1673: fix: azure创建订阅设置
  content/zh/docs/function_principle/multicloud/cloudaccounts/azure_subscription.md
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_app_id.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_assign_role.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_cloud_shell.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/images/az_enrollment_account.png
Labels: size/M

#1675 Update upload.md：如何关闭自动转换vmdk镜像
  content/zh/docs/function_principle/onpremise/glance/sysimage/upload.md
Labels: size/XS

#1676 Automated cherry pick of #1675: Update upload.md：如何关闭自动转换vmdk镜像
  content/zh/docs/function_principle/onpremise/glance/sysimage/upload.md
Labels: size/XS

#1677 fix: add azure dev and test offer doc
  content/zh/docs/function_principle/multicloud/cloudaccounts/azure_subscription.md
Labels: size/XS

#1678 Automated cherry pick of #1677: fix: add azure dev and test offer doc
  content/zh/docs/function_principle/multicloud/cloudaccounts/azure_subscription.md
Labels: size/XS

#1683 Automated cherry pick of #1682: feat(3.10):部署文档区分edge、cmp、fullstack
  content/zh/docs/introduce/_index.md
  content/zh/docs/quickstart/_index.md
  content/zh/docs/quickstart/allinone-converge.md
  content/zh/docs/quickstart/allinone-multicloud.md
  content/zh/docs/quickstart/allinone-private.md
  content/zh/docs/quickstart/docker-compose.md
  content/zh/docs/quickstart/k8s.md
  static/css/global.css
Labels: size/L

#1684 docs: traffic limit and daemon server
  content/zh/docs/function_principle/onpremise/network/traffic_limit.md
  content/zh/docs/function_principle/onpremise/vminstance/daemon_server.md
Labels: size/M

#1686 fix: broken eipgwhowto link
  content/zh/docs/function_principle/onpremise/network/vpc/eiphowto.md
Labels: size/XS

#1687 Automated cherry pick of #1686: fix: broken eipgwhowto link
  content/zh/docs/function_principle/onpremise/network/vpc/eiphowto.md
Labels: size/XS
