Repository yunionio/docs, pull requests merged in 2023-10, with the labels that each got.

#1751 Automated cherry pick of #1750: feat: add issue process content
  content/zh/docs/development/issue-process.md
Labels: size/M

#1752 add issue usage content
  content/zh/docs/development/issue-process.md
Labels: size/M

#1756 fix: dead links of issue page
  content/zh/docs/development/issue-process.md
Labels: size/S

#1754 fix: climc auth revisit 20231003
  content/zh/docs/ops/climc/auth.md
Labels: size/M

#1755 Automated cherry pick of #1754: fix: climc auth revisit 20231003
  content/zh/docs/ops/climc/auth.md
Labels: size/M

#1758 fix: update issue close strategy
  content/zh/docs/development/issue-process.md
Labels: size/S

#1761 Automated cherry pick of #1760: feat: hide ee content
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#1762 Automated cherry pick of #1760: feat: hide ee content
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#1760 feat: hide ee content
  content/zh/docs/quickstart/k8s.md
  content/zh/docs/setup/ce-ee-switch.md
Labels: size/S

#1763 feat(development): add monitor API example
  content/zh/docs/development/monitor/query.md
Labels: size/M

#1765 feat(notify): add desc for webhook
  content/zh/docs/development/images/webhook_config.jpg
  content/zh/docs/development/images/webhook_result.jpg
  content/zh/docs/development/webhook.md
Labels: size/S

#1766 Automated cherry pick of #1765: feat(notify): add desc for webhook
  content/zh/docs/development/images/webhook_config.jpg
  content/zh/docs/development/images/webhook_result.jpg
  content/zh/docs/development/webhook.md
Labels: size/S

#1767 release: 3.10.6 and 3.9.14
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.10/3-10-6.md
  content/en/docs/changelog/release-3.10/_index.md
  content/en/docs/changelog/release-3.9/3-9-14.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.10/3-10-6.md
  content/zh/docs/development/changelog/release-3.10/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-14.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1768 Automated cherry pick of #1767: release: 3.10.6 and 3.9.14
  config-ee.toml
  config.toml
  content/en/docs/changelog/release-3.10/3-10-0.md
  content/en/docs/changelog/release-3.10/3-10-6.md
  content/en/docs/changelog/release-3.10/_index.md
  content/en/docs/changelog/release-3.9/3-9-14.md
  content/en/docs/changelog/release-3.9/_index.md
  content/zh/docs/development/changelog/release-3.10/3-10-0.md
  content/zh/docs/development/changelog/release-3.10/3-10-6.md
  content/zh/docs/development/changelog/release-3.10/_index.md
  content/zh/docs/development/changelog/release-3.9/3-9-14.md
  content/zh/docs/development/changelog/release-3.9/_index.md
Labels: size/XL

#1771 fix(development): add desc for notify
  content/zh/docs/development/images/subscriber.jpg
  content/zh/docs/development/images/webhook_result.jpg
  content/zh/docs/development/webhook.md
Labels: do-not-merge/hold, size/L

#1774 Automated cherry pick of #1771: fix(development): add desc for notify
  content/zh/docs/development/images/subscriber.jpg
  content/zh/docs/development/images/webhook_result.jpg
  content/zh/docs/development/webhook.md
Labels: size/L

#1769 fix: add ctyun access key doc
  content/zh/docs/faq/image/ctyun.png
  content/zh/docs/faq/image/ctyunaccesskey.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1770 Automated cherry pick of #1769: fix: add ctyun access key doc
  content/zh/docs/faq/image/ctyun.png
  content/zh/docs/faq/image/ctyunaccesskey.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1775 fix(development): fix webhook doc
  content/zh/docs/development/webhook.md
Labels: size/XS

#1776 Automated cherry pick of #1775: fix(development): fix webhook doc
  content/zh/docs/development/webhook.md
Labels: size/XS

#1777 fix: 接入云错误信息判断说明
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS

#1778 Automated cherry pick of #1777: fix: 接入云错误信息判断说明
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/XS

#1784 fix: update linux supported distributions
  content/zh/docs/quickstart/allinone-converge.md
  content/zh/docs/quickstart/allinone-multicloud.md
  content/zh/docs/quickstart/allinone-private.md
Labels: size/M

#1786 “CentOS 7”改为“CentOS 7.6~7.9 Minimal”
  content/zh/docs/quickstart/allinone-converge.md
Labels: size/XS

#1789 Automated cherry pick of #1786: “CentOS 7”改为“CentOS 7.6~7.9 Minimal”
  content/zh/docs/quickstart/allinone-converge.md
Labels: size/XS

#1787 “CentOS 7”改为“CentOS 7.6~7.9 Minimal”
  content/zh/docs/quickstart/allinone-private.md
Labels: size/XS

#1788 “CentOS 7”改为“CentOS 7.6~7.9 Minimal”
  content/zh/docs/quickstart/allinone-multicloud.md
Labels: size/XS

#1792 fix: clean oem info
  Makefile
  Makefile.ee
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/monitor/_index.md
  content/zh/docs/function_principle/k8s/readonly-import.md
  content/zh/docs/function_principle/multicloud/networks/dns.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/upload.md
  content/zh/docs/function_principle/onpremise/host/reservecpus.md
  content/zh/docs/function_principle/onpremise/scheduler/algorithm.md
  content/zh/docs/function_principle/onpremise/scheduler/schedtags.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
  content/zh/docs/ops/climc/_index.md
  content/zh/docs/ops/migrate.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  scripts/builder/drivers.py
  scripts/saas-build.py
Labels: size/M

#1793 Automated cherry pick of #1792: fix: clean oem info
  Makefile
  Makefile.ee
  content/zh/docs/development/docs-dev.md
  content/zh/docs/development/monitor/_index.md
  content/zh/docs/function_principle/k8s/readonly-import.md
  content/zh/docs/function_principle/multicloud/networks/dns.md
  content/zh/docs/function_principle/onpremise/glance/sysimage/upload.md
  content/zh/docs/function_principle/onpremise/host/reservecpus.md
  content/zh/docs/function_principle/onpremise/scheduler/algorithm.md
  content/zh/docs/function_principle/onpremise/scheduler/schedtags.md
  content/zh/docs/function_principle/onpremise/storage/blockstorage/lvm-storage.md
  content/zh/docs/function_principle/onpremise/vminstance/passthrough/sriov.md
  content/zh/docs/function_principle/onpremise/vminstance/qga.md
  content/zh/docs/ops/climc/_index.md
  content/zh/docs/ops/migrate.md
  content/zh/docs/setup/_index.md
  content/zh/docs/setup/components.md
  content/zh/docs/setup/controlplane-ha.md
  scripts/builder/drivers.py
  scripts/saas-build.py
Labels: size/M

#1795 fix: make oem image
  Makefile
  Makefile.ee
Labels: size/XS

#1797 fix: misc updates
  content/zh/docs/function_principle/multicloud/vmware/_index.md
  content/zh/docs/function_principle/multicloud/vmware/vmware.md
  content/zh/docs/function_principle/multicloud/vmware/vmware_net.md
  content/zh/docs/function_principle/multicloud/vmware/vmware_v2v.md
  content/zh/docs/function_principle/multicloud/vmware/vmwarenet.png
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/function_principle/onpremise/network/reservedip.md
Labels: size/L

#1798 Automated cherry pick of #1797: fix: misc updates
  content/zh/docs/function_principle/multicloud/vmware/_index.md
  content/zh/docs/function_principle/multicloud/vmware/vmware.md
  content/zh/docs/function_principle/multicloud/vmware/vmware_net.md
  content/zh/docs/function_principle/multicloud/vmware/vmware_v2v.md
  content/zh/docs/function_principle/multicloud/vmware/vmwarenet.png
  content/zh/docs/function_principle/onpremise/glance/common.md
  content/zh/docs/function_principle/onpremise/network/reservedip.md
Labels: size/L

#1799 fix: db ha doc keepalived fixes
  content/zh/docs/setup/db-ha.md
Labels: size/M

#1800 Automated cherry pick of #1799: fix: db ha doc keepalived fixes
  content/zh/docs/setup/db-ha.md
Labels: size/M

#1801 fix: vmware net image missing
  content/zh/docs/function_principle/multicloud/vmware/vmware_net.md
Labels: size/XS

#1802 Automated cherry pick of #1801: fix: vmware net image missing
  content/zh/docs/function_principle/multicloud/vmware/vmware_net.md
Labels: size/XS

#1779 fix: 安全组逻辑改动
  content/zh/docs/function_principle/multicloud/compute/secgroup/principle.md
Labels: size/M

#1781 fix(development): Add debug reference link to add-cloud.md.
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/L

#1803 Automated cherry pick of #1781: fix(development): Add debug reference link to add-cloud.md.
  content/zh/docs/development/resource_sync/add-cloud.md
Labels: size/L

#1805 Automated cherry pick of #1804: fix: update rook with v16 ceph
  content/zh/blog/_posts/2021-10-09-rook-ceph-with-cloudpods/index.md
Labels: size/M
