Repository yunionio/docs, pull requests merged in 2024-05, with the labels that each got.

#1904 更新azure云账号提示信息
  content/zh/docs/faq/image/azure1.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/aws.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1902 更新oracle云录入参数
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/XS

#1905 Automated cherry pick of #1904: 更新oracle云录入参数
  content/zh/docs/faq/image/azure1.png
  content/zh/docs/function_principle/multicloud/cloudaccounts/aws.md
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/S

#1903 更新Azure账单存储桶获取方式
  content/zh/docs/faq/image/azure_bucket-1.png
  content/zh/docs/faq/image/azure_bucket-2.png
  content/zh/docs/faq/image/azure_bucket-3.png
  content/zh/docs/faq/image/azure_bucket-4.png
  content/zh/docs/faq/image/azure_bucket-5.png
  content/zh/docs/faq/image/azure_bucket-6.png
  content/zh/docs/faq/image/azure_bucket-7.png
  content/zh/docs/web_ui/multiplecloud/cloudaccount/cloudaccount.md
Labels: size/M
